### PR TITLE
update author status for Dr. Quinn

### PR DESCRIPTION
**Pull request by raj-sivakumar-zz**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.
@deniederhut can this new change be merged in. I hadn't realized the correct terminology for a senior author and amended that in the paper

### CODE REVIEW

**Comment by raj-sivakumar-zz** [comment]
paging @deniederhut Hope your day is going well! Just checking into make sure this amendment can be pushed

**Comment by deniederhut** [comment]
Hey! Sorry for missing this. I think the tag you want is just `:corresponding:`.

**Comment by raj-sivakumar-zz** [comment]
@deniederhut changed to the correct tag this time
looks now okay

**Review by deniederhut — APPROVED** [review]

**Comment by deniederhut** [comment]
Thanks!

**Pull request merged**
