### PR TITLE
Paper: test .rst paper

### PR DESCRIPTION
**Pull request by mepa**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: @mepa

*Reviewers*: @mepa

### CODE REVIEW

**Comment by mepa** [comment]
@scoobies help

**Comment by mepa** [comment]
@scoobies help

**Comment by scoobies** [comment]
Hello @mepa, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from branch custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

**Comment by mepa** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper mepa-tmp-test-paper-rst scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by mepa** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"mepa-tmp-test-paper-rst"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmprdvewbai'...\nMoving proceedings build tools to temp directory...\n[X] No papers found: []\nA build error occurred during the self.paper step.", "build_pdf_path"=>"", "build_status"=>"Paper not found", "build_timestamp"=>"24/05 22:23"}, "status"=>"fail"}}

**Comment by mepa** [comment]
@scoobies mark server fail

**Comment by mepa** [comment]
@scoobies code of conduct

**Comment by scoobies** [comment]
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

**Comment by scoobies** [comment]
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

**Comment by mepa** [comment]
@scoobies assign @mepa as editor

**Comment by scoobies** [comment]
Assigned! @mepa is now the editor

**Comment by mepa** [comment]
@scoobies add @mepa to reviewers

**Comment by scoobies** [comment]
@mepa added to the reviewers list!

**Comment by mepa** [comment]
@scoobies check references

**Comment by mepa** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper mepa-tmp-test-paper-rst scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by mepa** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"mepa-tmp-test-paper-rst"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpol5ajzy6'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: test_rst\n*** Warning: /tmp/tmpol5ajzy6/publisher/../output/test_rst/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/mepa-tmp-test-paper-rst.pdf", "build_status"=>"success", "build_timestamp"=>"24/05 22:53"}, "status"=>"success"}}

**Comment by mepa** [comment]
@scoobies check references

**Comment by mepa** [comment]
@scoobies mark server success

**Comment by mepa** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Pull request closed without merging**
