### PR TITLE
Gagnon Tahiri - FINAL

### PR DESCRIPTION
**Pull request by JustGag**
If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

### CODE REVIEW

**Comment by JustGag** [comment]
@rowanc1 @cbcunc Once again, we're sorry for the delay and, as we promised, we've pushed through the final paper version and won't be touching it again. We'd be interested to get the link to the latest version of our paper, to see if the latest changes to the text and figures have been followed correctly. Thank you so much. Sincerely,

**Comment by rowanc1** [comment]
We have merged your changes in, I have made a few updates:

https://github.com/scipy-conference/scipy_proceedings/commit/f792cb1d88e62384a276be0f235c91a79fd23179

You were missing two references and I moved to `autoref` and fixed subscript in math mode (textsubscript is not allowed).

I will get the final version up very soon.

**Comment by JustGag** [comment]
> We have merged your changes in, I have made a few updates:
> 
> [f792cb1](https://github.com/scipy-conference/scipy_proceedings/commit/f792cb1d88e62384a276be0f235c91a79fd23179)
> 
> You were missing two references and I moved to `autoref` and fixed subscript in math mode (textsubscript is not allowed).
> 
> I will get the final version up very soon.

@rowanc1 Thank you very much for your adjustments to our paper. We look forward to the final version. Sincerely,

**Comment by rowanc1** [comment]
Hi @JustGag the paper is now live, with the PDF at:

https://proceedings.scipy.org/articles/NVYF1037

**Comment by JustGag** [comment]
> Hi @JustGag the paper is now live, with the PDF at:
> 
> https://proceedings.scipy.org/articles/NVYF1037

Hi @rowanc1 Thank you for converting our paper to PDF. 

We wanted to know, since we hadn't anticipated the PDF layout, if we had to make minor adjustments related to sources and the size of certain figures, would it be possible to apply them?

Sincerely,

**Comment by rowanc1** [comment]
The PDF generation is not very flexible, is there a figure you have in mind that needs attention?

**Comment by JustGag** [comment]
> The PDF generation is not very flexible, is there a figure you have in mind that needs attention?

After comparing the paper on the SciPy site and the PDF, we can see that this may be due to the conversion to PDF. Would it be possible to send them back to you with the excess margins removed from the figure images?

As for the sources, we'd like to reverse the order in which they appear throughout the aPhyloGeo section, from \citep{li2024host, li2023aphylogeo, koshkarov_phylogeography_2022} to \citep{koshkarov_phylogeography_2022, li2023aphylogeo, li2024host}. There's also one in the Robinson-Foulds distance section: \citep{li2024comparison, tahiri2018new} to \citep{tahiri2018new, li2024comparison}. 

P-s: At this point, do these adjustments have to come from our side or yours?

Thank you for your understanding. 

Sincerely,

**Comment by rowanc1** [comment]
Feel free to open another pull request to change these small things. Please ensure that it is rebasing on top of the 2024 branch!

**Comment by JustGag** [comment]
Hi @rowanc1, we've made the necessary changes and opened a new pull request for our paper. 

Thank you very much.

Sincerely,

**Pull request merged**
