### PR TITLE
Add "New CUDA Toolkit packages for Conda" slides

### PR DESCRIPTION
**Pull request by jakirkham**
This adds the slides for the "New CUDA Toolkit packages for Conda"

ref: https://cfp.scipy.org/2023/talk/DQR9NU/

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @thomcom @rlratzel

**Review by deniederhut — APPROVED** [review]
giphy-1718213996

**Comment by jakirkham** [comment]
Thanks Dillon! 🙏

**Comment by deniederhut** [comment]
🙏

**Pull request merged**
