### PR TITLE
Paper: Exploring the Extended Kalman Filter

### PR DESCRIPTION
**Pull request by mwickert**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by yingweiy** [comment]
Review comments:
The authors implemented the Extended Kalman Filter (EKF) that applied to GPS with simulated data set. The paper is clear, and well-written. Overall, I agree to accept the paper. 

Here are some detailed/minor comments:

1. First paragraph in Introduction section: 
The Global positioning system => The Global Positioning System (GPS)

2. Page 4, code under Fig. 5: 
What is the @ char in the code?

3. Page 6, second last paragraph in left column: 
Case#$1 => Case#1 

4. Fig. 11 and Fig. 13:
It looks like the error of these experiments are much larger. Should you consider using the Unscented Kalman Filter (UKF) to get a better Gaussian distribution estimation after nonlinear transform? I believe it will improve the "corners" in the trajectory as shown in Fig 13.

See paper:
 Courses, E.; Surveys, T. (2006). "Sigma-Point Filters: An Overview with Applications to Integrated Navigation and Vision Assisted Control". Nonlinear Statistical Signal Processing Workshop, 2006 IEEE: 201–202. doi:10.1109/NSSPW.2006.4378854. ISBN 978-1-4244-0579-4.


5. Add citation to the original Kalman Filter:
 R.E. Kalman (1960). "A New Approach to Linear Filtering and Prediction Problems". Journal of Basic Engineering: 35–45.

**Comment by mwickert** [comment]
yingweiy,

Thanks for your comments. I will soon be pushing changes to address your (1), (3), and (5) comments.

Regarding (2) I have used, @, the Python 3.5+ operator overloading syntax for matrix multiply. In the PDF version of the paper when I format to produce a Python syntax code block it adds a red square around the @. I'm not sure how to fix this? Any ideas would be appreciated.

Regarding (4), I too like the use of the UKF and have that in the Jupyter notebooks I created for the training class. I do not however have the GPS tracking example coded at present. In the paper I elected to stay with the EKF, as the next logical step beyond the linear KF, and because it is discussed in the Brown reference. I see two paths to take: (1) When the EKF results are presented I can add a short discussion about the advantages of the UKF, including also how it is not sensitive to initial conditions like the EKF is. I can then discuss this as a future addition to the training Jupyter notebook; (2) Go off and work through the details, both writing and coding, of the UKF for the GPS problem and do rework of the paper, perhaps removing the EKF section and replacing it with the UKF.

**Comment by yingweiy** [comment]
Hi Mark,

Thank you for your reply!

Regarding (2), I suggest you use numpy function of matrix multiply to improve the readability and avoid the display problem.

Regarding (4), for this submission you can stay with EKF, and add some discussion of UKF should be fine.

Best Regards,
Yingwei Yu

**Comment by mrocklin** [comment]
This paper is a well written exposition of the Extended Kalman Filter.  The paper and the code artifact should be a useful aid in education.

I have no major concern with the paper itself, however I do think that we need to address whether or not the scope of the paper suffices for the SciPy conference proceedings.  According to the [review criteria](https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md) papers must meet novelty requirements:

- The work should employ new or innovative methods or approaches to a problem.
- The work should advance the state of a scientific domain, the practice of scientific computing itself, or another subject area within the scope of the conference.

It is not clear to me that the contents of this paper meet these requirements.  @mwickert do you have thoughts here?  Are there particular grounds on which you would like this submission to be judged for novelty?

Alternatively if a proceedings chair is around and able to help clarify that would be useful.

**Comment by mwickert** [comment]
mrocklin,

Thanks for your comments.

I have expanded the introduction to include more details on what I think makes the tool unique. I have not pushed the edits yet, but below is what I am proposing:

The Global Positioning System (GPS) allows user position estimation using time difference of 
arrival (TDOA) measurements from signals received from a constellation of 24 medium earth orbit 
satellites of space vehicles (SVs). The Kalman filter is a popular optimal *state estimation* 
algorithm [Simon2006]_ used 
by a variety of engineering and science disciplines. In particular the extended Kalman filter (EKF) 
is able to deal with nonlinearities related to both the measurement equations and state vector 
process update model. The EKF used in GPS has a linear  process model, but a nonlinear measurement 
model [Brown2012]_. This paper describes a Python computational tool for exploring the use of the 
EKF for GPS position estimation using pseudorange measurements. The development was motivated by the need for an example generator in a training class on Kalman filtering, with emphasis on GPS. 
What is special about the tool created here is that both *User* and satellite trajectories 
are custom generated for input to a Kalman filter implemented in a Jupyter notebook. The steps followed are logical and clear. You first enter a desired *User* trajectory/route, then choose appropriate *in-view* GPS satellites, and then using actual GPS satellite orbital mechanics information, 
create a simulated receiver measurement stream. A 3D plot shows you the satellite tracks in 
space and the User trajectory on the surface of the earth, over time. The Kalman filter code, also defined in the Jupyter notebook, uses the matrix math commonly found in textbooks, but it is easy to follow  as we make use of the PEP 465 @ infix operator for matrix multiplication. 
As the final step, the data set is played through the Kalman filter in earth-centered 
earth-fixed (ECEF) coordinates. The User trajectory is input in local east-north-up (ENU) 
coordinates, and the SVs used to form the location estimate specified by the coarse 
acquisition (C/A) code pseudo-random noise (PRN) number, of the SVs in view by the User. The ECEF coordinates of the SVs are then propagated along with the User trajectory using [SGP4]_ and the two-line element (TLE) data available from [Celestrak]_. The relationship between ECEF and ENU is 
explained in Figure :ref:`ECEFENU`. For convenience, this computational tool, is housed in a Jupyter 
notebook. Data set generation and 3D trajectory plotting is provided with the assistance of a 
single module, :code:`GPS_helper.py`.

**Comment by mwickert** [comment]
yingweiy,

In my local version, not pushed yet, besides revamping the introduction, as you can see in my response to mrocklin, I have added a reference to the paper you mention on UKF and SPKF. I have in particular made changes to the last paragraph of the Simulation Examples section and modified the Conclusion. I want to the leave the use of the infix operator, @, for matrix multiplication, as I see it to be very useful in matching textbook math to the actual Python code. 

I would like help from someone in the community on how to format Python code blocks in .rst to avoid the red boxes seen in the pdf.

Below is the proposed modified source at the end of the paper:

It is worthy of note at this point that the *Unscented Kalman Filter* (UKF) [Wan2006]_, and the 
more general class of algorithms known as *Sigma-Point Kalman Filters* (SPKF), are today much 
preferred to the  EKF of the past. The EKF is sub-optimal, and the linearization approach makes it sensitive to initial conditions. The EKF requires the Jacobian matrix, which may be hard to obtain, and 
may not converge without carefully chosen initial conditions. In this paper the EKF was chosen for use in a training scenario because it is the next logical step from the linear Kalman filter, and its development is simple to follow. The UKF is harder to get explain. In the end, the UKF is of similar complexity to the EKF, can offer large performance benefits, and does not require the use of a Jacobian.

Conclusions and Future Work
---------------------------

The objective of creating a Jupyter notebook-based simulation tool for studying the use of 
the EKF in GPS position estimation has been met. There are many tuning options to explore, which 
provides a very nice environment for studying a large variety scenarios. The 
performance results are consistent with expectations.

There are several improvements under consideration. The first is to develop a more realistic user 
trajectory generator. The second is to make measurement quality a function of the SV range, which would also make the measurement quality SV specific, rather than identical as it is now. A third desire is to move to the UKF to avoid the use of the Jacobian, reduce the sensitivity to initial conditions, 
and improve performance.

**Comment by deniederhut** [comment]
@mrocklin - thanks for the question! I've pinged the other chairs and will report back to you when we have a reasonable consensus. In the mean time, we would rather paper PRs not make changes to the rest of the repo. @mwickert, could I ask you to revert d042704f0ffe169f9b43a982b29d3afc47b4dc50?

**Comment by deniederhut** [comment]
Okay, the proceedings committee has had a quick chat about this and here is our position. We feel that judgments about the scientific merit of a paper, including its novelty, fall more naturally within the purview of the program committee. Our primary concern during open review is to aid authors in making the prose in their papers more understandable, and the methods in them reproducible.

**Comment by mwickert** [comment]
Dillon,

From what you say, I will continue to work with my reviewers on what you have just said.

**Comment by mrocklin** [comment]
@mwickert thanks for following up with the changed introduction.  It sounds like a lot of the benefits of this paper are around education and ease of understanding.  I wonder if it then makes more sense to focus on how effective it was in education and spend a little less time describing the extended kalman filter.  Was this used in a class?  If so how effective was it?  What are some things that you learned along the way after engaging students with it?  You mention that using Jupyter notebooks and the matrix multiply operator were particularly important, why was this?

**Comment by mrocklin** [comment]
I'm not particularly seeking answers to those questions here in the github issue, but more to highlight that that is the kind of analysis I would expect from a paper who was targetting an educational output.  

As is written now this paper seems more like the educational output itself, an explanation of a particular formulation of the kalman filter.  I fully believe that this sort of educational output is valuable, but for a research publication it might make more sense to describe how such an educational resource was used, and how lessons learned from that experience can improve future researchers or educators.

**Comment by mrocklin** [comment]
> We feel that judgments about the scientific merit of a paper, including its novelty, fall more naturally within the purview of the program committee.  Our primary concern during open review is to aid authors in making the prose in their papers more understandable, and the methods in them reproducible.

Noted.  Happy to change course.  Perhaps the program committee should change the criteria given to reviewers to remove the section on judging novelty and impact?  https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md#novelty-and-impact

**Comment by mwickert** [comment]
mrocklin,

I have some thoughts on what I could do to the paper, but before I push more changes I will answer your questions, and hopefully give more time for my co-author to get back to me.

1. *It sounds like a lot of the benefits of this paper are around education and ease of understanding. I wonder if it then makes more sense to focus on how effective it was in education and spend a little less time describing the extended kalman filter.* You are in part correct to say ease of understanding is a big deal. As I have said in the intro, integrating the data set generation along with the EKF provides a test bed for easy experimenting with many of parameters involved with the GPS tracking problem. I wanted this capability at my finger tips when teaching the class and then leave those who attend or anyone who reads this paper, the opportunity to explore on their own with this fairly detailed simulation framework.
2. *Was this used in a class?* Yes. It is what I am calling the capstone example for an industry short course in Kalman filter with application to GPS. Due to scheduling the class ran just two ago, and I started a second class last week, but will not cover the EKF-GPS example until July 17.
3. *If so how effective was it?* To the first group I feel it was very effective. My intent was to bring the details of what we all take for granted to light, and see there are math details, that are not beyond comprehension. I am at this moment waiting for my co-author to provide input, as this first group is my co-authors work team (Denver), none of whom I had ever met before. He hopefully has gotten feedback by now from those who attended. The second group are people I work with in one of my summer consulting jobs (Colorado Springs), so I know them already and I am anxious to see how things go I July. A quick look-ahead was presented in the first session last week. They seemed interested, as this group is interested in geolocation.
4. *What are some things that you learned along the way after engaging students with it?* Start simple and build up step by step. The EKF-GPS example has a lot of details and a lot of tuning parameters. The EKF-GPS example was preceded by one very simple example and a slightly more complex second example.
5. *You mention that using Jupyter notebooks and the matrix multiply operator were particularly important, why was this?* During lecture I routinely switch from static slides, PowerPoint in this case, to the Jupyter notebook/lab. The textbook equations from this paper, Figure 2, and the EKF extensions (9) and (10) are what is a stake here. In the spirit of keeping it simple, I want the students to see that the core Kalman filter (KF) equations are invariant from example-to-example. In the class this was seen from the first simple KF example down to the EKF-GPS example. The main point is one you understand the textbook equations the top level code changes little (OK, the KF did have to transform to the EKF). These facets are not part of the scipy paper at this point.

Where to next? I like having the math model in the paper to provide context and allow those new to the KF and EKF a chance to remove some of the mystery of applying it to a well know problem, that of User tracking. I can see the possibility of adding a section before the Conclusions and Future Work section, say entitled Educational Impact or Educational Assessment, or ...?....

**Comment by mrocklin** [comment]
So, this is probably beyond my scope as a reviewer, but for a article on education I would expect the analysis above and more to be part of the article itself.  Currently it looks like the article here _is_ the educational knowledge artifact, rather than a research paper about the effectiveness of a new educational technique.  I'm not well versed in the review of educational focused articles though.  My guess is that the appropriate thing for me to do here is to claim ignorance on how best to review a paper like this and stand aside from the review.

**Comment by aweinstein** [comment]
@mrocklin, @mwickert : I've studied the EKF and the GPS system in the past. Although these concepts are describes in several sources, I haven't seen a complete explanation with the associated code as the one presented in this paper. For this reason, in my opinion, the paper is a contribution as it is. 

I only have a question about the source code availability: Is all the code in this repository: https://github.com/chiranthsiddappa/gps_helper ? The paper mentions a Jupyter notebook, but I only see  Python code.  You also mention a `GPS_EKF` class in the paper, but I can't find it in that repository. Can you clarify where is the companion code for the paper.

And out of curiosity, how are you generating figures 3 and 5?

**Comment by mwickert** [comment]
@aweinstein,

Good questions. The repository you find linked in the paper is under development. I have just pushed a develop branch to https://github.com/chiranthsiddappa/gps_helper which includes two notebooks. One contains the EKF-GPS. There are double figures as I was running the notebooks in Jupyter Lab last week, and was doing some experimenting. Figures 3 and 5 were created in OmniGraffle.

**Comment by mwickert** [comment]
@aweinstein 

Also, and early version of the notebook, rendered to HTML, can be found here:
https://mwickert.github.io/scikit-dsp-comm/example_notebooks/gps_Kalman_filter_simulator/Kalman_GPS_practice.html 
We plan to have the newer version of the notebooks as HTML on GH-pages or similar.

**Comment by aweinstein** [comment]
Thanks for the answer @mwickert. I thought there was a tool to automatically create figures like 3 and 5.

**Comment by mwickert** [comment]
@dalippa,

I am thinking I should make the references in this paper also APA, to be consistent with the two papers I have written.

**Comment by mwickert** [comment]
@dalippa 

References now APA style. Maybe more minor changes as co-author and I looks things over again.

**Comment by deniederhut** [comment]
Hi @mwickert ! Is this paper ready for the reviewers to take another pass?

**Comment by mwickert** [comment]
@deniederhut 

Yes, my last push was the APA fix. My co-author has not provided any more input on the paper, but has  updated the GitHub project with Jupyter notebook examples under http://gps-helper.readthedocs.io/en/latest/?badge=latest, which is a reference one of the reviewers commented on.

**Comment by deniederhut** [comment]
Dear @yingweiy, @mrocklin, and @aweinstein  - do you feel this paper is now ready for inclusion in the proceedings?

**Comment by aweinstein** [comment]
@deniederhut I think the paper is ready for inclusion.

**Comment by deniederhut** [comment]
Thanks @aweinstein ! @yingweiy ?

**Comment by yingweiy** [comment]
@deniederhut Yes, I agree that this paper is ready for inclusion. Thanks!

**Review by deniederhut — CHANGES_REQUESTED** [review]
Hi @mwickert ! Paper PRs should not modify the source code in the repo. Can I ask you to remove your committed .gitignore file?

**Comment by mwickert** [comment]
@deniederhut 

21 days ago I did make a change, but then removed the change. The current .gitignore I think matches the original when I cloned the repo. So what shall I do? I'm heading to a gig in 15min and will not be at my computer for 4 hours. I realize you want to close this out.

**Comment by deniederhut** [comment]
Lol the diff has been bamboozled by a missing newline 😂 . I'll allow it, and sorry to have troubled you.

**Review by deniederhut — APPROVED** [review]

**Comment by mwickert** [comment]
@deniederhut 

Thanks for your help.

**Pull request merged**
