### PR TITLE
Paper: Meet Runpandas: How Applied Data Science with Python helped me to run better!  (INCOMPLETE - FIRST DRAFT)

### PR DESCRIPTION
**Pull request by marcelcaraciolo**
*Editor*: @deniederhut

*Reviewers*:

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
@scoobies assign @deniederhut as editor

**Comment by scoobies** [comment]
Assigned! @deniederhut is now the editor

**Comment by deniederhut** [comment]
@marcelcaraciolo we won't be assigning any reviewers to this paper until it is complete.

**Comment by deniederhut** [comment]
Hi @marcelcaraciolo ! How is progress on this paper?

**Comment by deniederhut** [comment]
Hi @marcelcaraciolo ! The paper needs to be finished to be reviewed, and it can't be accepted into the proceedings without review. Will you be able to finish it this weekend?

**Comment by marcelcaraciolo** [comment]
Hello @deniederhut , I am working on it!

**Comment by deniederhut** [comment]
@scoobies mark not ready

**Pull request closed without merging**
