### PR TITLE
Paper: Parkinson's Classification and Feature Extraction from Diffusion Tensor Images 2019

### PR DESCRIPTION
**Pull request by raj-sivakumar-zz**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by aweinstein** [comment]
Hi: I was asked to review this paper. The following are my comments.

In general the paper is very readable and understandable, and the results are interesting.

Typos:

- I think the correct spelling is "Levodopa", not "Levdopa."
- The heading for the reference section is missing.
- Repeated "or" in sentence "We are thus able to use ..."
- Caption of the tables says "labeltable1" and "labeltable2".

Comments:

- It would be great if you can share the code necessary to reproduce the results of the paper.
- In the introduction, when you say "A DTI record is a four-dimensional ...", explain briefly why DTI includes a time series, considering that white matter can be described by a 3D image.
- I find this sentence awkward: "We can generalize this premise to machine learning, when model complexity of models, often result in exponential increases in number of computations." Please try to reword it.
- The paragraph "Similarly to SVD, it is ...", seems disconnected with the text. It is not clear what "it" is. I guess is the Tucker method, but is ambiguous. Perhaps it should not be in a different paragraph.
- It is not clear what object is represented by a tensor in your experiments. I know it the DTI image, but it would be better if you make this explicit.
- Experiment II is not clear to me. In which sense you are dealing with a linear dynamical systems? Please explain.
- Figures and tables are not referenced in the text.
- I suggest to add a Discussion and Conclusion section.

**Comment by alberto-antonietti** [comment]
Hi! I have been assigned to review this paper too.

I read it before looking at @aweinstein, but I run across the same typos, and I agree with all his comments. 

First of all, congratulations on the fascinating work that have important implications for early recognition of PD cases. 

In addition to the issues raised by @aweinstein, I would add the following comments:

- References should be added to the main text when it is appropriate to reference previous works, while they are currently present at the end of the manuscript.
- The acronyms used should be defined when they are first used, even if they are common knowledge for the topic (e.g., MRI, fMRI, CT, SPECT, etc.).
- With the sentence: "DTI has been shown to be a promising biomarker in Parkinsonian symptoms and can provide unique insights into brain network connectivity" did you mean that some indexes/features extracted from DTI can be used as biomarkers? Because I am not sure if DTI itself can be a biomarker.
- Page 2. " a balance between the two analysis", it is not clear to me which are the two analyses that have to be considered among the ones cited above.
- Page 2. Ax=b can be used to represent uniquely a system of **linear** equation; this should be specified.
- Page 2. SVD should be defined before the equation A=USV^T
- Page 2. VT is miswritten after the equation (the T is not put in superscript).
- Page 2. The Tucker decomposition is one of the main methods of the paper, and it should be explained, at least briefly (e.g., making use of Figure 1).
- In the description of both experiments, it is not clear at which point the dimensionality reduction (PCA, LDA, Kernel PCA) is applied.
- Methods, Experiment II. Some details should be added, since the "scale down" operation is not sufficiently described. What do the Authors mean with scaling down the coronal slice?
- It has not specified the division of the dataset between training and testing set, and if the reported accuracies and F-measures are computed for the training or the testing phase. If no separation of the dataset has been performed, the Authors should discuss this limitation.
- Tables 1 and 2: "Kernel PcA" should be "kernel PCA".
- Page 3. "Compare to present results Cole et al." -> "Compared to present results, Cole et al."

I hope that my comments can help you in improving your manuscript!

**Comment by raj-sivakumar-zz** [comment]
Thanks both for your comments! I will make changes per your recommendation and submit an update this week!

**Comment by himito** [comment]
Hi! I have been assigned to review this paper too.

I read today the paper and I run across the same typos.

I agree with all the comments of @aweinstein  and @alberto-antonietti. In addition to the issues raised by them, I would add the following comments:

- [ ] Add a "references" section
- [ ] V^T instead of VT
- [ ] Add the websites of the used python packages.
- [ ] Add fMRI works on Parkinson detention in the Existing Work.
- [ ] I would appreciate if you could use reproducible research methods (e.g., share the code, the datasets, notebooks, etc.) 
- [ ] duplication of "the" word

**Comment by deniederhut** [comment]
Hi! Just checking in. @raj-sivakumar, the approval deadline for this paper is coming up fast. Have you had time to address the issue raised by your reviewers?

**Comment by raj-sivakumar-zz** [comment]
> Hi! Just checking in. @raj-sivakumar, the approval deadline for this paper is coming up fast. Have you had time to address the issue raised by your reviewers?

Hi @deniederhut Thank you for following up. I am addressing the comments and planning to push tomorrow morning.

**Comment by raj-sivakumar-zz** [comment]
If you had any help to offer on adding bibtex citations though I would appreciate it, I keep running into the same errors that stops the pdf build.

**Comment by raj-sivakumar-zz** [comment]
So as I was attempting to submit I noticed that my table captions that match the format of the examples are stopping the pdf build. This wasn't previously an issue, should I be doing something different from the 00_bibderwalt example?

**Comment by deniederhut** [comment]
So the `:bibliography: mybib` tag needs to go in your paper, not in the 00_bibderwalt example.

It also looks like your paper is missing the `:corresponding:` label.

Could I ask you to remove the `00` from your paper's name? So that the file is called `sivakumar.rst`?

As for the table, the rst format requires the table part to be indented.  That said, you only need the rst table or the latex table -- not both.

You're missing a space between the citation display name and the details here in line 421.

Hope this helps!

**Comment by deniederhut** [comment]
Hi @raj-sivakumar ! Have you been able to get the paper to build now?

**Comment by raj-sivakumar-zz** [comment]
@deniederhut Hi sorry! I wasn't able to get the build working unfortunately. I understand if the paper can not be accepted in the current revision.

**Comment by deniederhut** [comment]
Nonsense! I've pushed a PR to your fork that will fix the build issues. Will you be able to respond to the reviewers' comments now?

**Comment by raj-sivakumar-zz** [comment]
Hi @deniederhut Thanks for going above and beyond to help me. I've addressed most the in text issues, I will rebuild my paper and make a few more amendments and repush for editing. Thanks so much!

**Comment by alberto-antonietti** [comment]
Hi @raj-sivakumar, It seems that your paper is not building yet :-(

**Comment by raj-sivakumar-zz** [comment]
@deniederhut @alberto-antonietti I 've made edits and merged the pr so should be building successfully now

**Comment by deniederhut** [comment]
Yup! The paper is building and available at http://procbuild.scipy.org/download/raj-sivakumar-tensor_decomposition_2019

**Comment by himito** [comment]
Hi, here my comments:
  
- [ ] define only way of citing work. For example, what is the cite for Chahine & Stern, Dinov et al. , Adeli et al, etc.
- [ ] **a URL providing the code source of the experiments is not provided, so how could we reproduce your results.** 
- [ ] Introduction section: the dots must be after the citations.
- [ ] Existing Work section: 
  - [ ] develop and full data-processing  -> develop **a** full data-processing 
  - [ ]  It offers a another ->  It offers another
  - [ ] intensiveto -> intensive to
  - [ ]  the the size of the matrix - the size of the matrix
  - [ ]  Singular Value Decomposition is a subtitle, then it's missing bold format otherwise, remove it ?
  - [ ] Reference for Tucker decomposition
- [ ] Methods section:
  - [ ]  url of the TPOT library
  - [ ] url of the tensorly library
  - [ ] Experiment II to Experiment III
- Discussion section:
  - [ ]  fix: with with
  - [ ] it would be nice if you develop more this section.
- Acknowledgements section:
  - [ ] usually we thank to reviewers for their time reading your paper

**Comment by deniederhut** [comment]
Thanks for the review Jaime! @raj-sivakumar will you have time to implement these changes in the next couple of days?

**Comment by raj-sivakumar-zz** [comment]
Thanks @deniederhut thanks @himito , will try to implement these changes by tomorrow.

**Comment by raj-sivakumar-zz** [comment]
@himito could you clarify why you would like 'Experiment II' to be changed to 'Experiment III'? I had organized the paper into two experiments the original Tucker decomposition features extraction and the linear dynamical systems based features extraction. Hence just Experiment I and II.

**Comment by himito** [comment]
@raj-sivakumar you are right. Sorry for that, omit it :)

**Comment by raj-sivakumar-zz** [comment]
Hi @himito @deniederhut  I've made the changes listed, I've cited the packages using the original papers relevant to them instead of the urls

**Comment by raj-sivakumar-zz** [comment]
If you need data to reproduce results, let me know I can try to find a way to give you access a google bucket to download

**Comment by himito** [comment]
I let the decision to @deniederhut  :) there are conferences where an artifact is necessary, I'm no sure with scipy.

**Comment by deniederhut** [comment]
Eh, it's more aspirational than a requirement. We're trying to move toward more reproducible methods sections for papers, but don't really have a timeline set up for that yet. Does everything look okay otherwise?

**Comment by himito** [comment]
Oki doki.

It's only missing to fix the dots before citations. For example, you have '. [rabanser2017]'  instead of '[rabanser2017].' this is repeated several times.

Otherwise It's OK for me 😊. Thank you for considering my comments

**Comment by raj-sivakumar-zz** [comment]
Made the change, re: periods before bracket citation

**Comment by deniederhut** [comment]
@alberto-antonietti and @aweinstein do you now feel this paper is ready for inclusion in the proceedings?

**Comment by aweinstein** [comment]
@deniederhut I think the paper is good to go.

Thanks to the authors and the other reviewers for helping to push the paper forward.

**Comment by alberto-antonietti** [comment]
@deniederhut Green light from me too!

**Comment by deniederhut** [comment]
Rad - thanks so much everyone!

**Comment by deniederhut** [comment]
Hey @raj-sivakumar ! It looks like you've committed changes to the example paper in ` papers/00_bibderwalt`. Could I ask you to revert these changes before we merge your paper?

Also, it looks like some of your citations are missing their DOIs. Could I ask you to add these before we merge your paper?

**Comment by raj-sivakumar-zz** [comment]
@deniederhut have fixed the conflicts in `paper/00_bibderwalt` Also have added DOIs in some cases these were not available so instead opted to provide paper url or arxiv preprint number

**Comment by raj-sivakumar-zz** [comment]
@deniederhut Hi just checking in to make sure I don't have anything else to do to make the paper ready for merge. Hope you're having a lovely Monday!

**Comment by deniederhut** [comment]
Looks good to me! 😄

**Comment by raj-sivakumar-zz** [comment]
@deniederhut 

I notice the paper is marked ready but not in the proceedings. Is it precluded from the proceedings because of a later submission? I understand if so.

**Comment by deniederhut** [comment]
Oh, sorry. No, there's nothing wrong; and yes, your paper will be included in the finalized proceedings. It hasn't been published yet to give everyone time to get their slides/posters submitted. I'll tweet an announcement when it is live, which will hopefully be next week.

**Pull request merged**
