### PR TITLE
Paper: To comment or not? A data-driven look at attitudes toward code comments

### PR DESCRIPTION
**Pull request by vzhz**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by deniederhut** [comment]
Hi there! It looks like you are submitting a markdown file -- our publishing tools require restructured text as input. You can take a look at `papers/00_vanderwalt/` for an example of how these look.

**Comment by deniederhut** [comment]
Hi! This paper needs to build at procbuild.scipy.org before it can be reviewed. Have you had a chance to edit this PR to have your paper in a .rst file?

**Comment by deniederhut** [comment]
We have not assigned reviewers to your paper today because it is not formatted correctly for our publishing process. If this is not corrected soon, we will sadly be unable to include your paper in the proceedings.

**Comment by deniederhut** [comment]
Closing this because we are now past the review deadline.

**Comment by vzhz** [comment]
Thank you! Sorry I wasn't able to get this corrected in time. Next year!

**Pull request closed without merging**
