### PR TITLE
Todd updates

### PR DESCRIPTION
**Pull request by DrTodd13**
Some updates to our section of the paper.

### CODE REVIEW

**Comment by mpacer** [comment]
Is this related to the other PR on accelerating python by @anton-malakhov? 

If it is, could you please merge this into that PR?

**Comment by anton-malakhov** [comment]
yep, sorry, it's hard to prevent such mistakes despite any notices because of the way github suggests to create PR. For some reason, it suggests original repository first instead of simple branch merging into the same repository

**Comment by DrTodd13** [comment]
Sorry. 

Todd 

----- Original Message -----

**Comment by mpacer** [comment]
One way around that is for you to have collaborators fork your repo rather than this one. Also it should be possible to change that under settings.  But the forking from your repo will make it the default thing to be merged to and then you can make whatever branch you want into your repo’s default branch.

**Comment by mpacer** [comment]
@DrTodd13 no worries! Glad this was easy to resolve.

**Pull request closed without merging**
