### PR TITLE
Paper: Accelerating Spectroscopic Data Processing Using Python and GPUs on NERSC Supercomputers

### PR DESCRIPTION
**Pull request by dmargala**
This is the first draft of "Accelerating Spectroscopic Data Processing Using Python and GPUs on NERSC Supercomputers" by Margala, Stephey, Thomas, and Bailey.

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: @deniederhut

*Reviewers*: @laserkelvin

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
@scoobies assign @deniederhut as editor

**Comment by scoobies** [comment]
Assigned! @deniederhut is now the editor

**Comment by deniederhut** [comment]
@scoobies add @laserkelvin to reviewers

**Comment by scoobies** [comment]
@laserkelvin added to the reviewers list!

**Comment by deniederhut** [comment]
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

**Comment by deniederhut** [comment]
Hi @laserkelvin! Friendly reminder that the deadline for initial reviews is next week

**Comment by laserkelvin** [comment]
No problem, it's on the top of my todo list today!

**Comment by laserkelvin** [comment]
Here is my review for @dmargala's submission:

Overall, this is one of the best papers I have reviewed in a long time: the writing is clear, concise, and generally easy to follow by non-experts, and very seamlessly weaves in code blocks that are used effectively to demonstrate abstraction. The problem that this manuscript addresses is quite general, and I believe anyone dealing with Pythonic HPC workflows will gain valuable insight from this work. I only have a few minor suggestions to the paper, as it stands before I can recommend it for this submission to be included in the SciPy proceedings.

## Technical comments

1. To help the reader's understanding and to establish some context, I think it would be beneficial to briefly explain how the data is stored and passed, e.g. compression, storage formats, disk -> CPU -> GPU, etc. in the introduction. There is a section on I/O improvements in the middle of the paper, and more detail about data storage/formats in the introduction would benefit this discussion.
2. Related to 1., I would recommend make a quick figure to illustrate the pipeline at a high level, similar but expanded from Figure 6. It would help the reader with visualizing the steps taken, and I think fits naturally with the rest of the paper given emphasis placed on code profiling.
3. GPU memory is mentioned a few times in passing, but not explicitly talked about in terms of how the data fits into GPU memory exactly although in Figure 2 the screenshot of Nsight indicates 3% of memory is being used. Are there optimizations to be had by using larger image patches?
4. Related to 3. is whether or not [GPUDirect](https://developer.nvidia.com/gpudirect) might be beneficial to this pipeline?
5. In Figure 7, the last scatter point refers to a work-in-progress async algorithm; I was not sure if the authors intended to allude to this in the text at all, as it is not mentioned.
6. In the _GPU Implementation_ section, the authors indicate that in many places a drop-in replacement of NumPy/SciPy API calls was all that was needed, or applying `jit` decorators to functions. It would be up to the authors whether to include this or not, but I would be interested in seeing a "Future work" section that details some ideas for further improving throughput. I would be curious to know to what extent the limiting factors are now algorithmic versus implementation (e.g. batching versus improving `cuPy` performance)
7. In general, the distinction between single and multi GPU performance isn't clear to me; 

## Typographic comments

- Page 2 in the API codeblock example, "convenience" is misspelled.
- Figure 5 has some spell check highlighting
- The title in reference `OUN+17` is not formatted correctly

**Comment by deniederhut** [comment]
@scoobies mark needs more review

**Comment by laserkelvin** [comment]
Hi @deniederhut, is the deadline for the final review still June 24th? I also just wanted to touch base with @dmargala in case changes were made on their end but I missed them somehow!

**Comment by deniederhut** [comment]
Hey @laserkelvin ! We've just bumped the final revisions deadline to 1 July to give everyone a bit more time. @dmargala, how are the paper updates coming along?

**Comment by dmargala** [comment]
@laserkelvin Thank you for your review and comments! @deniederhut I will update the paper with revisions soon. 

1. I can add some text to the intro. The data is stored on disk using the [FITS file format](https://fits.gsfc.nasa.gov/fits_documentation.html). The input data is read by a single MPI rank, transferred to GPU memory, and then broadcast to other MPI ranks using [CUDA-aware MPI](https://mpi4py.readthedocs.io/en/latest/overview.html?highlight=cuda#support-for-cuda-aware-mpi). 

2. Good idea. I will work on creating a high level figure.

3. We have taken care to minimize data movement between CPU-GPU but otherwise we have not performed a detailed analysis of GPU memory usage. In Figure 2, "3% memory" is meant to indicate that memory transfer accounts for 3% of time spent on the GPU. In Figure 3, we see saturation in performance at 2 MPI ranks per GPU (V100) before reaching the GPU memory limit (beyond 4 MPI ranks per GPU). There are hyperparameters to adjust the patch sizes. After major feature implementations, we typically perform a scan of hyperparameter values to identify the optimal settings. For example, after the "batch Cholesky" implementation, the optimal number of wavelength bins per patch changed from 50 to 30.

4. I've seen some work enabling [GPU Direct IO with HDF5](https://www.hdfgroup.org/wp-content/uploads/2020/10/GPU_Direct_IO_with_HDF5-_John_Ravi.pdf) but I'm not aware of anything similar for FITS at this time. For our application, the "Overlapping Computer and IO" implementation mitigates the impact of disk -> CPU -> GPU data transfer (and the reverse).

5. Thanks for catching that! In Fig 7, the "Async IO (WIP)" label is out-of-date. The last scatter point indicates the performance of the "Overlapping Computer and IO" feature milestone. I will update the figure.

6. The performance of the spectral extraction step is now comparable to other steps in the DESI data processing pipeline so the team will need to re-evaluate where to focus optimization efforts. For example, it could be more beneficial at this point to improve workflow scheduling and management. The DESI team may also opt to "spend" some of the performance improvement to perform more compute intensive processing.

7. We only briefly mention single GPU performance. The transition from single GPU to multi GPU should be in the "Maximizing Node Utilization" section, I will try to make it more explicit. Figure 3 shows how performance scaled with number GPUs and number of MPI ranks per GPU.

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.25080/Majora-7ddc1dd1-00a is OK
- 10.1145/2833157.2833162 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1086/651008 is OK
- 10.1016/j.jpdc.2005.03.010 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by deniederhut** [comment]
@dmargala how are the revisions coming? Friendly reminder that the acceptance deadline is this Thursday, and we'll want to make sure that Kelvin has enough time to take a look at your changes before the deadline.

**Comment by deniederhut** [comment]
@scoobies mark pending comment

**Review by laserkelvin — APPROVED** [review]
Looked at the changes made, and the new figures in the PDF; everything looks good to me!

**Review by laserkelvin — APPROVED** [review]

**Comment by dmargala** [comment]
Thank you for reviewing @laserkelvin !

**Comment by laserkelvin** [comment]
@deniederhut I'm happy with the changes that @dmargala made, and it's been a pleasure to read. My final recommendation is :shipit:

**Comment by deniederhut** [comment]
@scoobies mark ready

**Pull request merged**
