### PR TITLE
Poster a phylo geo covid a web interface for reproducible phylogeographic analysis of sars co v 2 variation using neo4j and snakemake

### PR DESCRIPTION
**Pull request by TahiriNadia**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

### CODE REVIEW

**Review by deniederhut — CHANGES_REQUESTED** [review]
It looks like you may have accidentally included your paper inside this PR?

**Comment by deniederhut** [comment]
@scoobies mark not ready

**Comment by TahiriNadia** [comment]
> It looks like you may have accidentally included your paper inside this PR?

@deniederhut Should I delete it? If yes, directly in this PR?

**Comment by deniederhut** [comment]
> Should I delete it?

git is pretty opinionated about stuff like this. I'll pull this branch down and see if I can fix the history. Don't be alarmed if you see me close this PR later -- I'll make sure the poster ends up in the proceedings.

**Comment by deniederhut** [comment]
Closing in favor of https://github.com/scipy-conference/scipy_proceedings/pull/877

**Pull request closed without merging**
