### PR TITLE
Paper: A Pythonic Perspective to Terraforming a Desert

### PR DESCRIPTION
**Pull request by cbcunc**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by deniederhut** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"cbcunc-calloway-test"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp5_g_62w_'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: 00_calloway\n*** Warning: /tmp/tmp5_g_62w_/publisher/../output/00_calloway/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/cbcunc-calloway-test.pdf", "build_status"=>"success", "build_timestamp"=>"30/05 01:25"}, "status"=>"success"}}

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper cbcunc-calloway-test scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by deniederhut** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"cbcunc-calloway-test"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp_wcidzxs'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: 00_calloway\n*** Warning: /tmp/tmp_wcidzxs/publisher/../output/00_calloway/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/cbcunc-calloway-test.pdf", "build_status"=>"success", "build_timestamp"=>"03/06 11:25"}, "status"=>"success"}}

**Comment by cbcunc** [comment]
@scoobies check references

**Comment by scoobies** [comment]
Checking the BibTeX entries failed with the following error: 
```
Couldn't find bibliography entry
```

**Comment by cbcunc** [comment]
Test over.

**Pull request closed without merging**
