### PR TITLE
Paper: Gagnon and Tahiri - New Update

### PR DESCRIPTION
**Pull request by JustGag**
If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:  

Typos + Edit Figures + Details and adjustments in the general paper

### CODE REVIEW

**Comment by rowanc1** [comment]
Hi @JustGag. There have been updates made to your submission that will conflict with these changes.

https://github.com/scipy-conference/scipy_proceedings/pull/1029/commits/8f23695b1ca4d6825e2f332ae2e23f4f4c0e7630#diff-70616f05e0b0078a1b473ebcbce948bbaab6569beab193dbab5350f49b84fc2f

Once that PR is merged, please open a new PR with your requested changes on top of that.

Please note the changes in that diff include things like `Section \autoref{}` --> `\autoref{}` — removing the repeated "Section". `O\tsubscript{2}` --> `O\textsubscript{2}`.

We will be moving onto final steps in publication later this week and finalizing the proceedings for 2024.

**Comment by JustGag** [comment]
Hi @rowanc1, 

I'm new to writing a conference article and am unsure I understood your requests. My supervisor and I have merged the 'scipy-conference:2024' branch into Gagnon_Kebe_Tahiri, but we're not sure we've done what you asked. Could you please tell me what steps I need to take to check that everything is fine?

Also, although I've made changes to my main text, some figures and information in the myst.yml section, they don't appear in the online article (https://proceedings.scipy.org/articles/NVYF1037). So I wanted to know if my updates could be taken into account in the final article, in addition to the updates you've made? Would it be possible for me to see a preview of the final article, like when I check the appearance of my article from Curvenote Preview?

Finally, could you please tell me whether the final stages of the article's publication will be completed tomorrow or this Sunday?

Thank you and have a nice day.

Sincerely,
Justin Gagnon

**Comment by rowanc1** [comment]
Hi @JustGag -- the other PR has now been merged and there are now conflicts. Could you please either update this branch to resolve the conflicts or open a new PR with the changes you request and close this one!

**Comment by rowanc1** [comment]
Hi @JustGag, there are still conflicts in the merge. I am going to close this pull-request so that you can open a new one against the updated 2024 branch. Please ensure that all requested changes are complete by end of day Wednesday this week, further updates won't be possible as we will be doing the final publications and PDF generation.

**Comment by cbcunc** [comment]
@JustGag @TahiriNadia Just checking to see if you intend to follow through with Rowan's request above? We are almost done with the publication of proceedings except for this outstanding issue. We would have like to have been done already.

**Comment by JustGag** [comment]
> Hi @JustGag, there are still conflicts in the merge. I am going to close this pull-request so that you can open a new one against the updated 2024 branch. Please ensure that all requested changes are complete by end of day Wednesday this week, further updates won't be possible as we will be doing the final publications and PDF generation.

@rowanc1 Thank you for your message. We expect to complete the corrections by 7pm tonight. Sorry for the delay. Sincerely,

**Comment by JustGag** [comment]
> @JustGag @TahiriNadia Just checking to see if you intend to follow through with Rowan's request above? We are almost done with the publication of proceedings except for this outstanding issue. We would have like to have been done already.

@cbcunc Thank you for your message. We're really sorry for the delay. We've had a few setbacks and are in the process of completing the final proofreading by 7pm this evening at the latest. After that, we'll put down our pen. Sincerely,

**Pull request closed without merging**
