### PR TITLE
talk: Add pyhf SciPy 2020 talk and information

### PR DESCRIPTION
**Pull request by matthewfeickert**
Add [`pyhf` talk presented at SciPy 2020](https://github.com/matthewfeickert/talk-SciPy-2020) by @matthewfeickert on behalf of the `pyhf` dev team.

Note: This PR is set to a draft for the time being so that responses to any questions received in the Q&A session can be addressed in the "backup" slides after the fact for posterity. Once those are in the PDF I'll move it to being ready for review.

### CODE REVIEW

**Comment by deniederhut** [comment]
Lol we haven't even made the announcement yet. You are too quick for me!

**Comment by deniederhut** [comment]
@matthewfeickert were there still changes you wanted to make before moving this PR from draft to ready?

**Comment by matthewfeickert** [comment]
> @matthewfeickert were there still changes you wanted to make before moving this PR from draft to ready?

@deniederhut Sorry for not following up on this yet. I've gotten much more sidetracked running my conference this week then I was expecting. I wanted to add a few slides at the end that would answer the questions raised in the Q&A, but I probably won't get to that until Friday (2020-07-17) night. I'm not sure what the timeline is for getting the proceedings out, so if I'm holding things up please let me know so I can prioritize getting that done ASAP.

**Comment by deniederhut** [comment]
No worries - I just wanted to check in. As for the timing, the official deadline is the 17th, but typically we see submissions continue for a few days afterward, so we'll hold off on publishing for a bit.

**Comment by matthewfeickert** [comment]
> As for the timing, the official deadline is the 17th, but typically we see submissions continue for a few days afterward, so we'll hold off on publishing for a bit.

Ah sorry I missed that! I don't want you to have to chase after me any more on this so I'll do my best to get these in before the evening of the 17th (tomorrow!).

**Comment by matthewfeickert** [comment]
@deniederhut Thanks for your patience here. This should now be ready for review. :+1:

**Review by deniederhut — APPROVED** [review]

**Comment by matthewfeickert** [comment]
Thanks @deniederhut. :+1:

**Pull request merged**
