### PR TITLE
[Poster] Breaking down the Jupyter notebook monolith: Building reliable notebook-based pipelines with Ploomber

### PR DESCRIPTION
**Pull request by edublancas**
Poster submission.

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
Hey @edublancas -- thanks for submitting a poster to be published with the conference! I'm not sure that a readme with a link is complete enough for archival purposes. How would you feel about creating a release of your poster repository here -> https://github.com/edublancas/scipy-2021 and uploading the zip archive of that release as your submission?

**Comment by edublancas** [comment]
Hi,

The original deadline to submit was last week but I didn't receive any instructions so I figured I'd open a PR here. But then on Friday (after I had submitted this PR), we got new instructions saying we should fill a google form with the poster info (which I just did).

I'm guessing this PR is no longer needed?

**Comment by deniederhut** [comment]
Sorry for the confusion! The submission deadline you are thinking about is for a full paper. The deadline for slides and posters (like this PR) is typically the last day of the conference (so like 2-3 weeks away). Publishing your poster is optional, but it will let you cite it easily in future work.

For us to publish/archive slides and posters, we need the files you are using to run yours.

**Comment by edublancas** [comment]
Ah, thanks for clearing things up! In that case, I'll make a few changes to the poster and update the PR in the upcoming weeks.

**Comment by deniederhut** [comment]
Sounds good to me!

**Pull request closed without merging**
