### PR TITLE
Paper: Multithreaded parallel Python through OpenMP support in Numba.

### PR DESCRIPTION
**Pull request by DrTodd13**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: @mepa

*Reviewers*: @awthomp, @hschovanec-usgs

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
@scoobies assign @mepa as editor

**Comment by scoobies** [comment]
Assigned! @mepa is now the editor

**Comment by deniederhut** [comment]
@scoobies add @awthomp to reviewers

**Comment by scoobies** [comment]
@awthomp added to the reviewers list!

**Comment by deniederhut** [comment]
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

**Comment by deniederhut** [comment]
@scoobies add @hschovanec-usgs to reviewers

**Comment by scoobies** [comment]
@hschovanec-usgs added to the reviewers list!

**Review by awthomp — COMMENTED** [review]
I'll start by saying that I'm familiar with this topic area but by no means an expert in OpenMP. I am, however, experienced in both Python, Numba, and parallel programming concepts. I also plan on adding code level comments over the next few days; this description captures my overall feedback, questions, and potential concerns with the paper.

While I enjoyed this paper, I do think that it misses out on or doesn't adequately describe the strengths and weaknesses of existing Python packages dedicated to both multithreading and multiprocessing, namely -- the `multithreading` and `multiprocessing` libraries. Of course, in the case of `multithreading`, the GIL still locks per CPU, but I do think the audience would benefit from a quick description of these libraries and their falterings. The casual reader may think, "oh gosh, now I need to learn OpenMP?" As stated in your results section, numpy's `matmul` achieves pretty amazing single thread performance on an order 1000 DGEMM, so I think this paper would benefit from a stronger thesis saying why "scaling this numpy implementation to multi-threads/multi-cores" is less valuable than using PyOMP.

On that note, I do think the Introduction is unfairly harsh on Python and borderlines on having some editorials that can probably be removed. For example:
> "They also emerge from a common attitude among Python programmers. Python is for developing new applications"

I find this to be uniquely false and poorly represents the high-performance Python work via Cython, NumPy, Numba, etc. Sure, native Python can be slow for something like dense array processing, but one can argue that doing such is a poor use of Python. While this may be a big-tent opinion, NumPy -- which is fundamentally perf. optimized C/Fortran with some Python bindings -- is considered "Python" at this point. There are a myriad of high performance applications written in Python deployed to production today.

My biggest piece of feedback, however, is I feel like this paper doesn't emphasize the importance of Numba in their narrative. Why do we need Numba? Why Numba + OpenMP instead of Python bindings to OpenMP? Given a JIT implementation, what's the effect of the compile overhead over native OpenMP? What's the performance impact of optimized OpenMP in Numba vs just using OpenMP to enable multiprocessing/multithreading with NumPy? A couple of actionable suggestions here:
- Bring the Numba and the implementation of PyOMP section before the OpenMP design patterns
- Add more description of why Numba was chosen for PyOMP given the alternatives

This paper spends a significant amount of time on the OpenMP parts of the work. While I'm not very familiar with this topic, I do get the feeling that more time could be spent on the "why" rather than the "how", particularly since I don't see any links to looking at the source code for PyOMP. It seems like a non-trivial amount of time was spent on describing key library development concepts, and I question its detailed relevance to this particular community, especially when you note:
> "We need to investigate whether the OpenMP support in the Intel open source release of LLVM is sufficient to support PyOMP"

There's the risk that this work could never see the light of day without a proprietary compiler, so I think the focus on this paper should be more "how to inspire the community to get over the GIL hurdles, and we've found a compelling way to do so."

I'd also like to see more benchmarks and descriptions thereof. What is the C code implementation? What's the performance of NumPy + MPI/OpenMP or Dask? This is the opportunity to hammer home the thesis of the paper, and I think improvements could be made here to really survey the current ecosystem and differentiate why PyOMP is the best solution.

While reading the paper, I also noticed a few stylistic/prose errors and areas of improvement:
- The Abstract and Introduction, in particular, consist of very short sentences that tend to read like a series of amalgamated bullet-points. Flow can be improved by combining ideas and telling more of a story.
- Current thesis is based on a faulty foundation that Python is fundamentally slow and/or Pythonistas don't care about performance. This certainly needs to be toned down as, in my opinion, it's demonstrably untrue.
- Too much focus is given to the mechanics of creating PyOMP without an open-sourced release to the community.
- Inconsistent capitalization and some spelling errors. Just run the paper through a grammar/spelling check, and I think you'll catch most of them. I'll try to make in-line suggestions too
- Denote coding keywords like `with` via italics or `

I think the figures are good, and I like seeing code snippets. In order to broaden the audience, perhaps you should also include block-diagrams showing the SPMD, Loop Level Parallelism, and Tasks and Divide and Conquer design patterns.

Overall, I did enjoy reading this paper and learned a lot. Great job, and I hope my feedback is helpful for improvement!

**Comment by deniederhut** [comment]
@scoobies mark needs more review

**Comment by mepa** [comment]
Hi @hschovanec-usgs, just a friendly reminder that the initial review deadline is this coming Thursday.

**Comment by tgmattso** [comment]
> I'll start by saying that I'm familiar with this topic area but by no means an expert in OpenMP. I am, however, experienced in both Python, Numba, and parallel programming concepts. I also plan on adding code level comments over the next few days; this description captures my overall feedback, questions, and potential concerns with the paper.
> 
> While I enjoyed this paper, I do think that it misses out on or doesn't adequately describe the strengths and weaknesses of existing Python packages dedicated to both multithreading and multiprocessing, namely -- the `multithreading` and `multiprocessing` libraries. Of course, in the case of `multithreading`, the GIL still locks per CPU, but I do think the audience would benefit from a quick description of these libraries and their falterings. The casual reader may think, "oh gosh, now I need to learn OpenMP?" As stated in your results section, numpy's `matmul` achieves pretty amazing single thread performance on an order 1000 DGEMM, so I think this paper would benefit from a stronger thesis saying why "scaling this numpy implementation to multi-threads/multi-cores" is less valuable than using PyOMP.

Thank you for taking the time to so carefully respond to the contents of our paper.   We really struggled with fitting what we needed to say into the length restrictions the SciPy people set (8 pages).  While we agree that discussion multithreading and multiprocessing in general would be useful, it would take a great deal of space.  Likewise with a discussion of DASK, MPI4Py, and other packages for on-CPU parallelism; this discussion is desperately needed, but that (as we point out later in our discussion section) that is a topic that deserves a separate and much longer paper (which we are working on).

I want to emphasize (and maybe I need to make this more clear in the text) that this not about DGEMM.  You'd always use a library written by professional performance engineers to run DGEMM (which numpy does internally).   This is about a common pattern (triply nested loops) that programmers use all the time that we can easily test and time.  We'll go back and make this change in the paper.


> 
> On that note, I do think the Introduction is unfairly harsh on Python and borderlines on having some editorials that can probably be removed. For example:
> 
> > "They also emerge from a common attitude among Python programmers. Python is for developing new applications"
> 
> I find this to be uniquely false and poorly represents the high-performance Python work via Cython, NumPy, Numba, etc. Sure, native Python can be slow for something like dense array processing, but one can argue that doing such is a poor use of Python. While this may be a big-tent opinion, NumPy -- which is fundamentally perf. optimized C/Fortran with some Python bindings -- is considered "Python" at this point. There are a myriad of high performance applications written in Python deployed to production today.
> 

OK.  My coauthor is not very happy about this either.  However, among the HPC community, that statement is the common attitude.  I have heard it quoted at me more times than I can count.  I think the problem is that I paint too broad of a stroke when I say "Python Programmers".   I should say "Python Programmers in the HPC community (such as those you find at DOE supercomputing centers)".   With that modifier, this statement is indeed the case.

I also want to point out that as a writing device, I want to hook readers.  I want to get people fired up a bit so they might keep reading.  We will go back and see about modifying the paper so our overall point comes through but we don't piss people off.

> My biggest piece of feedback, however, is I feel like this paper doesn't emphasize the importance of Numba in their narrative. Why do we need Numba? Why Numba + OpenMP instead of Python bindings to OpenMP? 

We need numba or some technology that gets us away from the GIL.  A python binding to Python without a JIT into a lower level IR would not work (its that GIL again).   OpenMP is not a library.  It is implemented in a compiler front end with directives that explicitly control multiple threads.  It might be possible to directly bind Python to the low level OpenMP runtime but since OpenMP is fundamentally a compiler technology, to do so you'd have to reinvent much of numba anyway.

>Given a JIT implementation, what's the effect of the compile overhead over native OpenMP? 

We do mention this.  It adds a second or two the first time you encounter a function.

> What's the performance impact of optimized OpenMP in Numba vs just using OpenMP to enable multiprocessing/multithreading with NumPy? 

I understand what you mean, but embedding multithreading in NumPy kind of misses the point.  OpenMP is about users adding threads to their own algorithms.  Yes, we need multithreading inside Numpy.  That is a great thing to do. But that doesn't help someone who has their own algorithm they want to multithread.  Also parallelizing inside numpy focusses on one operation at a time.  That can be bad for the cache and creates excess overhead.


> A couple of actionable suggestions here:
> 
> * Bring the Numba and the implementation of PyOMP section before the OpenMP design patterns
> * Add more description of why Numba was chosen for PyOMP given the alternatives
> 

Thank you for the suggestion.   We respectfully disagree as a matter of style.  It would be hard to explain or even motivate a long discussion about how pyomp is implemented using numba without first explaining pyOMP.  And we present the patterns holistically as part of the description of OpenMP (which based on 20+ years of teaching OpenMP is the right way to do it).  

As for alternatives to numba, we'll try to clarify the point in the paper. The bottom line ... for what we are doing, there is no alternative.  Remember, we are connecting to LLVM and that is precisely one of the key functionalities one gets from numba.

> This paper spends a significant amount of time on the OpenMP parts of the work. While I'm not very familiar with this topic, I do get the feeling that more time could be spent on the "why" rather than the "how", particularly since I don't see any links to looking at the source code for PyOMP. 

It's not clear to us what you are trying to say here.   I guess you want us to say more about why someone would want to use multithreading for performance?    I guess we work in parallel computing so much that writing parallel code for performance is self-evident.   We'll go back into the introduction and make sure the reason for using multithreading is clear.



>  It seems like a non-trivial amount of time was spent on describing key library development concepts, and I question its detailed relevance to this particular community, especially when you note:
> 
> > "We need to investigate whether the OpenMP support in the Intel open source release of LLVM is sufficient to support PyOMP"
> 
> There's the risk that this work could never see the light of day without a proprietary compiler, so I think the focus on this paper should be more "how to inspire the community to get over the GIL hurdles, and we've found a compelling way to do so."

We are aware of and very much concerned that if PyOMP is tied to a proprietary compiler, it will not see the level of usage it deserves.  We are working hard to address this problem which is why we mentioned the need to investigate moving this into the open source LLVM release.   We have already done this investigation and we know the Open source LLVM is not sufficient.  We hope that this paper spurs enough interest in the user community so we can get the Open source LLVM updated to support what we need.  It's kind of a chicken and the egg problem ... if people don't know this is possible, they won't push for the needed updates into LLVM.  We are hoping to drive that conversation.

> 
> I'd also like to see more benchmarks and descriptions thereof. What is the C code implementation? What's the performance of NumPy + MPI/OpenMP or Dask? This is the opportunity to hammer home the thesis of the paper, and I think improvements could be made here to really survey the current ecosystem and differentiate why PyOMP is the best solution.

Note that OpenMP is the number one multithreading API used in HPC today.  To and HPC person, OpenMP is the approach they already know.  Showing we can do this in Python is a VERY big deal.  So we believe the paper stands as an introduction to OpenMP in Python.  At the same time we agree that comparisons to DASK and MPI4Py and Ray and the many other systems out there is important.  But that demands its own paper.  We can't do that comparison without a long paper.  We tried to make that point in the discussion section of the paper. We'll go back and make sure its clear enough.


> 
> While reading the paper, I also noticed a few stylistic/prose errors and areas of improvement:
> 
> * The Abstract and Introduction, in particular, consist of very short sentences that tend to read like a series of amalgamated bullet-points. Flow can be improved by combining ideas and telling more of a story.

Thank you for the feedback.   I'll take a look and see what we can do.

> * Current thesis is based on a faulty foundation that Python is fundamentally slow and/or Pythonistas don't care about performance. This certainly needs to be toned down as, in my opinion, it's demonstrably untrue.

Once again ... to the HPC community used to the performance we get from C/C++/Fortran, python is fundamentally slow.   We reference a paper published in Science recently (there's plenty of room at the top) that goes into this in detail.  Python is slow and we (the community who cares about performance) need to do a lot of work to fix this.  Fixing this problem is a MAJOR thrust of our research group.


> * Too much focus is given to the mechanics of creating PyOMP without an open-sourced release to the community.

Yes, this is a serious problem.  We have to fix this.  Our changes to Numba will be open sourced. But without the LLVM release that Intel uses internally, this will only work for people who have a license for the intel compiler.  We are painfully aware of this and are working hard to fix this.  

> * Inconsistent capitalization and some spelling errors. Just run the paper through a grammar/spelling check, and I think you'll catch most of them. I'll try to make in-line suggestions too
> * Denote coding keywords like `with` via italics or `
> 

I will look into this.  We wrote the paper in LaTex and then converted to the markup language SciPy insisted we use.  This was a MAJOR problem and resulted in dropping italics and other font changes.   I'll see what i can do.




> I think the figures are good, and I like seeing code snippets. In order to broaden the audience, perhaps you should also include block-diagrams showing the SPMD, Loop Level Parallelism, and Tasks and Divide and Conquer design patterns.
> 
> Overall, I did enjoy reading this paper and learned a lot. Great job, and I hope my feedback is helpful for improvement!

I would love to add those block diagrams.  They do help and will be in the slides that will go with the paper.  I don't think we have room to add them, but I will see what we can do,.

Once again, thank you very much for your feedback and your detailed comments.   This really helps.

**Comment by hschovanec-usgs** [comment]
A note before I jump into my comments: I have linked specific references, quotes, etc. to the lines in the diff. After you click on the link, you will need to select "Load Diff" in order to see the highlighted section.

This paper is well written. The results displayed in the paper are very interesting and promising for providing performance optimization to future Python projects. While I understand that there are limitations on open source libraries that claim to provide parallelization and threading. I think that it is important to repeatedly emphasize the specific limitations. 

My overarching comment is that this paper needs to do a better job convincing the reader that PyOMP is a superior alternative to NumPy, Numba alone, or writing code in C and Cython. While your Results section points to this conclusion, I have pointed out some specific sections that I think might need more attention.
- It would be good to discuss that ["The GlobalInterpreterLock (GIL) prevents multiple threads from simultaneously accessing Python objects."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R26) outside of the Abstract. Perhaps in the Introduction to emphasize the motivation for PyOMP.
- There are statements like this that while they lead into more specific details, do not provide any information: ["The key result of this paper is that PyOMP works."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R363-R364)
- In the results section you compare PyOMP with three other cases and provide the test code in the figure. However, when comparing results in [table 3](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R435-R439), only the comparison of PyOMP and C with OpenMP is shown. It would have been more impactful to compare all three results visually rather than comparing two in a table and comparing the others in the text.
- The statement ["We need to work out the details for how we will distribute this code."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R479) will likely be concerning to those readers that primarily rely on open source compilers. It would be beneficial to clearly state your goal. Is the primary goal to provide an open-source release? If you have already done tests with the open-source LLVM that indicate whether this goal is achievable, this should be clearly stated.

On a smaller note, the generalization of programmers' attitudes may not be appreciated by your readers. While I do not necessarily disagree that ["The performance issues in Python come from a lack of focus on performance."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R52), there are many in the Python community that write open source software and may not have the resources for performance-driven development. Rather than placing the blame on the Python community, it would be beneficial to highlight how PyOMP could make performance-driven development a more attainable goal.

Below I have listed possible typos, inconsistent capitalization, etc. There may be others that I have missed.
- "Loop Level Parallelism pattern" is inconsistently capitalized in places.
- "Numba" is inconsistently capitalized in places.
- "NumPy" is inconsistently capitalized in places.
- ["It is good form in OpenMP programming to make the status of variables explicit in an OpenMP construct which we do with the shared and private clauses in lines~14 and 15 in figure1."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R160-R162)
- ["This is shown in figure2."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R206)
- ["Finally, certain OpenMP directives such as single}and critical, require the use of memory fences with acquire, release, or acquire/release memory orders."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R356)
- ["As we saw in firgre 2, we achieved reasonable speedups for the three key patterns that dominate OpenMP programming where by the word "reasonable" we mean "achieving performance similar to that from C". The pi programs, however, are "toy programs"."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R363-R366)
- ["If we use NumPy and call the matrix multiplication function provided with NumPy (line 22 in figure 7, the order 1000 DGEMM ran at 11.29 +/- 0.58 GFLOPS with one thread (using the matmul() function from numpy."](https://github.com/scipy-conference/scipy_proceedings/pull/623/files#diff-863cfd358efe732247aecf8989216fabfbf46d28eabe8a28acee5c1c04ff5372R445-R448)

Below are some general stylistic comments:
- Your figures that show code are explaned thoroughly in the text. However, it might be nice to add in-line comments so that the reader doesn't have to jump back and forth between the image and the text.
- It might be beneficial to add simple diagrams/flowcharts for the proposed patterns.


Again, I would like to state that I think that this paper is very interesting and provides promising results. I look forward to hearing more about PyOMP in the future!

**Comment by deniederhut** [comment]
@scoobies mark pending comment

**Comment by deniederhut** [comment]
@DrTodd13 to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st

**Comment by deniederhut** [comment]
Hi @DrTodd13 ! Have you had a chance to respond to the reviewers' comments?

**Comment by tgmattso** [comment]
> Hi @DrTodd13 ! Have you had a chance to respond to the reviewers' comments?

I am the other author on the paper.  Todd took a vacation so the reply fell to my shoulders.

I will produce a draft of the paper that replies to the comments from the reviewer.  I just haven't had time to do so yet.

**Comment by tgmattso** [comment]
Thank you so much for the careful and thoughtful review.  I am working on a new draft of the paper that will incorporate our responses to most of your comments.    I do not have time to respond in detail to your review and work on the next draft of the paper.  But you will see in the final paper how helpful your comments were in making this a better paper.

It is interesting ... both you and the other reviewer asked for images showing the patterns we mention.  I have those images, but they would push us over the page limit.  With online publication, it would sure be nice if they relaxed the page-count limit.   

Also ...  concerning my generalization of programmers attitude towards performance.  That comment bothered my co-author, but I stubbornly stuck to it since that is truly what traditional HPC programmers like me (Fortran and later C are my most commonly used languages) think of Python.  Then the first reviewer complained and now you.   I guess I need to stop being so stubborn and listen to what people are telling me. :)        I will fix it.

--Tim

--Tim

**Comment by DrTodd13** [comment]
@hschovanec-usgs and @awthomp Please have a look at Tim's comments and the updates he made to the paper and let me know if you are happy with how we have resolved things.

**Comment by awthomp** [comment]
@DrTodd13 -- I am happy with the revisions both you and your co-author made to the paper. One of my biggest pieces of feedback was to back off the "Python is slow!" thesis, and I think you've done a good job clarifying that folks in the high performance python community achieve speedup via linking to high-performance libraries written in some statically typed language. I think this does a good job balancing between getting your point across for why PyOMP is relevant and interesting but also doesn't turn off some of your readers with a blanket statement.

I also like the new addition surrounding performance gains via NumPy and its relative strenghts/weaknesses. I think it better positions your work, here.

I know I made a litany of other suggestions, but the framing was really my biggest critique, and I think that's been fixed. Other modifications potentially fall out of scope/page limit of this submission.

Great job, ya'll, and I'm happy I could help review!

**Comment by mepa** [comment]
Hi @hschovanec-usgs, do you feel the authors have addressed your comments and that the paper is now ready for inclusion in the proceedings?

**Comment by mepa** [comment]
@scoobies mark ready

**Comment by hschovanec-usgs** [comment]
The changes made to the paper address the comments I have provided. The added context about the objective of the paper and the limitations created by GIL is very beneficial to this paper.

**Pull request merged**
