### PR TITLE
Paper: Analyzing YouTube using Python and Machine Learning

### PR DESCRIPTION
**Pull request by jsingh811**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: @cbcunc

*Reviewers*: @pgadige, @junipertcy

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
@scoobies assign @cbcunc as editor

**Comment by scoobies** [comment]
Assigned! @cbcunc is now the editor

**Comment by cbcunc** [comment]
Editor’s initial quickie look-over:

- [x] Make sure the paper builds on procbuild
- [x] Make sure that the sections are filled in
- [x] Make sure 8 pages or less exclusive of references

**Comment by deniederhut** [comment]
@scoobies add @pgadige to reviewers

**Comment by scoobies** [comment]
@pgadige added to the reviewers list!

**Comment by deniederhut** [comment]
@scoobies add @junipertcy to reviewers

**Comment by scoobies** [comment]
@junipertcy added to the reviewers list!

**Comment by deniederhut** [comment]
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

**Comment by jsingh811** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper jsingh811-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by jsingh811** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper jsingh811-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by junipertcy** [comment]
Hi @jsingh811, thank you for the instruction for where to download [the PDF manuscript](https://procbuild.scipy.org/download/jsingh811-2021). I aim to post my initial review in a few days.

**Comment by junipertcy** [comment]
Hello @jsingh811! Here is my synopsis for your manuscript based on [the suggested review criteria](https://github.com/scipy-conference/scipy_proceedings/blob/2021/review_criteria.md) for SciPy Proceedings. The main contribution of the paper is the [`pyYouTubeAnalysis`](https://github.com/jsingh811/pyYouTubeAnalysis) library, which is used to render most of the figures (Figs. 5–13) and supports the arguments in Section "Trend Analysis Case Study". It is a wrapper to interact with YouTube's Data API, which offers a convenient layer to the users. 

Currently, I vote against acceptance because the manuscript does not offer enough content that suggest it either advances (1) the state of a scientific domain (i.e., natural language process or named-entity recognition), or (2) the practice of scientific computing itself. Specifically, the scientific novelty is only weakly emphasized in the paper (on the abstract and on page 2) and the analyses are based on number statistics (e.g., Figs. 5–11), which, to me, does not offer a rigorous argument.

In addition to **Novelty and Impact**, I only find minor problems on **Written Quality** and no problem on **Verifiability** and **Technical Content**.

**Comment by junipertcy** [comment]
My minor comments follow.
1. Many places in the manuscript: If 3 similar items are mentioned altogether, say A–B–C, the suggested way is to write it as `A, B, and C`, with a comma between `B` and `and`.
2. On the abstract: "NLP" is mentioned earlier than "Natural Language Processing".
3. Subsection "Keyphrase extraction": Suggest to write out explicitly the tools mentioned in the article, and then cite the article. 
4. Subsection "Others": The third item "Mass analysis" is not a use case. To me, it is a bonus that computers offer to expedite our understanding.
5. Subsection "Data Cleaning Techniques": Suggest unify / re-structure the two code blocks a bit. 
6. Section "Trend Analysis Case Study": Figure 2 should be mentioned prior to Figure 3.
7. Figure 12 and 13: What techniques (that are mentioned in the manuscript) are used to generate those plots? Currently, I see only named-entity recognition being used. Also, it might be more informative to use histograms for these plots.
8. "language" vs "language usage": "language" is confounded with "language usage" at many places. Find&Replace.

**Comment by junipertcy** [comment]
Dear @jsingh811, good work! The pyYouTubeAnalysis library looks very useful. I hope my suggestions help.

Dear @deniederhut, my initial assessment is completed. We may need additional reviewers to provide complementary ideas.

**Comment by deniederhut** [comment]
Thanks!

On June 14, 2021, ivan-marroquin ***@***.***> wrote:
> Dear @jsingh811 <https://github.com/jsingh811>, good work! The
> pyYouTubeAnalysis library looks very useful. I hope my suggestions
> help.
>
> Dear @deniederhut <https://github.com/deniederhut>, my initial
> assessment is complete. We may need additional reviewers to provide
> complementary ideas.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scipy-
conference/scipy_proceedings/pull/630#issuecomment-861295985>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABUM3LFUXTSWK6RLVYWQJRLTS4FBFANCNFSM45VMO4SA>.

**Comment by jsingh811** [comment]
Thank you for the detailed review and feedback!
I have made edits to the paper to reflect all the suggestions. I have further added more content, specifically around the **Trend Analysis** and **Data Cleaning Techniques** sections,  in order to strengthen the case for _Novelty and Impact_. This was done in the effort to better highlight the impact of developed techniques to improve standard NLP method outputs. Furthermore, in addition to helping fetch data from YouTube, pyYouTubeAnalysis includes NLP methods and developed techniques that help better process data from social media based on observations of quality, which I have tried to better describe in the paper with the new edits. Thank you for observing the gaps. I hope these changes improve the state of this submission. Once again, I truly appreciate all the efforts and feedback.

**Comment by jsingh811** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper jsingh811-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by jsingh811** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper jsingh811-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by deniederhut** [comment]
@scoobies mark needs more review

**Comment by deniederhut** [comment]
@jsingh811 to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st.

@junipertcy has Jyotika's changes addressed the items in your review?

**Comment by junipertcy** [comment]
Hi @deniederhut --- Yes, most concerns have been properly addressed.

**Comment by cbcunc** [comment]
@scoobies check references

**Comment by scoobies** [comment]
Checking the BibTeX entries failed with the following error: 
```
Couldn't find bibliography entry
```

**Comment by jsingh811** [comment]
Hi @cbcunc, 
Would you prefer if I moved the references to a separate bib file?

**Comment by deniederhut** [comment]
That's okay -- you don't have that many references, so I took a look with my human eyes. Would you mind updating the DOIs in the reference section to follow the display guidelines here https://www.crossref.org/display-guidelines/ ? Thanks!

**Comment by deniederhut** [comment]
@scoobies mark pending comment

**Comment by jsingh811** [comment]
Thanks @deniederhut !
Can I add an ORCID ID somewhere?

**Comment by jsingh811** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper jsingh811-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by jsingh811** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18653/v1/K18-1022 is OK
- 10.5281/zenodo.1212303 is OK
- 10.5281/ZENODO.5044556 is OK
- 10.1186/1751-0473-6-7 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by deniederhut** [comment]
Yup! You can add an orcid tag under your author name in the paper header like this:


```rst
:author: Gaius Caesar
:email: jj@rome.it
:institution: Senate House, S.P.Q.R.
:institution: Egyptian Embassy, S.P.Q.R.
:orcid: 0101-0101-0101-0103
:corresponding:
```

**Comment by jsingh811** [comment]
Thank you @deniederhut !
I have double-checked the references and added the orcid. 
One final question: would it be ok to slightly alter the title of the paper, so that it matches with the poster?

**Comment by deniederhut** [comment]
You're welcome!

> would it be ok to slightly alter the title of the paper

Yeah totally! The title can be whatever you like.

**Comment by jsingh811** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper jsingh811-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by jsingh811** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18653/v1/K18-1022 is OK
- 10.5281/zenodo.1212303 is OK
- 10.5281/ZENODO.5044556 is OK
- 10.1186/1751-0473-6-7 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jsingh811** [comment]
Thank you, @deniederhut! I have finished making all the changes and have double checked the references.

**Comment by deniederhut** [comment]
Awesome! Unless @cbcunc has any objections, I think we're good to go here

**Comment by deniederhut** [comment]
@scoobies mark ready

**Comment by deniederhut** [comment]
😦  looks like github is having an outage

**Pull request merged**
