### PR TITLE
Paper: Dynamic Social Network Modeling of Diffuse Subcellular Morphologies

### PR DESCRIPTION
**Pull request by Adurden**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by renato-umeton** [comment]
The authors present a very interesting paper that leverages social network analysis tools to gather insights into mitocondria and actins activities in epithelial cells.

The paper is overall well structured and results are nicely presented.

A few comments would probably make the paper easier to digest for a broader community:

1. The pipeline is detailed well in the text, and an image would help -- something that looks like the Cell graphical abstracts would help a lot the reader following the procedures
2. The paper would benefit from a spell check and a proof-reading pass by a native speaker. Some sentences like "This element of the our graph analogue’s structure will be more cemented as we analyze the networks created." or "the normpdf includes an implementation of a normal distrobution function due to discrepencies with the scipy.stats.norm implementation" can be improved for syntax and clarity.
3. The image resolution is suboptimal and could be improved -- some text in the images is impossible to read.

In general, the direction of exploring Spectral Clustering on the Laplacian seems a very promising direction and I look forward to seeing developments on this point.

**Comment by cmahapatra97** [comment]
In this paper, the authors develop a computational model for the subcellular patterns of mitochondria in epithelial cells. First, they segment each cell from the initial input video, then, they apply social network engineering to quantify the spectrum of mitochondrial morphology.
The paper is interesting and fairly written. The manuscript has described a technically sound piece of scientific research.
 
Few queries:
1.	Authors should address the advantages of this method by comparing with other methods for quantifying protein behaviors. 
2.	Manuscript needs a proof-reading pass. Some type errors are there in the text. For example, normal distrobution function due to discrepencies in page 4 (2nd paragraph in right column)
3.	Authors should maintain a uniform captain style for all figures. Fig. 1 captain is misleading due to missing bracket. For example, LLO induced mitochondrial fragmentation Center).
4.	Authors should add more lines to illustrate Fig 6 in the MS.

**Comment by Adurden** [comment]
@Dana-Farber I want to clarify, when you suggest an image for the pipline do you mean one to show an abstract representation of the entire process, or are you refering to a specific portion of the process?

**Comment by renato-umeton** [comment]
I mean the pipeline. See some examples here
https://www.google.com/search?q=cell+graphical+abstract+pipeline&client=firefox-b&prmd=ivns&source=lnms&tbm=isch&sa=X

**Comment by Adurden** [comment]
@cmahapatra97  what do you mean by "Authors should add more lines to illustrate Fig 6 in the MS"? Is it a matter of the last image following the paper.  As is, I can't seem to move the figure to be in the body, regardless of how I define it in the .rst file, in the build it always follows the paper. I think when content is added, like an image representing the overall pipeline or your recommended address of advantages of the proposed method, it may shift the body down to envelop the image. Other than that, I am unsure how the image can be better integrated into the body.

**Comment by renato-umeton** [comment]
This is great! Inside each one of the 5 figures can you please add a text
(yes text in the image) that summarizes in 3-5 words what the steps
entails? Eg, 1. mitochondria identification, 2. Cell clustering and contour
definition,..., 5. Social network analysis...

**Comment by deniederhut** [comment]
Hi team! It looks like the build for this paper is currently failing on the server. My best guess is that someone accidentally changed one of the image names. Could you confirm whether it still builds locally?

**Comment by Adurden** [comment]
It builds locally for me. I made a change to the pipeline.PNG file in the most recent commit but it hasn't broken my local build.

**Comment by deniederhut** [comment]
Hm this builds locally for me too... @mpacer can you see what is happening in the logs server-side?

**Comment by mpacer** [comment]
It’s likely a capitalisation issue. Your capitalisation in the paper for the pipeline.png does not match the file name because you capitalised PNG. Please make the capitalisation consistent and this should begin to work again.

**Comment by Adurden** [comment]
I changed the capitalization. Looks like it's building now on the server. Thank you @mpacer 
Seems like the remaining revisions are to:
1. Overall proofread for grammar, syntax, and spelling
2. Make image captions more consistent
3. Address the advantages of this approach

**Comment by Adurden** [comment]
I believe we are done with edits. Is there anything else that needs to be changed from it's current status for the paper to be considered ready?

**Comment by renato-umeton** [comment]
Was the entire content proof read after my initial review? Proofreading
would be the last item on my list...

**Comment by Adurden** [comment]
@Dana-Farber the very last set of commits today were a full proof read and edit by the corresponding author.

**Comment by dalippa** [comment]
@Dana-Farber @cmahapatra97 Please tag @proceedings when the paper is ready to be accepted.

**Comment by renato-umeton** [comment]
@proceedings

**Comment by dalippa** [comment]
@Dana-Farber is the paper ready?

**Comment by renato-umeton** [comment]
Looks ready to me: I don't have other feedback at this moment for the
authors

On Jul 2, 2018 8:37 PM, "David Lippa" <notifications@github.com> wrote:

@Dana-Farber <https://github.com/Dana-Farber> is the paper ready?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scipy-conference/scipy_proceedings/pull/396#issuecomment-401977923>,
or mute the thread

**Comment by cmahapatra97** [comment]
Thank you very much for considering all queries.  No additional points from me. I hope to see the extended version of this work as a journal paper with additional results.

**Comment by dalippa** [comment]
@Dana-Farber @cmahapatra97 please let us know your name and if you will be attending the conference so you can get a reviewer sticker.

**Pull request merged**
