### PR TITLE
Paper: "Comparison of machine learning methods applied to birdsong element classification". David Nicholson.

### PR DESCRIPTION
**Pull request by NickleDave**

### CODE REVIEW

**Comment by suchow** [comment]
Here's some advice from Proselint (http://github.com/amperser/Proselint), a Python-based linter for prose, with two false alarms removed:

```
99:417: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).
57:470: garner.phrasal_adjectives.ly No hyphen is necessary in phrasal adjectives with an adverb ending in -ly.
78:1040: uncomparables.misc Comparison of an uncomparable: 'less ideal ' is not comparable.
169:683: weasel_words.very Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be.
```

**Comment by sbenthall** [comment]
Hello, I'll be reviewing this paper over the next couple days.

First impressions: It's a very interesting topic and a cool case for comparing machine learning methods. I gather that there are a number of results, and that the process you went through is instructive. But the paper is written in an informal style that makes it difficult for me to follow the line of argument.

Please consider:

- Using much less of the first person, "I". If you can rewrite it without using the first person at all, that would be ideal.
- You have written the paper as a narrative about your process of discovery. Your logic of discovery need not be your logic of presentation. Take the most significant things you learned from your investigation and put them front and center to your argument. They are your research contribution, and you can structure your paper to be a presentation of those research contributions and the empirical support for them.

There is a lot of good scientific content in this paper. It would be much easier to understand it if it were organized as a scientific argument.

**Comment by sbenthall** [comment]
Ok, giving this a second look this morning.

I want to try to articulate the questions I have about your scientific content that I'm having trouble figuring out from reading the paper:

What does the data you are using look like, exactly? I think what's going on is that all songs are Bengalese Finch songs. And then individual syllables are labeled? So you are looking for which algorithm correctly classifies the most syllables based on the least number of songs used in the training.
  
This is not as far as I know a standard way of evaluating the effectiveness of machine learning algorithms. One reason for this is that the order in which you feed data to the learning algorithm is going to effect its effectiveness. So in order to evaluate the effectiveness of algorithms in this sort of study, you need to randomize the inputs to the algorithms.

There's also the question of whether you are testing the algorithm with the same data you trained it on. If you are, the algorithm you choose might be very good at [overfitting](https://en.wikipedia.org/wiki/Overfitting) the data, but not be the best classified overall. This is what you've expect from an algorithm with more [variance](http://users.sussex.ac.uk/~christ/crs/ml/lec03a.html), which you're going to get when you use a kernel.

So what I think would improve this paper is if you did a standard [cross-validation](http://users.sussex.ac.uk/~christ/crs/ml/lec03a.html) method to test these algorithm's effectiveness. This means splitting your data at random into a training set and a test set, training the algorithm on the training set, and testing on the test set.

**Comment by NickleDave** [comment]
Hi Sebastian,

Thank you for taking the time to review the paper. Your comments are
helpful.

I think I can address the questions in your last e-mail by rewriting the
methods section. My experiments do use cross-validation. It's obvious to me
looking at the methods again that I did not make this clear.

I did randomize the inputs by drawing samples at random from the training
set for each of the "replicates" (currently n=5 in all the experiments
except Figs.10 and 11). I did not test the algorithm on the same data I
trained with. The testing sets for each bird consists of an additional 1-3
days of song that was not used in the training set.

So each data point in the graph is a replicate where I grabbed *k* random
songs, where *k* is the value on the x axis, trained a classifier, and then
tested it on the testing set that was constant for all experiments. There
are 5 data points at each value on the x axis because there were 5
replicates with *k* random songs.

I will re-write the methods to make the above clear.

With regards to your first email, I take your points about the
presentation. The use of first person and the logic of presentation is a
conscious choice in response to my frustration with reading other papers,
and an attempt to make it more understandable to songbird researchers that
might not be as familiar with the ins-and-outs of machine learning.

Your comments made me realize that presenting a ton of experiments in that
way is asking a lot of the reader. My general plan is to condense the main
comparison of the three algorithms (linear SVM, SVM-RBF, and k-NN) into one
graph, then present the finding about the effect of intro syllables on
linear SVM in another graph, and lastly present the results comparing the
three algorithms with a common feature set. I will also remove first person
where possible.

Please let me know if you feel this will address your comments.

Thank you again for finding time to review the paper.
David

On Wed, Jun 29, 2016 at 10:32 AM, Sebastian Benthall <
notifications@github.com> wrote:

> Ok, giving this a second look this morning.
>
> I want to try to articulate the questions I have about your scientific
> content that I'm having trouble figuring out from reading the paper:
>
> What does the data you are using look like, exactly? I think what's going
> on is that all songs are Bengalese Finch songs. And then individual
> syllables are labeled? So you are looking for which algorithm correctly
> classifies the most syllables based on the least number of songs used in
> the training.
>
> This is not as far as I know a standard way of evaluating the
> effectiveness of machine learning algorithms. One reason for this is that
> the order in which you feed data to the learning algorithm is going to
> effect its effectiveness. So in order to evaluate the effectiveness of
> algorithms in this sort of study, you need to randomize the inputs to the
> algorithms.
>
> There's also the question of whether you are testing the algorithm with
> the same data you trained it on. If you are, the algorithm you choose might
> be very good at overfitting <https://en.wikipedia.org/wiki/Overfitting>
> the data, but not be the best classified overall. This is what you've
> expect from an algorithm with more variance
> <http://users.sussex.ac.uk/%7Echrist/crs/ml/lec03a.html>, which you're
> going to get when you use a kernel.
>
> So what I think would improve this paper is if you did a standard
> cross-validation <http://users.sussex.ac.uk/%7Echrist/crs/ml/lec03a.html>
> method to test these algorithm's effectiveness. This means splitting your
> data at random into a training set and a test set, training the algorithm
> on the training set, and testing on the test set.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/208#issuecomment-229374500>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALYZiukaAbSc_s3UG-5motwE4mz0GVBnks5qQoH4gaJpZM4IqNIV>
> .
>



-- 
David Nicholson
Ph.D. Candidate
Sober Lab <http://www.biology.emory.edu/research/Sober/Home.html>
Emory Neuroscience Program <http://www.emory.edu/NEUROSCIENCE/>

**Comment by sbenthall** [comment]
Hello David,

Thanks for this patient and well-considered response.

I think that these changes will address my concerns with the paper.

Looking forward to seeing the next version.

- Seb

**Comment by NickleDave** [comment]
Hi Seb, I made those changes and pushed a new version to the repo. Let me
know what you think. Thanks, David

On Wed, Jun 29, 2016 at 11:17 AM, Sebastian Benthall <
notifications@github.com> wrote:

> Hello David,
>
> Thanks for this patient and well-considered response.
>
> I think that these changes will address my concerns with the paper.
>
> Looking forward to seeing the next version.
>
>    - Seb
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/208#issuecomment-229389369>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALYZijWnVTasMq1pD3D_n1TYsSU_z1kfks5qQoyFgaJpZM4IqNIV>
> .
>



-- 
David Nicholson
Ph.D. Candidate
Sober Lab <http://www.biology.emory.edu/research/Sober/Home.html>
Emory Neuroscience Program <http://www.emory.edu/NEUROSCIENCE/>

**Comment by fonnesbeck** [comment]
I reviewed the paper today, and have a few comments:

- I recommend moving the method section so that it appears before the results. Otherwise there is insufficient context to interpret the results. In my view, the methods are the most important component of the paper (particularly a technical paper), and should not be tacked on to the end.
- Related to this, it would be helpful to explicitly state what is being classified very early on in the document. It was not entirely clear on first reading. Being relatively unfamiliar with this type of application, for awhile I was under the impression that you were classifying songs to birds, and had to read ahead to clarify this.
- It is not entirely clear why these particular classification methods were compared, rather than others. It would be helpful to have a justification for your choices. I would be interested to know why random forests were not used, for example. 
- Related to this, I wondered why a machine learning approach was used, rather than a parametric statistical model, given that the data are not all that large. ML classifiers are generally more data-hungry than parametric statistical models.
- I'm always a little skeptical when accuracy is used as a performance metric, rather than a statistically proper scoring rule, or an ROC curve. Accuracy can be gamed pretty easily when, for example, the number of instances of a particular class is small. You might discuss the choice of scoring rule to allay these fears.
- The first part of the second paragraph of the results is used to describe the technical details of figure 3. This should really be part of the caption, and not part of the document text.
- In the results, you state:

> because I was concerned that the 536-dimensional feature vector would yield poor results for k-NN

You might explain to the reader the cause for this concern.

- In contrast with the previous reviewer, I like the first-person in scientific writing, but this is common in my field. Unless it is discouraged or prohibited by the guidelines of the proceedings, I would keep it.

I hope these comments are helpful. Let me know if anything is unclear or misinterpreted.

Best wishes,
Chris

**Comment by NickleDave** [comment]
Hi Chris,

Thank you for your helpful comments. Please see below:

   - I recommend moving the method section so that it appears before the
   results. Otherwise there is insufficient context to interpret the results.
   In my view, the methods are the most important component of the paper
   (particularly a technical paper), and should not be tacked on to the end.

Done

   - Related to this, it would be helpful to explicitly state what is being
   classified very early on in the document. It was not entirely clear on
   first reading. Being relatively unfamiliar with this type of application,
   for awhile I was under the impression that you were classifying songs to
   birds, and had to read ahead to clarify this.

I understand why this is confusing to someone outside of the songbird field
and I have tried to add some language in the intro to clarify.

   - It is not entirely clear why these particular classification methods
   were compared, rather than others. It would be helpful to have a
   justification for your choices. I would be interested to know why random
   forests were not used, for example

The point of the study was to compare previously published methods, because
as I state in the intro this has not been done in the songbird field in
spite of many (10-20) previously published papers. I chose the most
recently used algorithms for the species we study where code was already
available that I could reuse or at least use as a guide. Maybe I did not
make this explicit enough in the intro when I cited those papers. I added
more language to emphasize this.

While the point of this study was to compare the previously published
methods, I have thought about using random forests in future work. A new
paper has come out using deep learning to label Bengalese Finch syllables,
but again the authors do not use the same metrics they have used previously
to compare the new findings to their own previous work using different
algorithms. From what I have read, I gather that random forests can give
accuracy on par with some neural nets without requiring finicky
hand-tuning. I guess something like that is the reason you thought of
random forests? Please let me know.

   - Related to this, I wondered why a machine learning approach was used,
   rather than a parametric statistical model, given that the data are not all
   that large. ML classifiers are generally more data-hungry than parametric
   statistical models.

Again, the point was to compare the previously used machine learning
methods using openly-shared code and data. I did think I made that pretty
clear in the abstract and intro.

I'm not quite sure what a parametric statistical model is. Do you mean
something like logistic regression? Or Naive Bayes? The problem with Bayes
I think is that a lot of the features are going to be highly correlated
with each other...and yet useful for classification. Can you name some
models you would try? I don't think I can re-run everything and rewrite,
but I am interested to hear what you would look at.

   - I'm always a little skeptical when accuracy is used as a performance
   metric, rather than a statistically proper scoring rule, or an ROC curve.
   Accuracy can be gamed pretty easily when, for example, the number of
   instances of a particular class is small. You might discuss the choice of
   scoring rule to allay these fears.

I did specifically choose average accuracy instead of Rand accuracy because
I felt that it wasn't informative enough, as I point out in the methods and
results. I took out some language contrasting them because I got feedback
that some of my writing came off as if it was just attacking one paper, but
I could add that back in with less finger pointing.

I don't think I can use ROC curves for multiple classes; I looked at them
but my understanding is they are usually applied to binary classification
problems, and that the extensions to the multiple class case are pretty
messy. Also I thought ROCs are mainly used where the focus is on the
trade-off between false positives and true negatives. I'm not dealing with
e.g. concerns about rare events that I need to make sure are always
classified correctly at the expense of having more false positives.

By statistically proper scoring rule, do you mean a "strictly proper
scoring rule", e.g. Brier score? Is there one in particular that you think
would better address the question of how well each classifier assigns label
to syllable types?

When you say accuracy can be gamed when the number of instances of a class
is small, you mean in the training data? I know that part of the reason for
the variance I got in smaller training data subsets is that the number of
syllables can vary from song to song, so a random grab of a small number of
songs could have imbalanced classes in the training data subset. This issue
is minimized as the training data subset size grows: the species we study
sings syllables with a fixed frequency so the ratio of one class to another
stays fixed, and none of them is "rare". Using a number of songs to feed
the algorithms instead of number of samples is more like what a real
songbird researcher will do. I.e., the question I'm asking is, if I label
the first 3 songs the bird sings, that are essentially random draws from
some underlying distribution of all possible songs, how well will the
classifier do? Again I tried to explain this rationale in the methods but
maybe I need to rewrite?

   - The first part of the second paragraph of the results is used to
   describe the technical details of figure 3. This should really be part of
   the caption, and not part of the document text.
   - In the results, you state:

because I was concerned that the 536-dimensional feature vector would yield
poor results for k-NN

You might explain to the reader the cause for this concern.

Can you clarify what you're referring to here? Do you mean the paragraph
where I briefly describe the cross-validation etc. for figure 2 (not 3)?

re: the cause for concern, I had explained it in more detail in a later
section and provided a citation, but you're right that I should explain it
the first time. I moved it up to the first mention.

   - In contrast with the previous reviewer, I like the first-person in
   scientific writing, but this is common in my field. Unless it is
   discouraged or prohibited by the guidelines of the proceedings, I would
   keep it.

I think maybe the previous version was a little too first person but I
wouldn't mind adding some "I"s back to avoid a lot of the awkward passive
voice constructions. Please let me know what you think of the above replies
and then I can address that.

Thank you
David

On Mon, Jul 4, 2016 at 4:17 PM, Chris Fonnesbeck <notifications@github.com>
wrote:

> I reviewed the paper today, and have a few comments:
>
>    - I recommend moving the method section so that it appears before the
>    results. Otherwise there is insufficient context to interpret the results.
>    In my view, the methods are the most important component of the paper
>    (particularly a technical paper), and should not be tacked on to the end.
>    - Related to this, it would be helpful to explicitly state what is
>    being classified very early on in the document. It was not entirely clear
>    on first reading. Being relatively unfamiliar with this type of
>    application, for awhile I was under the impression that you were
>    classifying songs to birds, and had to read ahead to clarify this.
>    - It is not entirely clear why these particular classification methods
>    were compared, rather than others. It would be helpful to have a
>    justification for your choices. I would be interested to know why random
>    forests were not used, for example.
>    - Related to this, I wondered why a machine learning approach was
>    used, rather than a parametric statistical model, given that the data are
>    not all that large. ML classifiers are generally more data-hungry than
>    parametric statistical models.
>    - I'm always a little skeptical when accuracy is used as a performance
>    metric, rather than a statistically proper scoring rule, or an ROC curve.
>    Accuracy can be gamed pretty easily when, for example, the number of
>    instances of a particular class is small. You might discuss the choice of
>    scoring rule to allay these fears.
>    - The first part of the second paragraph of the results is used to
>    describe the technical details of figure 3. This should really be part of
>    the caption, and not part of the document text.
>    - In the results, you state:
>
> because I was concerned that the 536-dimensional feature vector would
> yield poor results for k-NN
>
> You might explain to the reader the cause for this concern.
>
>    - In contrast with the previous reviewer, I like the first-person in
>    scientific writing, but this is common in my field. Unless it is
>    discouraged or prohibited by the guidelines of the proceedings, I would
>    keep it.
>
> I hope these comments are helpful. Let me know if anything is unclear or
> misinterpreted.
>
> Best wishes,
> Chris
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/208#issuecomment-230349537>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALYZil6agP66gp_qnJ633kFkGTKaNfgVks5qSWpRgaJpZM4IqNIV>
> .
>



-- 
David Nicholson
Ph.D. Candidate
Sober Lab <http://www.biology.emory.edu/research/Sober/Home.html>
Emory Neuroscience Program <http://www.emory.edu/NEUROSCIENCE/>

**Comment by JuancaDuque** [comment]
Dear David,

I am sorry for my late review!! but it is better later that never :-)

This is a very nice work. I have only minor comments:

1) It would be nice to include in figures 2, 5, 6 and 7 the training errors just to see if there is some overfitting.
2) The paragraph 2 in page 3 is very important but is not clear. Please explain more clearly the the training and testing sets.
3) Convolutional neural network have been widely applied in natural language processing, have you considered to explore this type of machine learning type with your birds?
4) you can give a more academic tone to your paper! some paragraphs are a little informal. 

This is just curiosity: Does a bird with no social interactions produce some very basic song? it would be nice to se whether these birds born with some kind of basic set of syllables in their brain!!

The paper is of course good to be presented in Pycon.

cheers.

**Comment by sarostru** [comment]
Due to the complication of the proceedings deadline lining up with everyone's travel schedule to attend the conference we've decided to allow authors to spend an additional 2 days, that is until July 12th to complete any major changes to the submission.  This may impact your enjoyment of the conference, so we hope not too many of you need to take the time.  For reviewers, we ask that you read over this final document before the conference is over and post your decision here in the comments on or before July 17th.

Thanks and have a great Scipy!
Your proceedings co-chairs Scott Rostrup (@sarostru) and Sebastian Benthall (@sbenthall)

**Comment by NickleDave** [comment]
Hi Juan, thank you for comments and for taking the time to read the
article. I've got a couple of quick questions if you have a chance to
respond.

*1) It would be nice to include in figures 2, 5, 6 and 7 the training
errors just to see if there is some overfitting.*

I will try to add this--not sure how it will affect readability of the
plots.

* 2) The paragraph 2 in page 3 is very important but is not clear. Please
explain more clearly the the training and testing sets.*

You mean the paragraph that begins "Each type of classifier..."? Could you
clarify what specific details I should add about the data sets?

* 3) Convolutional neural network have been widely applied in natural
language processing, have you considered to explore this type of machine
learning type with your birds?*

There is already a paper out using convnets as part of a "hybrid algorithm"
that also uses Hidden Markov models to give the classifier some context
information. My next goal is to compare their model to the models I'm
presenting in this paper, and to determine how well all models work across
songs from many different Bengalese finches.

*4) you can give a more academic tone to your paper! some paragraphs are a
little informal.*

Can you specify which paragraphs are informal? I did try to rewrite in a
more academic way as per other reviewers comments.

*This is just curiosity: Does a bird with no social interactions produce
some very basic song? it would be nice to se whether these birds born with
some kind of basic set of syllables in their brain!!*

Yes, songbird species have innate song when raised in isolation, and by eye
it looks "unrefined" compared to a songbird raised with a tutor. Such
findings form the basis of our field; that's part of why we think they're a
great model for how humans learn to speak.

Here's a classic paper on it:
http://www.reed.edu/biology/professors/srenn/pages/teaching/2008_syllabus/2008_readings/7_Marler_tamura_1964.pdf

The hard part is figuring out what gives rise to the "basic set of
syllables". How much of it is in their brain and how much of it is in their
throat/beak/lungs?

Thanks again for your review

--David

On Wed, Jul 6, 2016 at 7:54 PM, Juan C Duque <notifications@github.com>
wrote:

> Dear David,
>
> I am sorry for my late review!! but it is better later that never :-)
>
> This is a very nice work. I have only minor comments:
>
> 1) It would be nice to include in figures 2, 5, 6 and 7 the training
> errors just to see if there is some overfitting.
> 2) The paragraph 2 in page 3 is very important but is not clear. Please
> explain more clearly the the training and testing sets.
> 3) Convolutional neural network have been widely applied in natural
> language processing, have you considered to explore this type of machine
> learning type with your birds?
> 4) you can give a more academic tone to your paper! some paragraphs are a
> little informal.
>
> This is just curiosity: Does a bird with no social interactions produce
> some very basic song? it would be nice to se whether these birds born with
> some kind of basic set of syllables in their brain!!
>
> The paper is of course good to be presented in Pycon.
>
> cheers.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/208#issuecomment-230941858>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALYZimUQz2iekBWR3RxwLVEWXTk8WxBZks5qTEAjgaJpZM4IqNIV>
> .
>



-- 
David Nicholson, Ph.D. Candidate
Sober Lab <http://www.biology.emory.edu/research/Sober/Home.html>, Emory
Neuroscience Program. <http://www.emory.edu/NEUROSCIENCE/>
www.nicholdav.info; <http://www.nicholdav.info>https://github.com/NickleDave

**Comment by NickleDave** [comment]
I realized I only saved the training accuracy for one of the three
algorithms. For the other two I have accuracy on a validation set (the rest
of the training data) and of course the testing accuracy.

I will re-run everything when I get back (using the same hyperparameters
and training sets) and save the training accuracy. Again I'm not sure if
the training accuracy will clutter up the current plots too much but I will
for sure include it in the results posted on-line and in the Jupyter
notebook.

On Mon, Jul 11, 2016 at 4:30 PM, David Nicholson <nicholdav@gmail.com>
wrote:

> Hi Juan, thank you for comments and for taking the time to read the
> article. I've got a couple of quick questions if you have a chance to
> respond.
>
> *1) It would be nice to include in figures 2, 5, 6 and 7 the training
> errors just to see if there is some overfitting.*
>
> I will try to add this--not sure how it will affect readability of the
> plots.
>
> * 2) The paragraph 2 in page 3 is very important but is not clear. Please
> explain more clearly the the training and testing sets.*
>
> You mean the paragraph that begins "Each type of classifier..."? Could you
> clarify what specific details I should add about the data sets?
>
> * 3) Convolutional neural network have been widely applied in natural
> language processing, have you considered to explore this type of machine
> learning type with your birds?*
>
> There is already a paper out using convnets as part of a "hybrid
> algorithm" that also uses Hidden Markov models to give the classifier some
> context information. My next goal is to compare their model to the models
> I'm presenting in this paper, and to determine how well all models work
> across songs from many different Bengalese finches.
>
> *4) you can give a more academic tone to your paper! some paragraphs are a
> little informal.*
>
> Can you specify which paragraphs are informal? I did try to rewrite in a
> more academic way as per other reviewers comments.
>
> *This is just curiosity: Does a bird with no social interactions produce
> some very basic song? it would be nice to se whether these birds born with
> some kind of basic set of syllables in their brain!!*
>
> Yes, songbird species have innate song when raised in isolation, and by
> eye it looks "unrefined" compared to a songbird raised with a tutor. Such
> findings form the basis of our field; that's part of why we think they're a
> great model for how humans learn to speak.
>
> Here's a classic paper on it:
> http://www.reed.edu/biology/professors/srenn/pages/teaching/2008_syllabus/2008_readings/7_Marler_tamura_1964.pdf
>
> The hard part is figuring out what gives rise to the "basic set of
> syllables". How much of it is in their brain and how much of it is in their
> throat/beak/lungs?
>
> Thanks again for your review
>
> --David
>
> On Wed, Jul 6, 2016 at 7:54 PM, Juan C Duque <notifications@github.com>
> wrote:
>
>> Dear David,
>>
>> I am sorry for my late review!! but it is better later that never :-)
>>
>> This is a very nice work. I have only minor comments:
>>
>> 1) It would be nice to include in figures 2, 5, 6 and 7 the training
>> errors just to see if there is some overfitting.
>> 2) The paragraph 2 in page 3 is very important but is not clear. Please
>> explain more clearly the the training and testing sets.
>> 3) Convolutional neural network have been widely applied in natural
>> language processing, have you considered to explore this type of machine
>> learning type with your birds?
>> 4) you can give a more academic tone to your paper! some paragraphs are a
>> little informal.
>>
>> This is just curiosity: Does a bird with no social interactions produce
>> some very basic song? it would be nice to se whether these birds born with
>> some kind of basic set of syllables in their brain!!
>>
>> The paper is of course good to be presented in Pycon.
>>
>> cheers.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/scipy-conference/scipy_proceedings/pull/208#issuecomment-230941858>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ALYZimUQz2iekBWR3RxwLVEWXTk8WxBZks5qTEAjgaJpZM4IqNIV>
>> .
>>
>
>
>
> --
> David Nicholson, Ph.D. Candidate
> Sober Lab <http://www.biology.emory.edu/research/Sober/Home.html>, Emory
> Neuroscience Program. <http://www.emory.edu/NEUROSCIENCE/>
> www.nicholdav.info; <http://www.nicholdav.info>
> https://github.com/NickleDave
>



-- 
David Nicholson, Ph.D. Candidate
Sober Lab <http://www.biology.emory.edu/research/Sober/Home.html>, Emory
Neuroscience Program. <http://www.emory.edu/NEUROSCIENCE/>
www.nicholdav.info; <http://www.nicholdav.info>https://github.com/NickleDave

**Comment by sbenthall** [comment]
Thanks for submitting such an interesting paper to the conference, and for your edits. I recommend this paper for acceptance.

A minor correction:

"each songbird produce" -> produces

**Comment by sarostru** [comment]
@fonnesbeck Did you want to take a another look at this?  Otherwise from @sbenthall and @JuancaDuque 's feedback it looks ready to go, @sbenthall can you take over on this one?

@NickleDave for the final version, if you could do a careful proofread of the paper, @sbenthall and I will help with updating the proceedings build from draft to final.

**Comment by fonnesbeck** [comment]
@NickleDave by "parametric" I did indeed mean parametric statistical models, such as regression, which tend to be less data-hungry than machine learning methods.

@sarostru I'm happy with the responses to my questions

**Comment by NickleDave** [comment]
@sbenthall @sarostru I did a careful proofread--should be ready to go to final

**Pull request merged**
