### PR TITLE
Slides: Add anywidget talk slides

### PR DESCRIPTION
**Pull request by manzt**

### CODE REVIEW

**Comment by tkoyama010** [comment]
@manzt It was really cool presentation. Thanks!

**Review by mepa — COMMENTED** [review]
Hi! Could you please move `presentations/manzt-anywidget/` to `presentations/slides/manzt-anywidget/`?

**Comment by manzt** [comment]
Done, sorry about that!

**Comment by mepa** [comment]
The full path to each file from the root of `scipy_proceedings` repo should be: 
- `presentations/slides/manzt-anywidget/info.json`
- `presentations/slides/manzt-anywidget/slides.pdf`

And no worries! The proceedings comittee will fix things up as needed when we publish the proceedings but it's helpful if you have chance to change it to the expected path.

**Pull request merged**
