### PR TITLE
ENH: 2018 scipy_proc.json update

### PR DESCRIPTION
**Pull request by deniederhut**
This is the file that contains the metadata for the proceedings, including things like who is on the committe. We are currently missing a few pieces of info, including:

- all the reviewers for the 2018 proceedings
- scholarship recipients

### CODE REVIEW

**Comment by mpacer** [comment]
What is it that creates this file such that it ended up being un-pretty-printed at some point? Can we fix the code that does that to make it actually pretty print when it does the `json.dump`?

**Comment by deniederhut** [comment]
I think you already made as issue about this.

**Comment by mpacer** [comment]
Indeed, I was hoping you could address it in this PR, but it's more important that we get this merged.

**Comment by mpacer** [comment]
#353 is the issue that still needs addressing

**Comment by mpacer** [comment]
Hi @deniederhut I noticed that you made this PR on the wrong branch, I'm going to revert it and force push over the 2018 branch and I ask that you remake the PR against `dev`. Thanks.

**Comment by mpacer** [comment]
NVM I'll take care of this.

**Pull request merged**
