### PR TITLE
Booktabs

### PR DESCRIPTION
**Pull request by bmcfee**
This ought to fix issue #127

### CODE REVIEW

**Comment by bmcfee** [comment]
aw man, I screwed up my merge history again... sorry!  Only that last commit https://github.com/bmcfee/scipy_proceedings/commit/0bd43e82b5711d6684af230185f7771bc8180ee6 is necessary here.

**Comment by stefanv** [comment]
Awesome, thanks @bmcfee!  Can you rebase to get rid of the other commits?

**Comment by bmcfee** [comment]
done.

**Comment by katyhuff** [comment]
Looks good to me.

**Pull request merged**
