### PR TITLE
Paper: ChiantiPy: a Python package for Astrophysical Spectroscopy

### PR DESCRIPTION
**Pull request by wtbarnes**
**Title**: ChiantiPy: a Python Package for Astrophysical Spectroscopy
**Authors**: Will T. Barnes, Kenneth P. Dere

### CODE REVIEW

**Comment by gtelzur** [comment]
Hello, I was assigned to be your reviewer. 
**I recommend to accept the paper as it is.** 
However, for your talk, I would like to recommend to discuss more about your insights about development in Python and less about equations and too detailed physics. This will be more appealing to the audience.

Good luck,

Guy Tel-Zur

@proceedings, The paper is ready to be merged.

**Comment by katyhuff** [comment]
Thanks @gtelzur for your prompt review . We're waiting for at least one more review of this paper before it can be merged.

**Comment by WorklnProgress** [comment]
Few comments: 
1) On Page 1, in the following sentence, did you mean momentum and not moment?
While IDL has been the lingua franca of solar physics for
over twenty years, Python is gaining moment in the community
and is the language of choice for many younger researchers. 

2) For clarity, might be good to add which common calculations and API you will be describing so reader knows what to expect and looks for those. 

3) Just above conclusion, when you describe the CI and documentation, you refer to Sphinx for document generation before you describe it in detail in next paragraph. A rewording to separate out CI and Doc generation tools might make it read better. 

Rest looks great and really helpful!

**Comment by wtbarnes** [comment]
@gtelzur Thanks for the review! Yes the talk will have fewer equations and some more info about the history and development of ChiantiPy. Thanks for the suggestions.

@WorklnProgress Regarding point 1, yes that is a typo and should be "momentum." I agree with your points in 2 and 3 as well. I think both should help improve clarity. Thanks for your feedback!

**Comment by lchjoel1031** [comment]
Hi, 
It was my pleasure to be assigned as a reviewer. ChiantiPy is very important for the astronomical society and the effort from the authors to put down a detail documentation of the package is really appreciated! This paper is very comprehensive and well written. I only have very 2 minor comments:

1. On page 2, about the database structure "{el}/{el}_{ion}/{el}_{ion}.{filetype}". While it might be self-explanatory to experienced users, it would be useful to show what do "el" and "ion" mean (element and ionization level?), especially for first time users. 

2. On page 3. Could you please put foonotes 2 and 3 on this page (page 3), not page 4.

Besides these two minor points, I would recommend to accept the paper as is.

Cheers,
Lee, Chien-Hsiu

@proceedings, The paper is ready to be merged.

**Comment by wtbarnes** [comment]
@lchjoel1031 Thanks for your feedback! I've addressed your concerns in the most recent set of changes.

**Comment by wtbarnes** [comment]
@WorklnProgress The latest commit incorporates your suggestions as well. Please let me know if you'd like to seen any other fixes. Thanks again!

**Comment by katyhuff** [comment]
@lchjoel1031 has declared this paper ready to be merged.  @WorklnProgress , it appears the author @wtbarnes has made changes in response to your comments, do you feel this is ready for publication?

**Comment by WorklnProgress** [comment]
@proceedings, the paper is ready to be merged.

**Comment by dalippa** [comment]
@lchjoel1031 @WorklnProgress Please provide your name and if you are attending the conference so you can get a reviewer sticker.

**Comment by gtelzur** [comment]
Hello,

Unfortunately I won't be able to attend the conference.
Can you please send me a PDF of the sticker?

Best regards,

Guy


*Guy Tel-Zur, Ph.D. *External Lecturer | Computer Engineering

gtelzur@post.bgu.ac.il

Tel: +972-54-444-3477 *|* +972-50-624-4876

P Please don't print this email unless you really need to

*like  <https://www.facebook.com/telzur>**|* web  <http://tel-zur.net/>*|*
follow  <http://twitter.com/telzur>*|* network
<http://www.linkedin.com/in/telzur>


Join my Cloud Computing group with more than 20,000 members:
*https://www.facebook.com/groups/1stcloud/
<https://www.facebook.com/groups/1stcloud/>*

**Comment by WorklnProgress** [comment]
Hi,

Unfortunately I won’t be able to attend the conference. But would love getting a pic of sticker to see if I can print it :) 

Regards,
Priya

**Comment by deniederhut** [comment]
@dalippa this is a paper from the 2017 proceedings

**Comment by dalippa** [comment]
@deniederhut Argh. Sorry about that.

**Pull request merged**
