### PR TITLE
update readme with 2024 schedule

### PR DESCRIPTION
**Pull request by hongsupshin**
- Updated the deadlines according to the new [2024 schedule](https://docs.google.com/spreadsheets/d/1ChYRPkZTtvwStq-5AIFtjPI-Hx8A8hdVnGenArU-0us/edit#gid=0)
- Added new proceedings co-chairs based on [SciPy 2024 Organizing Committee Members doc](https://docs.google.com/spreadsheets/d/1ChYRPkZTtvwStq-5AIFtjPI-Hx8A8hdVnGenArU-0us/edit#gid=0)

Notes
- `https://www.scipy2024.scipy.org/code-of-conduct` current doesn't exist, but I expect this to be updated before the conference
- Changed the link to the review criteria from `master` branch to [`2024`](https://github.com/scipy-conference/scipy_proceedings/blob/2024/review_criteria.md) branch

### CODE REVIEW

**Review by cbcunc — CHANGES_REQUESTED** [review]
The link for the COC is 404. Maybe check on Slack  to see what the link should be.

**Comment by hongsupshin** [comment]
Following @ivanov 's suggestion from the discussion on Slack, changed the code of conduct link to NumFOCUS's. Also added the text "Attendees at SciPy 2024 are subject to the NumFOCUS Code of Conduct."

**Review by ivanov — APPROVED** [review]

**Comment by hongsupshin** [comment]
Per our discussion yesterday, I added the following two dates:
- Reviewer invitations sent: 3/26/2024
- Deadline to respond to offer to be a reviewer: 4/2/2024

Also made the deadline date text consistent across all deadline sections

**Review by ivanov — APPROVED** [review]
I don't want to step on the toes of the Proceedings committee in approving this, but if you're just looking for a sanity check, this looks good to me (and we can always make more changes as necessary).

**Review by cbcunc — APPROVED** [review]

**Pull request merged**
