### PR TITLE
Paper: pgmpy: Probabilistic Graphical Models using Python (Ankan & Panda)

### PR DESCRIPTION
**Pull request by ankurankan**
Initial Draft.

### CODE REVIEW

**Comment by katyhuff** [comment]
Hi There, 
I just wanted to let you know that your paper is currently failing to build [on our build server](nipy.bic.berkeley.edu:5000). It must build in order to be reviewed.

The error is thus:

```
[ 16/06 07:57 Build failed ] pgmpy: Probabilistic Graphical Models using Python (Ankan & Panda) by ankurankan 
• Updating proceedings build tools in /home/katyhuff/procbuild/procbuild/../cache/scipy_proceedings...
Already up-to-date.
• Check out paper repository...
Cloning into '/tmp/tmpYI7xBr'...
Installing proceedings build tools...
• Build the paper...
:71: (WARNING/2) Inline strong start-string without end-string.
Building: ankur_ankan
Traceback (most recent call last):
File "publisher/build_paper.py", line 179, in 
build_paper(paper_id)
File "publisher/build_paper.py", line 164, in build_paper
rst2tex(in_path, out_path)
File "publisher/build_paper.py", line 84, in rst2tex
settings_overrides=settings)
File "/usr/lib/python2.7/site-packages/docutils/core.py", line 414, in publish_string
enable_exit_status=enable_exit_status)
File "/usr/lib/python2.7/site-packages/docutils/core.py", line 662, in publish_programmatically
output = pub.publish(enable_exit_status=enable_exit_status)
File "/usr/lib/python2.7/site-packages/docutils/core.py", line 219, in publish
output = self.writer.write(self.document, self.destination)
File "/usr/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
self.translate()
File "/usr/lib/python2.7/site-packages/docutils/writers/latex2e/__init__.py", line 246, in translate
self.document.walkabout(visitor)
File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
if child.walkabout(visitor):
File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
if child.walkabout(visitor):
File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
if child.walkabout(visitor):
File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 166, in walkabout
visitor.dispatch_visit(self)
File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
return method(node)
File "/tmp/tmpYI7xBr/publisher/writer/__init__.py", line 77, in visit_field_body
text = self.encode(node.astext())
File "/usr/lib/python2.7/site-packages/docutils/writers/latex2e/__init__.py", line 1490, in encode
text = text.translate(table)
TypeError: expected a character buffer object
Error building paper /tmp/tmpYI7xBr/papers/ankur_ankan. Aborting.
Error code 1
```

**You can try fixing stuff and then pressing the refresh button to the right of your paper title on the build server page until you get it building.**

**Comment by Carreau** [comment]
Really agreeable read, I am not an expert in the field but I was happy to read this. 

The article make a good job at describing the library, which is, as advertised, well documented and well written (for the quick look I had). 

A few improvement point (maybe):
  - You have a conda build, why not also a PyPI package ?
  - Which version of Python do you target ? Travis seem to be 3.4 only, I know many scientist are still on 2.7. If you are (plan to be) Python 3 only, say it, it is great to see that and one more data point for Python 3 adoption,  loads of people will be pleased. If you plan on support 2.7 too, say it, many other people will be pleased.

**Comment by ankurankan** [comment]
@Carreau Thank a lot for your comments. 

We don't have a conda build right now. We have mentioned only about installing dependencies in conda. Also since we haven't done our first release yet, we haven't put pgmpy on PyPI. 

I have mentioned in the installing section that pgmpy runs only on python 3. And now have also fixed travis to run on multiple versions of python3 (thanks for pointing that).

Please let me know if you have any other suggestions for improving.

**Comment by Carreau** [comment]
> We don't have a conda build right now. We have mentioned only about installing dependencies in conda. Also since we haven't done our first release yet, we haven't put pgmpy on PyPI.

Oh, I missread the files in the repository, sorry about that.

> I have mentioned in the installing section that pgmpy runs only on python 3

OK, I see that now, I skimmed through install too fast apparently. Still if you like I think a statement of your Python 3 only choice could be nice. I don't know of many scientific packages that target Python 3 only. Up to you. 

As for PyPI, I would (at least) register the package name before someone else snatch it.

Otherwise nothing else to say. 

Thanks a lot.

**Comment by Carreau** [comment]
@katyhuff & @jaberg I think the paper is ready.

**Comment by jaberg** [comment]
Paperbot: http://nipy.bic.berkeley.edu:5000/download/11

**Comment by jaberg** [comment]
@ankurankan Great lib! I would really like to see more comparison with the existing modeling and inferences tools that you mention in the introduction. This paper is your chance to compare and contrast the libraries, and explain what makes yours uniquely useful. After reading the current paper, I don't know how to decide if I should use pygmy or bbn, pymc, or pgm, or similar tools for R, or Matlab, etc.  How do they compare in terms of modeling abilities, inference algorithms, dependencies, speed, etc. Why did you make this library? Why should anyone use it?

The paper itself is already good, what's missing is the context.

**Comment by ankurankan** [comment]
@jaberg I have added a section for comparing it with other libraries. Please have a look and let me know if you have any suggestions.

**Comment by jaberg** [comment]
That comparison is helpful!
@katyhuff my comments have been addressed

**Pull request merged**
