### PR TITLE
Paper: Towards Explicit Models for the Practice of Computer Programming

### PR DESCRIPTION
**Pull request by SamPenrose**
This is a placeholder. It is not complete and does not yet compile to PDF.

### CODE REVIEW

**Comment by mpacer** [comment]
I think you aren't supposed to have arbitrary indentations at the beginning of your paragraphs as those are syntactically meaningful for RestructuredText. I'm not sure if that would allow your paper to build but that would explain the indentation errors.

**Comment by SamPenrose** [comment]
Yes, this is an unbuildable placeholder. My apologies. Fix coming.

**Comment by mpacer** [comment]
@SamPenrose Comprehensive review deadlines are approaching and reviewers won't be able to reasonably review your paper if it cannot build.

**Comment by manojpandey** [comment]
@SamPenrose Slight reminder - I just checked and build is failing as of now. Please see !

**Comment by mpacer** [comment]
@SamPenrose We're regretfully going to have to close this submission as it did not build by the comprehensive review deadline which meant that no reviewers were able to review your paper. We hope you will consider submitting to the proceedings in future years.

**Comment by SamPenrose** [comment]
I was just going to withdraw it. My apologies for the noise.

**Pull request closed without merging**
