### PR TITLE
Paper: PyHRF: A Python Library for the Analysis of fMRI Data Based on Local Estimation of Hemodynamic Response Function

### PR DESCRIPTION
**Pull request by himito**
**Title:** PyHRF: A Python Library for the Analysis of fMRI Data Based on Local Estimation of Hemodynamic Response Function

**Authors:** Jaime Arias, Philippe Ciuciu, Michel Dojat, Florence Forbes, Aina Frau-Pascual , Thomas Perret, Jan M. Warnking

### CODE REVIEW

**Comment by himito** [comment]
Hello,

We have a problem with the generation of the PDF file on the  `Scipy server`. We tried to fix it without success :\

**Comment by mpacer** [comment]
@himito Does this work locally when you run `./make_paper papers/jaime_arias`?

**Comment by mpacer** [comment]
Nb: if you have it on a branch with a name that is not 2017 it is syntactically simpler for me to assign it to a local branch that doesn't conflict with my local 2017. 

It's not _substantially_ more complicated, but it is complicated enough that I need to look it up. 

@deniederhut @katyhuff @dalippa Does that seem like a reasonable recommendation in future years? Your local branch should be named something other than `2017` or `master`?

**Comment by mpacer** [comment]
A thought having looked at this and this stackexchange https://tex.stackexchange.com/questions/249579/pdfendlink-ended-up-in-different-nesting-level-than-pdfstartlink-error-with (which has your error). 

Because the formatting is slightly different, it's breaking one of your links between two pages page, unfortunately the easiest way for you to run this on the test server is to submit PRs at this point. 

I should really make it a docker instance so that this behaviour could be more reproducible. I apologise for the difficulty.

**Comment by dalippa** [comment]
@mpacer The reason for the forked repository is that the branch name shouldn't matter.

**Comment by mpacer** [comment]
@dalippa I completely disagree that that is **the** reason why we use forked repositories. But we can discuss that elsewhere as it's not relevant to this.

**Comment by himito** [comment]
Hi @mpacer,
Thank you for your help. Is it possible to know what link generates the problem ? I compile the same file on my machine and other machines, and it works :\.

**Comment by mpacer** [comment]
I haven't figured out how to detect which link it is directly, since I can't inspect the pdf directly since it won't build. When I run it locally it works too meaning it has to do with the server. I'm trying to figure out why it changes the line spacing and am having some trouble.

My guess is that it's the citation with a tonne of authors, as it's the only unusually  "long" element in your file as far as I could see. But that's just a hunch. 

But you should be able to have that as part of your paper so the real solution is for me to fix the spacing issue.

**Comment by mpacer** [comment]
Just got the changes that fix the spacing issue merged into the server, so now your paper builds as expected!

**Comment by himito** [comment]
Thank you so much @mpacer !

**Comment by nickwan** [comment]
Hi authors,
In general, this paper actually reads very well and isn't too neuroscience-heavy for this conference. I think it is a useful tool and shows (in brief) advantages of using a JDE approach to HRF data to rectify possible type 2 errors when using traditional toolboxes (i.e. SPM, FSL). I only have minor comments.

To stay close to SciPy's suggested reviewing criteria, I'll break my review down into the sections they have listed on the [criteria page](https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md). 

**Written quality**
No concerns. Overall, well-written. Please check for capitalization errors (i.e. page 3: "jupyter").

**Technical content**
No concerns, although I have some suggestions for markdown presentation within the paper below (perhaps unnecessary).

**Novelty/impact**
PyHRF seeks to promote a Bayesian-based method in JDE to estimate HRF concentration where other packages promote frequentist-based methods like GLM. The paper also subtly promotes the use of open data resources (OpenfMRI, NeuroVault), which is an area that is also growing in the neuroscience community. 

**Verifiability**
No concerns. Many references and links to cited resources used within this paper.

**Other requirements**
_Minor suggestions_
Some of the code snippets are concise but more difficult to follow. Since the majority of attendees will be familiar with Python, these are not issues but rather suggestions. For example, pg 4 contains a code snippet that is not difficult to follow, but could be made perhaps easier to read if a little less compact. 

```python
# Original code
slice_timing = Node(
    spm.SliceTiming(num_slices=NUM_SLICES,
        time_repetition=TR,
        time_acquisition=TA,
        slice_order=SLICE_ORDER,
        ref_slice=REF_SLICE),
    name='slice_timing_node')
```

```python
# Proposed, less compact code
node_var = spm.SliceTiming(num_slices=NUM_SLICES,
        time_repetition=TR,
        time_acquisition=TA,
        slice_order=SLICE_ORDER,
        ref_slice=REF_SLICE)

slice_timing = Node(node_var,
    name='slice_timing_node')
```
Might just be personal preference, but nested function calls just seem harder to unpack when trying to demonstrate a technique for the first time. This shows up a few different times, looking over the accompanying ipynb (i.e. nesting os.path.join() in glob.glob(); even though os.path.join() is a relatively common python call, breaking it into one extra line above glob.glob() wouldn't be the end of the world).  But, your style may vary. And that doesn't deter from the content of this paper. 

Figure 9 and 10 is a bit messy in terms of navigation. I would recommend merging these two figures into one figure and label within-figure more precisely than by area (e.g. 'top left', 'bottom left', 'right'). You don't need all three cuts from NeuroVault to demonstrate PyHRF parcel area accuracy. I recommend only using the dorsal view. Furthermore, on figure 10, labeling with letters would help. and "A)" next to the top left image, "B)" next to the bottom left, and "C)" on the time course figure would help. "Top left" etc. is confusing since you are saying "top left" in reference to the entire figure and not just the "top-left" brain (aka the first row, first column brain). Flipping the arrangement of the subplots in Figure 10 would also increase white space; move the time course to the left and the topo plots to the right (this may also mean to re-reference the time course to be "A)" as opposed to "C)").  Finally, despining the top and right axis borders from the time course figure and moving the legend to the bottom-left white space area would most likely allow for enough room required to merge Figure 9 into Figure 10. 

However, as stated before, these figure suggestions are not deal-breakers. Just suggestions for even more clarity.

**Comment by adelavega** [comment]
Overall, I find this manuscript to be a strong contribution to SciPy, and recommend acceptance. The technical contribution of providing HRF estimation for fMRI in an easy to use package should be quite useful to the field, and the manuscript is written is a way that should be accesible to non-experts. 

I have some minor comments that could further improve this manuscript. I'll use the same sections as @nickwan in order to make my review easy to follow. 

Written quality
No major concerns, although there are several grammatical and spelling errors that should be carefully checked (I will comment in line for errors I've spotted)

Technical content
No major concerns. The technical contributions of this paper are robust. However, although this is a technical report, the discussion could be expanded. In particular, it might be useful to very briefly state how this package helps researchers achieve the goal noted in the introduction of clinical application. Additionally, it would be useful to comment on future directions of this package, and current limitations. In particular, the limitation of parcel-level analysis is significant, as the majority of the field operates at the voxel level. It would be useful to know if voxel-level estimation is something that will be supported down the line, or is computationally too costly. 

These sort of comments could help guide potential users as to the utility and limitations of this package, and increase the potential audience. 

Novelty/impact
PyHRF allows users to estimate the HRF response in fMRI studies using state-of-the-art Bayesian methods that are currently not supported in more mainstream packages. This package makes an important technical contribution to a problem that is too often ignored (variability of HRF).

Verifiability
Overall, the authors did an excellent job of citing sources, packages, and resources (e.g. OpenfMRI, NeuroVault, other Python packages). 

Other requirements
Minor: In code snippets, it is not always clear which library a method or class originates from. For example `Node` is from nipype, but that is not clear in the code snippet as the import is not shown. Moreover, the style used is inconsistent as some methods/classes are called from another library (e.g. `spm.SliceTiming`. This could be done in a more consistent manner, and if there is space the imports could be shown. If this is not possible due to space, feel free to ignore.

I agree with @nickwan that the final two figures (9 and 10) are too inconsistent. I would prefer to display the two figures adjacent to each other, so that it is easy to visually compare the results from the methods. The same orientation (e.g. axial & sagital) should be used for both. For Figure 9, I would also suggest downloading the image from NeuroVault and display using nlearn, as in Figure 10. Perhaps overlaying both results in the same figure would also be useful, although I could foresee it may be too crowded.

**Comment by katyhuff** [comment]
@nickwan and @adelavega , thank you for your reviews! It appears that @himito has made changes in response to your comments. In your opinion, is this paper ready to be merged?

**Comment by nickwan** [comment]
I have read over the updated version and I believe all my comments were addressed to the best of the author's abilities; so yes, ready to be merged! 

Good work, everyone! Thanks for letting me be apart of the process.

**Comment by himito** [comment]
We thank the reviewers @nickwan  @adelavega  for their detailed comments that helped us to improve this paper :)

**Comment by adelavega** [comment]
Hi all, the changes look good to me, the paper looks ready to be merged. Nice work!

**Pull request merged**
