### PR TITLE
adds publisher changes to support bibtex in rst files as their own thing

### PR DESCRIPTION
**Pull request by michaelpacer**
The second solution totally worked once I switched the arguments of the line

```
git checkout -- 2015 publisher/build_paper.py publisher/writer/__init__.py
```

to 
```
git checkout 2015 -- publisher/build_paper.py publisher/writer/__init__.py
```

And it looks like the merge is catching the right differences. 

Thanks @katyhuff for writing that code making my life much easier!

### CODE REVIEW

**Comment by katyhuff** [comment]
Thank you @michaelpacer ! sorry that was a pain in the butt. I'm going to check to make sure it doesn't break any of the builds in the build bot and then Ill pull it. Thanks for this contribution!!

**Comment by katyhuff** [comment]
bummer. Turns out every single paper build is now failing except for yours.. 

```
[ 16/06 19:12 Build failed ] PySPLIT (Cross) by mscross 
• Updating proceedings build tools in /home/katyhuff/procbuild/procbuild/../cache/scipy_proceedings...
From https://github.com/scipy-conference/scipy_proceedings
e3df71a..f8cd86b 2015 -> origin/2015
Updating e3df71a..f8cd86b
Fast-forward
publisher/build_paper.py | 68 ++++++++++++++++++++++++++++++++------------
publisher/writer/__init__.py | 21 ++++++++++++--
2 files changed, 69 insertions(+), 20 deletions(-)
• Check out paper repository...
Cloning into '/tmp/tmpNbBgLW'...
Installing proceedings build tools...
• Build the paper...
Building: mellissa_cross_p
*** Warning: /tmp/tmpNbBgLW/publisher/../output/mellissa_cross_p/paper_stats.json does not exist.
Traceback (most recent call last):
File "publisher/build_paper.py", line 211, in 
build_paper(paper_id)
File "publisher/build_paper.py", line 197, in build_paper
pdflatex_stdout = tex2pdf(out_path)
File "publisher/build_paper.py", line 137, in tex2pdf
bib_file = os.path.join(out_path, d["bibliography"] + '.bib')
KeyError: 'bibliography'
Error building paper /tmp/tmpNbBgLW/papers/mellissa_cross_p. Aborting.
Error code 1
```

**Comment by katyhuff** [comment]
So, because of the way the build server works, I figured the easiest way to test it was to merge it and see if it broke everything. It did, as you can see above, which is a shame. Could you please let me know if/when you are sure that these changes don't break everyone else's papers? I unfortunately don't have time to help debug this. I have returned the build server to its previous state with a git force push.

**Comment by michaelpacer** [comment]
I'm not going to have time to debug this either — it looks like the problem is that the dictionary that loads expects to see the "bibliography" option in the json file and for some reason that isn't being saved if no bibliography is being saved, which is why I had included  a `self.bibliography = ''` call in the original version of my changes which must have been reverted at some point in the process. I readded again the  `self.bibliography = ''` so that it won't have any key errors when later called. hopefully this works.

**Comment by michaelpacer** [comment]
I don't know how to reissue this pull commit, but if you can try it now, it should at least not give that annoying error for anyone's paper with the bibstuff2 version that I just pushed and PRd.

**Pull request merged**
