### PR TITLE
Paper: libyt: a Tool for Parallel In Situ Analysis with yt

### PR DESCRIPTION
**Pull request by cindytsai**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: @mepa

*Reviewers*: @ktzhao, @bjmcder

### CODE REVIEW

**Comment by deniederhut** [comment]
@scoobies assign @mepa as editor

**Comment by scoobies** [comment]
Assigned! @mepa is now the editor

**Comment by mepa** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"cindytsai-shin-rong_tsai"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpwn8oa1ui'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: shin-rong_tsai\n*** Warning: /tmp/tmpwn8oa1ui/publisher/../output/shin-rong_tsai/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/cindytsai-shin-rong_tsai.pdf", "build_status"=>"success", "build_timestamp"=>"03/06 14:47"}, "status"=>"success"}}

**Comment by mepa** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0067-0049/192/1/9 is OK
- 10.1088/0067-0049/211/2/19 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1093/mnras/sty2586 is OK
- 10.1038/nphys2996 is OK
- 10.1103/PhysRevLett.113.261302 is OK
- 10.1086/588755 is OK
- 10.1088/0004-637X/774/1/17 is OK
- 10.1103/PhysRevLett.85.1158 is OK
- 10.1103/PhysRevE.57.4150 is OK
- 10.1088/1475-7516/2021/01/011 is OK
- 10.1016/j.physrep.2016.06.005 is OK
- 10.3847/1538-4357/aaa893 is OK
- 10.1086/466517 is OK
- 10.1088/0004-637X/765/1/29 is OK
- 10.1109/LDAV.2011.6092322 is OK
- 10.1093/mnras/250.3.581 is OK
- 10.1086/317361 is OK
- 10.1051/0004-6361:20011817 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.2514/6.2003-3559 may be a valid DOI for title: Upwind and high-resolution methods for compressible flow: From donor cell to residual-distribution schemes

INVALID DOIs

- https://doi.org/10.1016/0021-9991(84)90143-8 is INVALID because of 'https://doi.org/' prefix
```

**Comment by deniederhut** [comment]
@scoobies add @ktzhao to reviewers

**Comment by scoobies** [comment]
@ktzhao added to the reviewers list!

**Comment by deniederhut** [comment]
@scoobies code of conduct

**Comment by scoobies** [comment]
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

**Comment by scoobies** [comment]
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

**Comment by deniederhut** [comment]
@scoobies add @bjmcder to reviewers

**Comment by scoobies** [comment]
@bjmcder added to the reviewers list!

**Comment by bjmcder** [comment]
@cindytsai I'm going through the paper and so far everything looks good! I mostly just have minor editorial comments. 

I'd like to run some test problems to get a feel for how the library works. The GAMER shock tube problem is sufficient, but I'm getting errors when I try to run it with libyt support. I also have access to HPC resources if you have a ready-to-go example from the paper I can replicate.

**Comment by cindytsai** [comment]
Hi @bjmcder, thanks for giving some feedbacks!

I'm not sure what error message you get, so I'll just list the following steps. (The doc in GAMER doesn't have a specific section about using `libyt`, we will work on that.)
1. Get [`libyt` in Interactive Mode and `yt_libyt`](https://calab-ntu.github.io/libyt/HowToInstall.html#how-to-install)
2. When following [GAMER -- 1D Shock Tube](https://github.com/gamer-project/gamer/wiki/Quick-Start%3A-1D-Shock-Tube), please add these configuration in `Makefile`. The first two line is for GAMER to run in MPI. Since currently `libyt` supports _fake_ serial (`mpirun -np 1`), we will support compiling without MPI later. The 3rd and 4th line is for GAMER to use `libyt` interactive mode.
   ```
   #SIMU_OPTION += -DSERIAL
   SIMU_OPTION += -DLOAD_BALANCE=HILBERT
   SIMU_OPTION += -DSUPPORT_LIBYT
   SIMU_OPTION += -DLIBYT_INTERACTIVE
   ```
3. After you have copied GAMER executable and example problem into working directory `bin/shocktube`, update `Input__Parameter` by adding these lines at the bottom:
   ```
   YT_SCRIPT                     inline      # inline Python script to read
   YT_VERBOSE                    1           # Log level of libyt
   YT_FIG_BASENAME               ShockTube   # Figure base name
   ```
4. Create inline Python script `inline.py`. The Python function `yt_inline` here is equivalent to `plot__hydro_dens.gpt` provided in the example.
   ```python
   # inline.py
   import yt_libyt
   import yt

   yt.enable_parallelism()

   def yt_inline():
       # Load dataset through libyt
       ds = yt_libyt.libytDataset()
       
       # Draw LinePlot along x-axis and disable log scale
       plot = yt.LinePlot(ds, ("gamer", "Dens"), [0, 0, 0], [1, 0, 0], 64)
       plot.set_log(("gamer", "Dens"), False)

       # Save the result
       plot.save()

   def yt_inline_inputArg(*args):
       pass
   ```
   The `plot.save()` saves figure on each MPI process, and it may seem unnecessary. We need to do this because `yt` needs data IO for which to save a figure with log scale disabled. This is yet another stuff we are working on to make `yt` more compatible inside `libyt`.
5. Run GAMER,
   ```bash
   OMPI_MCA_osc=sm,pt2pt mpirun -np 4 ./gamer
   ```
6. If you want to pause GAMER and enter interactive Python prompt, just create `LIBYT_STOP` file.

If you still have questions, I am really happy to help. 

And as for reproducing the results in paper, I'll prepare it in another thread. Do you need both of them (Fuzzy Dark Matter and Core-Collapse Supernova)?

**Comment by bjmcder** [comment]
@cindytsai Thanks for the detailed instructions! I'll give this a try and let you know how it goes.

The Core-Collapse example is sufficient for me, but others at the conference may be interested in trying out both problems. If I have one recommendation for the paper, it would be to point to a repo showing how to replicate those problems, and/or the simpler problem you described. I think that could help give people a better picture of how to integrate it into their codes.

Also, one minor thing I noticed when installing libyt is that I get a dynamic load error when I go to run GAMER with libyt support. Adding libyt to my LD_LIBRARY_PATH fixes this, but you might consider adding an -rpath option to future releases to automatically handle this.

**Comment by bjmcder** [comment]
@cindytsai I got the shock tube to work! For some reason the MPI command you gave me was aborting, but I was able to get the problem to execute successfully on my local machine just by doing `./gamer`. Very cool!

**Comment by cindytsai** [comment]
Hi @bjmcder , thanks for the advice!

> The Core-Collapse example is sufficient for me, but others at the conference may be interested in trying out both problems. If I have one recommendation for the paper, it would be to point to a repo showing how to replicate those problems.

If it is for people at the conference to try out the problems, maybe I can provide another test problem ([Plummer](https://github.com/gamer-project/gamer/tree/main/example/test_problem/Hydro/Plummer)) that is much more easier to setup and can well illustrate `libyt`. It is a 3D problem, and it contains field data and particle data.
Because both Fuzzy Dark Matter (FDM) and Core-Collapse Supernova (CCSN) simulations are ongoing projects in GAMER and have not yet been merged into GAMER main branch, and both of them require loading a large GAMER snapshot for restart (116 GB for FDM and 19 GB for CCSN), I'm not sure if this is a good idea for the audience. But I think it is ok to share how to set it up with you. 

> you might consider adding an -rpath option to future releases to automatically handle this.

Thanks for pointing out! This is fixed in this [PR](https://github.com/yt-project/libyt/pull/85) and will be merged after the tests are done.

**Comment by bjmcder** [comment]
@cindytsai Good point, Plummer is probably a good balance then. Once I figure out the best way to provide my minor edits to the text, I'll post that here. A branch off of this PR maybe?

**Comment by cindytsai** [comment]
@bjmcder OK!
And just to let you know that we have moved the repo from `calab-ntu/libyt` to `yt-project/libyt`. I have pushed the commit for updating the link in the proceedings.

**Comment by mepa** [comment]
Hey @ktzhao! A friendly reminder that your initial review is due Friday, June 23rd.

**Comment by ktzhao** [comment]
@mepa Thank you for the reminder. 
@cindytsai This paper is very well written and easy to understand.
I notice that the documents(https://yt-project.github.io/libyt/libytAPI)  are not complete, lots of todos. Although that probably doesn't affect this paper. Documents would be very helpful for anyone interested in libyt , will you finish it sooner?

**Comment by cindytsai** [comment]
Hi @ktzhao , thanks for the advice. I am working on that and will get it done sooner.

**Comment by mepa** [comment]
@scoobies mark pending comment

**Comment by deniederhut** [comment]
Hi @cindytsai ! Have you had a chance to respond to the reviewer comments?

**Comment by cindytsai** [comment]
Hi @deniederhut, yes, I definitely will and sorry I forgot to update it here.

---

Hi @bjmcder, I have updated the GAMER doc [here](https://github.com/gamer-project/gamer/wiki/In-Situ-Python-Analysis#quick-demos) for people who want to test run `libyt` in GAMER, but I'm not sure should I also include this in the paper. Thanks!

---

Hi @ktzhao, I have completed libyt [docs](https://yt-project.github.io/libyt/). Thanks!

**Comment by mepa** [comment]
Thanks, @cindytsai!

@bjmcder and @ktzhao - how are you feeling about the updates from the author?

**Comment by bjmcder** [comment]
@mepa I'm good!

**Comment by ktzhao** [comment]
@mepa Looks good. I think it is ready to be published.
@cindytsai Thank you for accepting my suggestion. Enjoy the conference and good luck!

**Comment by mepa** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0067-0049/192/1/9 is OK
- 10.1088/0067-0049/211/2/19 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1093/mnras/sty2586 is OK
- 10.1038/nphys2996 is OK
- 10.1103/PhysRevLett.113.261302 is OK
- 10.1086/588755 is OK
- 10.1088/0004-637X/774/1/17 is OK
- 10.1103/PhysRevLett.85.1158 is OK
- 10.1103/PhysRevE.57.4150 is OK
- 10.1088/1475-7516/2021/01/011 is OK
- 10.1016/j.physrep.2016.06.005 is OK
- 10.3847/1538-4357/aaa893 is OK
- 10.1086/466517 is OK
- 10.1088/0004-637X/765/1/29 is OK
- 10.1109/LDAV.2011.6092322 is OK
- 10.1093/mnras/250.3.581 is OK
- 10.1086/317361 is OK
- 10.1051/0004-6361:20011817 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.2514/6.2003-3559 may be a valid DOI for title: Upwind and high-resolution methods for compressible flow: From donor cell to residual-distribution schemes

INVALID DOIs

- https://doi.org/10.1016/0021-9991(84)90143-8 is INVALID because of 'https://doi.org/' prefix
```

**Comment by mepa** [comment]
Hey @cindytsai, could you please check and resolve the MISSING and INVALID DOIs marked by scoobies above?

**Comment by cindytsai** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0067-0049/192/1/9 is OK
- 10.1088/0067-0049/211/2/19 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1093/mnras/sty2586 is OK
- 10.1038/nphys2996 is OK
- 10.1103/PhysRevLett.113.261302 is OK
- 10.1086/588755 is OK
- 10.1088/0004-637X/774/1/17 is OK
- 10.1103/PhysRevLett.85.1158 is OK
- 10.1103/PhysRevE.57.4150 is OK
- 10.1088/1475-7516/2021/01/011 is OK
- 10.1016/j.physrep.2016.06.005 is OK
- 10.3847/1538-4357/aaa893 is OK
- 10.1086/466517 is OK
- 10.1088/0004-637X/765/1/29 is OK
- 10.1109/LDAV.2011.6092322 is OK
- 10.1016/0021-9991(84)90143-8 is OK
- 10.1093/mnras/250.3.581 is OK
- 10.2514/6.2003-3559 is OK
- 10.1086/317361 is OK
- 10.1051/0004-6361:20011817 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cindytsai** [comment]
Hi @mepa , I have fixed the DOIs and other typos.

**Comment by mepa** [comment]
@scoobies mark ready

**Review by deniederhut — APPROVED** [review]
Thanks @ktzhao and @bjmcder for your help getting this paper ready for publication! And thanks @ktzhao for joining us at SciPy this year!

thank-you-gif-3-2494169499

**Pull request merged**
