### PR TITLE
Mention inline figures expectation in README

### PR DESCRIPTION
**Pull request by mpacer**

### CODE REVIEW

**Comment by mpacer** [comment]
@katyhuff @dalippa @deniederhut Is that text clear?

**Comment by mpacer** [comment]
Closes #271.

**Comment by deniederhut** [comment]
Thanks for clarifying this! I might be a little more explicit and say something like "figures and tables should be positioned inline, close to their explanatory text".

**Comment by mpacer** [comment]
Thank you for the suggestion. Done.

**Comment by deniederhut** [comment]
👍

**Comment by deniederhut** [comment]
It looks like the template paper has all of the figures and tables listed at the end -- for next year, this might be a thing we want to update.

**Comment by mpacer** [comment]
Not all of the images are placed at the end, only those that were too large to put in a per column format

image

However, I **do** need to think more about how to handle images that won't fit in a single column.

**Comment by deniederhut** [comment]
Well, this is definitely an improvement for now.

**Pull request merged**
