### PR TITLE
Poster: Likeness poster SciPy 2022

### PR DESCRIPTION
**Pull request by jGaboardi**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:  

cc @jvtcl

xref #733

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by jGaboardi** [comment]
@deniederhut If you have a chance, can you let me know if I did this poster PR correctly?

**Comment by deniederhut** [comment]
Haha it might be a couple of days before I have the bandwidth, but yes I will take a look!

**Comment by jGaboardi** [comment]
> Haha it might be a couple of days before I have the bandwidth, but yes I will take a look!

Thanks and no rush!

**Review by deniederhut — APPROVED** [review]

**Pull request merged**
