### PR TITLE
Poster: Kiwi tool

### PR DESCRIPTION
**Pull request by n33lima**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
Whoa that's a whole lotta commits and changed files. @n33lima it looks like you've accidentally pulled in the 2021 branch? Can you rebase your changes on 2022?

**Review by deniederhut — CHANGES_REQUESTED** [review]
There should only be the one commit here with the slides and the info.json file in it

**Comment by n33lima** [comment]
@deniederhut I didn't understand what was going on but I knew something was wrong. I'm sorry about this. I'll fix it ASAP

**Comment by n33lima** [comment]
@deniederhut I didn't know how to fix this PR so I made another one called 'Kiwi tool: Redo' That one has only the needed files and nothing else. I can close and delete this PR if that is ok. Please let me know.

**Comment by deniederhut** [comment]
Closing in favor of https://github.com/scipy-conference/scipy_proceedings/pull/774

**Pull request closed without merging**
