### PR TITLE
Paper: Pydra - a dataflow engine

### PR DESCRIPTION
**Pull request by djarecka**
SUBMISSION: 249
TITLE: Pydra - a flexible and lightweight dataflow engine for scientific analyses

PDF of the paper can be seen [here](http://procbuild.scipy.org/download/nipype-pydra_paper)

### CODE REVIEW

**Comment by calvinmccarter** [comment]
Hello @djarecka @satra @nicolocin ! I'll be reviewing your paper.

I'll read the paper more thoroughly, but an initial question I have is how Pydra compares to Snakemake and Luigi in terms of capabilities and use-cases.

**Comment by djarecka** [comment]
@calvinmccarter - thank you for reviewing our paper, we're looking forward to your feedback!

I’ve prepared a simple table that presents the comparison between Snakemake, Luigi and Pydra. Please note, that this is not meant to be an exhaustive comparison, I focused on the key features in Pydra and whether/how they are supported in Snakemake and Luigi. I’m not very familiar with the tools, so I welcome any feedback and will also ask people from the community to comment on that. 


|  Features / Support for:     | SnakeMake           | Luigi                     | Pydra                    |                
| --------------------- | ---------------------- | --------------------- | ---------------------- |
| Language / API |  Snakemake files to specify `rules`, uses custom syntax with support for embedded Python | Python, tasks - class-like object (with output, requires, run methods) |  Python, functional-like syntax|
|  Python Function | SnakeMake file + python script, or python code can be in the `run` field in the Snakemake file | part of the task’s   `run` method | Pydra’s decorator transform any function to task  |
| Shell commands | direct support, flexible command syntax, support for wildcard in input fields | no direct support | direct support (special class), flexible input/output specification, allow for wildcard, use `attr` classes (support for metadata, e.g. default values, type, etc., type checking in the future) | 
| Splitting/Mapping and combining/reducing concept | `rule` has support for splitter for multiple variables  by using arbitrary python function to generate the input  | support for pyspark and its map-reduce concept (single task level) | **extended map-reduce concept over graphs (`splitter` treated as a attribute that can be modified through the Workflow)**, support for nested dataflow |
| Workflow |  support for explicit connection, allows for named multiple output |  explicit connections in requires method, no support for named and multiple output | **Support for nested workflows**,  explicit connection, allows for named multiple output |
| Global Caching | full support for `rule`s  | no support (?) | full support for Tasks, tasks with splitting/mapping can extend input list without need to recompute all cases |
| Encapsulated environments | support for conda environment and Singularity | (?) | support for Docker and Singularity |
| Dependencies installed by PIP | appdirs-1.4.4 attrs-19.3.0 chardet-3.0.4 configargparse-1.2.3 datrie-0.8.2 decorator-4.4.2 docutils-0.16 gitdb-4.0.5 gitpython-3.1.3 idna-2.9 ipython-genutils-0.2.0 jsonschema-3.2.0 jupyter-core-4.6.3 nbformat-5.0.7 psutil-5.7.0 pyrsistent-0.16.0 pyyaml-5.3.1 ratelimiter-1.2.0.post0 requests-2.23.0 six-1.15.0 smmap-3.0.4 toposort-1.5 traitlets-4.3.3 urllib3-1.25.9 wrapt-1.12.1 | docutils-0.16 lockfile-0.12.2 python-daemon-2.2.4 python-dateutil-2.8.1 six-1.15.0 tornado-5.1.1 | attrs-19.3.0 chardet-3.0.4 ci-info-0.2.0 cloudpickle-1.4.1 etelemetry-0.2.1 filelock-3.0.12 idna-2.9 requests-2.23.0 urllib3-1.25.9|

**Comment by djarecka** [comment]
@tashrifbillah - hey, that's the table I've told you about. If you can comment on Luigi (or other things), that would be great

**Comment by tashrifbillah** [comment]
> 

Workflow | support for explicit connection, allows for named multiple output | explicit connections in requires method, no support for named and multiple output | Support for nested workflows, explicit connection, allows for named multiple output
-- | -- | -- | --


Luigi supports the same features you noted for Snakemake and Pydra. If I understood the `named and multiple outputs` term correctly, see [`named and multiple outputs`](https://github.com/pnlbwh/luigi-pnlpipe/blob/diag-cte/workflows/dwi_pipe.py#L55) in my pipeline.

**Comment by tashrifbillah** [comment]
> 

Dependencies installed by PIP | appdirs-1.4.4 attrs-19.3.0 chardet-3.0.4 configargparse-1.2.3 datrie-0.8.2 decorator-4.4.2 docutils-0.16 gitdb-4.0.5 gitpython-3.1.3 idna-2.9 ipython-genutils-0.2.0 jsonschema-3.2.0 jupyter-core-4.6.3 nbformat-5.0.7 psutil-5.7.0 pyrsistent-0.16.0 pyyaml-5.3.1 ratelimiter-1.2.0.post0 requests-2.23.0 six-1.15.0 smmap-3.0.4 toposort-1.5 traitlets-4.3.3 urllib3-1.25.9 wrapt-1.12.1 | docutils-0.16 lockfile-0.12.2 python-daemon-2.2.4 python-dateutil-2.8.1 six-1.15.0 tornado-5.1.1 | attrs-19.3.0 chardet-3.0.4 ci-info-0.2.0 cloudpickle-1.4.1 etelemetry-0.2.1 filelock-3.0.12 idna-2.9 requests-2.23.0 urllib3-1.25.9
-- | -- | -- | --

I think a significant dependency has been missed for Luigi. It is probably not in `requirements` file but essential for seeing task history on the Luigi web visualizer-- `sqlalchemy`

**Comment by tashrifbillah** [comment]
> 

Encapsulated environments | support for conda environment and Singularity | (?) | support for Docker and Singularity
-- | -- | -- | --


Luigi has built-in `hadoop` support.

**Comment by tashrifbillah** [comment]
> 

Shell commands | direct support, flexible command syntax, support for wildcard in input fields | no direct support | direct support (special class), flexible input/output specification, allow for wildcard, use attr classes (support for metadata, e.g. default values, type, etc., type checking in the future)
-- | -- | -- | --


Let's say you want to run `antsRegistration` as part of a Luigi task. Then, you will write a wrapper around the command line executable inside the task. I believe this requirement is the same for any other pipeline building tool i.e. nipype. So, I don't think this row can be used to demean Luigi.

**Comment by tashrifbillah** [comment]
> 
Python Function | SnakeMake file + python script, or python code can be in the run field in the Snakemake file | part of the task’s run method | Pydra’s decorator transform any function to task
-- | -- | -- | --


The function does not have to be part of a particular task's run method. It can be global to the module where the task is written or even can reside in a different module where the task is not written.

**Comment by tashrifbillah** [comment]
Unrelated to the discussion, I moved from `nipype` to Luigi mainly because nipype definition of node around a function required all imports and variables to be local to that function while Luigi didn't. To satisfy that limitation and write pipeline joining several long-standing scripts we have, I would need to rewrite those scripts-- an option not viable for us in terms of time required and reliability of the new ones. 

If Pydra has improved upon that design, I think that would make a good comparison against Luigi.

**Comment by tashrifbillah** [comment]
In any case, feel free to talk a look at my pipelines [here](https://github.com/pnlbwh/luigi-pnlpipe/tree/diag-cte/workflows) to come up with more comparisons.

**Comment by djarecka** [comment]
@tashrifbillah - thanks so much for your comments on the table! will update

**Comment by deniederhut** [comment]
Hey @djarecka  ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

**Comment by deniederhut** [comment]
Hi @calvinmccarter ! Were there other suggestions you had for this submission? Or is everything good to go?

**Comment by calvinmccarter** [comment]
@deniederhut -- sorry for the late reply! 

Overall, I think everything is looking great and ready to go! One additional suggestion I had is that, space permitting, it might be nice to discuss how pydra deals with failed tasks. 

- a brief discussion of current debugging support, or if it's part of future development plans
- if it's possible (and I assume this is the case at least at the workflow level, since they're hashable?) to re-run due to a failed task while reusing all other computations.

**Comment by djarecka** [comment]
@calvinmccarter - thank you for your review. Answering your questions:
- We are indeed working on better support of error tracking and debugging support (it's not finished and that's why we didn't add this to the paper)
- yes, it's definitely possible to reuse tasks from previously run workflows, ee tried to explain it in the `Checksum and Global Cache` section, see [here](https://github.com/scipy-conference/scipy_proceedings/pull/573/files#diff-61ae8a7a00d9015219547efaf4e302abR596). But if you think it's not clear I can rewrite this part.

**Comment by calvinmccarter** [comment]
No editing is needed -- just wanted to double-check!

**Pull request merged**
