### PR TITLE
Slides for poliastro talk

### PR DESCRIPTION
**Pull request by astrojuanlu**
I have the slides in another repository, not sure if I should

1. Copy-paste everything here (in which case, I'd rather way until the talk is over because I'll likely make some last minute adjustments)
2. Add a git submodule
3. Add a link with a README file (what I did in this PR)

In any case, the `info.json` file is complete.

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
Hey @astrojuanlu ! We need a single file that represents your presentation that we can submit to an archiving service.

**Comment by astrojuanlu** [comment]
Thanks @deniederhut! For the case of an HTML slideshow like the one I used, would it be OK then if I submit a `.zip` with all the contents then?

**Comment by deniederhut** [comment]
Yup a zipfile is fine

**Comment by astrojuanlu** [comment]
Done!

**Comment by deniederhut** [comment]
Thanks!

**Review by deniederhut — APPROVED** [review]

**Pull request merged**
