### PR TITLE
Paper: aPhyloGeo-Covid: A web interface for phylogeographic analysis of SARS-CoV-2 variation using Neo4j and Snakemake

### PR DESCRIPTION
**Pull request by TahiriNadia**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

### CODE REVIEW

**Comment by deniederhut** [comment]
Screenshot 2023-05-12 at 1 51 16 PM

👀 that's a lot of files. Did you mean to commit your virtualenv?

**Comment by TahiriNadia** [comment]
> Screenshot 2023-05-12 at 1 51 16 PM
> 👀 that's a lot of files. Did you mean to commit your virtualenv?


Yes, very strange. I followed the procedure, but shouldn't the environment be excluded by the gitignore? I prepared the PR early because there are two of us working on it, and the account belongs to the research lab. Thanks @deniederhut.

**Comment by WanlinLi2021** [comment]
> Screenshot 2023-05-12 at 1 51 16 PM
> 👀 that's a lot of files. Did you mean to commit your virtualenv?

Dear Dillon,

I am writing to seek your guidance and assistance regarding the generation of an updated PDF file on the SciPy Proceedings Build Server. 

Specifically, I have noticed that I cannot build an updated PDF file successfully. It seems that there may be an issue that needs to be addressed before running the SciPy Proceedings Build Server. I would be grateful if you could provide me with any instructions, recommendations, or fixes that could help me overcome this obstacle.

Thank you in advance for your time and support. Your guidance will be invaluable to me.

**Comment by deniederhut** [comment]
Thanks for the ping -- we'll take a look

**Comment by deniederhut** [comment]
Okay so there are two issues here. One is that procbuild is grabbing the wrong paper to compile -- we'll have that fixed as soon as we can. The other issue is that your title, headings, and subheadings need to have their underline characters be as long as the heading content.

E.g. like this

```rst
Future directions
-----------------
```

I've confirmed that if you fix all your headings, your paper will compile locally.

**Review by cbcunc — CHANGES_REQUESTED** [review]
This PR cannot be merged for two reasons. One, your paper should be in it's own directory within the papers directory. Instead this PR attempts to overwrite one of the example paper directories, 00_bibderwalt. Second all your changes must be confined to your own paper directory. Instead this PR attempts to overwrite all 1,352 files in the entire scipy_proceedings repo. You should close this PR and start over. There have been updates to the scipy_proceedings code since you forked, so It is likely that your code replacement is downlevel and won't work anyway.

**Comment by TahiriNadia** [comment]
Thanks @deniederhut and @cbcunc for your quick answers. We will start over. So we will close the PR. Once again thanks.

**Comment by cbcunc** [comment]
https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors

**Pull request closed without merging**
