### PR TITLE
Fixed print statements in build_paper.py to be python 3 compatible

### PR DESCRIPTION
**Pull request by michaelpacer**
Added parens to the print statements so that it would be compatible with both python 3 and python 2.

### CODE REVIEW

**Comment by stefanv** [comment]
To make this compatible with Python 2, we also need

```
from __future__ import print_function
```
at the top of the file.

**Comment by michaelpacer** [comment]
I didn't realize that just by pushing that to my forked branch it would automatically add it to this pull request — but i guess that makes sense. 

But is that correct?

**Comment by michaelpacer** [comment]
Ok didn't realize beginning meant literally beginning.

**Comment by stefanv** [comment]
Thanks, @michaelpacer !

**Pull request merged**
