### PR TITLE
Paper christensen rapid application development - fix citation links

### PR DESCRIPTION
**Pull request by sdc50**
This original PR was already merged, but I noticed the citation links weren't formatted correctly.

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
@sdc50 thanks for catching these! It looks like those two references also have DOIs -- would you mind adding them following the formatting guidelines here? https://www.crossref.org/display-guidelines/

**Comment by deniederhut** [comment]
@sdc50 have you had a chance to add the missing DOIs?

**Comment by sdc50** [comment]
> @sdc50 have you had a chance to add the missing DOIs?

@deniederhut Sorry for the delay. I just pushed up the DOIs.

**Review by deniederhut — APPROVED** [review]

**Pull request merged**
