### PR TITLE
[Lightning] Renovate: Automated Dependency Management

### PR DESCRIPTION
**Pull request by paddyroddy**
Let me know if you want a PDF export.

_Editor_:  

_Reviewers_:

### CODE REVIEW

**Review by cbcunc — CHANGES_REQUESTED** [review]
@paddyroddy The presentation files themselves rather than just a link are required. We deposit them in the SciPy community account in Zenodo and then issue a DOI through Crossref.

**Comment by paddyroddy** [comment]
> @paddyroddy The presentation files themselves rather than just a link is required. We deposit them in the SciPy community account in Zenodo and then issue a DOI through Crossref.

Do you want the files to build the `quarto` or a PDF mimicking the presentation?

**Comment by cbcunc** [comment]
> Do you want the files to build the `quarto` or a PDF mimicking the presentation?

Either or preferably both.

**Comment by paddyroddy** [comment]
> Either or preferably both.

Have added both

**Review by mepa — APPROVED** [review]

**Comment by cbcunc** [comment]
@paddyroddy The PDF doesn't render correctly. It only shows half a page for each slide, probably because it is rendering in portrait instead of landscape.

**Comment by paddyroddy** [comment]
> @paddyroddy The PDF doesn't render correctly. It only shows half a page for each slide, probably because it is rendering in portrait instead of landscape.

My bad, fixed this. Thanks for spotting!

**Review by cbcunc — APPROVED** [review]

**Pull request merged**
