### PR TITLE
Paper: test paper

### PR DESCRIPTION
**Pull request by deniederhut**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: @deniederhut

*Reviewers*: @deniederhut

### CODE REVIEW

**Comment by deniederhut** [comment]
@scoobies help

**Comment by scoobies** [comment]
Hello @deniederhut, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Assign a user as the reviewer N of this submission (where N=1,2...)
@scoobies assign @username as reviewer 2

# Remove the user assigned as reviewer N of this submission (where N=1,2...)
@scoobies remove reviewer 2

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Send an invitation to a user to collaborate in the review
@scoobies invite @username

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

**Comment by deniederhut** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper deniederhut-tmp-test-paper scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by deniederhut** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"deniederhut-tmp-test-paper"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nFrom https://github.com/scipy-conference/scipy_proceedings\n   195a7c3..750ad71  2021       -> origin/2021\nUpdating 195a7c3..750ad71\nFast-forward\n README.md                                 | 18 ++++++++++++++----\n presentations/lightning/example/info.json |  8 ++++++--\n presentations/posters/example/info.json   | 20 ++++++++++++++------\n presentations/slides/example/info.json    |  8 ++++++--\n presentations/tools/example/info.json     |  8 ++++++--\n pull_request_template.md                  |  5 +++++\n review_criteria.md                        |  2 ++\n 7 files changed, 53 insertions(+), 16 deletions(-)\n[*] Check out paper repository...\nCloning into '/tmp/tmpqkve1u1m'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: dillon\n*** Warning: /tmp/tmpqkve1u1m/publisher/../output/dillon/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/deniederhut-tmp-test-paper.pdf", "build_status"=>"success", "build_timestamp"=>"26/05 02:06"}, "status"=>"success"}}

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by scoobies** [comment]
Checking the BibTeX entries failed with the following error: 
```
Couldn't find bibliography entry
```

**Comment by deniederhut** [comment]
@scoobies add @dniederhut as editor

**Comment by deniederhut** [comment]
@scoobies add @deniederhut as editor

**Comment by deniederhut** [comment]
@scoobies assign @deniederhut as editor

**Comment by scoobies** [comment]
Assigned! @deniederhut is now the editor

**Comment by deniederhut** [comment]
@scoobies add @deniederhut as reviewer

**Comment by deniederhut** [comment]
@scoobies add @deniederhut to reviewers

**Comment by scoobies** [comment]
@deniederhut added to the reviewers list!

**Comment by mepa** [comment]
@scoobies mark server fail

**Comment by mepa** [comment]
@scoobies mark server success

**Pull request closed without merging**
