### PR TITLE
Paper: Using Computational Thinking to Teach Mechanical Vibrations

### PR DESCRIPTION
**Pull request by moorepants**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by moorepants** [comment]
@ixjlyons FYI

**Comment by stefanv** [comment]
Thanks for submitting this paper to SciPy, and for taking an innovative approach to teaching mechanics!  I taught dynamics myself for a number of years, and appreciate the effort you put into illuminating this field to your students.

After a cursory reading of the paper, I have the following feedback:

1. The paper does not quite manage to convey the excitement of the course it represents.  Yes, there are code snippets, but no outputs or calculation results are shown.  One of the fun aspects of teaching mechanics is that you can show, either via real-world or computation experiments, things that we intuit due to personal experience.  Why not highlight an example like this, where code produces an exciting output?

2. I do not see mentions of prior or related works, or courses (could have missed that in the quick reading).  I'm thinking of projects such as http://www.pydy.org/, presented at previous SciPy conferences.

3. There is a lot of focus on not-very-novel setup procedures that are the same for many courses currently taught.  I understand that this is part of capturing the entire context of the course, but it can probably be cut back a bit without affecting the paper's message much.

**Comment by moorepants** [comment]
@stefanv Thanks! We'll work on some improvements.

**Comment by dalippa** [comment]
@moorepants @stefanv What is the status of the review/updates?

**Comment by moorepants** [comment]
I have not finished the edits due to being off work. I plan to work on it this coming week.

**Comment by deniederhut** [comment]
Hi @moorepants ! There hasn't been activity here in quite some time. Do you plan on addressing the reviewer comments?

**Comment by moorepants** [comment]
I was hoping to, but am dealing with some family medical issues and had to cancel going to SciPy. My co-author is presenting the paper though. What is the deadline for this proceedings to be done?

**Comment by deniederhut** [comment]
Technically last Thursday, but we've been giving unofficial extensions to authors who have been giving good faith efforts to get their changes in on time.

**Comment by moorepants** [comment]
I'm sorry I wasn't able to complete this. I'm closing the request. Thank you for your time.

**Comment by deniederhut** [comment]
Sorry to hear that things haven't been amazing. But I hope we will see you next year?

**Pull request closed without merging**
