### PR TITLE
Paper: tests the proceedings builder

### PR DESCRIPTION
**Pull request by katyhuff**
test test test

### CODE REVIEW

**Comment by stefanv** [comment]
Yay, where is it running?

**Comment by katyhuff** [comment]
It's not.
1) I just was testing it locally.
2) It's also not working when I test it locally either.

I've never used flask or buildbot before, so I haven't had a chance to
figure out how to serve it up like you have at your pythonanywhere domain.
However, please don't just jump in and do it for me though, I want to do
it, I just haven't gotten around to looking into how - I'm sure it's not
that hard, I just haven't had a chance to put any time into it. What you
saw was the first 5 minutes of my playing around with it.

On Mon, May 11, 2015 at 5:31 PM, Stefan van der Walt <
notifications@github.com> wrote:

> Yay, where is it running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/117#issuecomment-101081836>
> .
>



-- 
http://katyhuff.github.com

**Comment by stefanv** [comment]
Cool, feel free to ping me if you get stuck.  It *should* be as simple as just running it, and if it is not then it is broken.

**Comment by stefanv** [comment]
(I had too many problems on PythonAnywhere, so in the end I just ran it on another server I had access to.)

**Comment by katyhuff** [comment]
Yeah, I definitely ran it and saw your webapp pop up on my localhost8080.
However, it didn't seem to be successfully finding the pull request.
Locally, it looks as exactly as blank as stefan.pythonanywhere.com .


On Tue, May 12, 2015 at 11:21 AM, Stefan van der Walt <
notifications@github.com> wrote:

> Cool, feel free to ping me if you get stuck. It *should* be as simple as
> just running it, and if it is not then it is broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/117#issuecomment-101374127>
> .
>



-- 
http://katyhuff.github.com

**Pull request merged**
