### PR TITLE
Paper: pyMolDyn

### PR DESCRIPTION
**Pull request by IngoHeimbach**
Paper title:
    "pyMolDyn: Identification, structure, and properties of
    cavities in condensed matter and molecules"

### CODE REVIEW

**Comment by mpacer** [comment]
@IngoHeimbach could you modify the paper to include the figures inline rather than grouping them at the end?

**Comment by inchoate** [comment]
@IngoHeimbach 

**Summary and Notes**
The authors present an algorithm and software, _pyMolDyn_, to identify molecular cavities. Once identified, properties of those voids can be calculated as well. They detect cavities through a discretization of the unit cell and apply split and merge and marching cubes. The software also can provide high-resolution images and movies. 

Marching cubes has been used for a long time to calculate cavities. And, since it is not clearly stated in the text, I'm not sure where the novelty in the methods arise. If this is more of a software notice as opposed to an exposition of novel techniques, please advise (since I missed it).

The software was downloaded. I tried the sample XYZ file, but never was able to calculate or view the cavities. I set the resolution to `384` (and various other settings) and tried a surface-based calculation. No calculations completed nor were cavities shown. The UI didn't act exactly as the documentation indicates. 

**Requested Changes**
 * Please be consistent in placing citation references in the text. They should be placed in the sentence where appropriate or at the end **before the full stop**. You place them within and outside various sentences all throughout the text.
 * Please double check your numbers. You mention a common 2.5 A cutoff and then later, 2.8 A cutoff.
  * Missing full stop before the text, "The default colors.." on page 3.
  * The "Concluding Remarks" section duplicates text very close by. I suggest reworking them to be more concise. I know you're told to "tell the reader what you just told the reader" -- but I think improving this section would improve the paper significantly.
  * The authors seem to leave out any comparison to current techniques or validation. How do you know you calculated the right values? An explicit example with tables or images compared to established software would improve this paper.

**Recommendation**
While I couldn't get the software to work, I'm reasonably confident that it does or will soon (I reviewed some of the code). When finished, this looks like a useful tool for the community which is why I recommend to accept it with revisions.

**Execution Logs**
Hopefully this helps you debug the issues on my MacBook Pro:
```
17:28 $ /Applications/pyMolDyn.app/Contents/MacOS/__startup__.sh 
Traceback (most recent call last):
  File "../Resources/conda_env/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Applications/pyMolDyn.app/Contents/Resources/conda_env/lib/python2.7/site-packages/conda/cli/main.py", line 154, in main
    activate.main()
  File "/Applications/pyMolDyn.app/Contents/Resources/conda_env/lib/python2.7/site-packages/conda/cli/activate.py", line 179, in main
    from conda.base.context import context
  File "/Applications/pyMolDyn.app/Contents/Resources/conda_env/lib/python2.7/site-packages/conda/base/context.py", line 20, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "/Applications/pyMolDyn.app/Contents/Resources/conda_env/lib/python2.7/site-packages/conda/common/configuration.py", line 52, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named ruamel.yaml.comments
../Resources/conda_env/bin/activate: line 92: [: =: unary operator expected
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

**Comment by IngoHeimbach** [comment]
@inchoate Thanks for your detailed review. I am not at the office until the end of the month but in July I can fix the issues you have found.

**Comment by govarguz** [comment]
**@IngoHeimbach**

**Summary and Notes**
The authors present an algorithm, pyMolDyn, to identify molecular cavities. Such algorithm discretizes the unit cells and create a split and merge scheme to identify 3 types of cavities. On top of that it has an embedded visualization that uses the marching cubes algorithm. 

In haven't downloaded the software since I saw the program running during the Euroscipy2016. Nonetheless for the paper I missed the algorithm description remarking the parts where you focused your development of PyMolDyn (eventually you could use a flowchart).

**Requested Changes**

I recommend addressing the following points before further rounds of publication:

**(1)** Add a figure with a "flowchart-like" illustration which shows the adaptations to the algorithms you have used and the focus of your development. 

**(2)** Another important aspect is the comparison to some existing package tackling the same cavities identification. 

**(3)** As a guideline to the user I would also add another figure showing some simple benchmarks of cavity finding according to the resolution. In other words, Y axis (time to find cavities on a given system) and X axis (resolution 384 512...and so on).

**Recommendation**
I consider the article of importance to those with closely related research in the computational physics/ chemistry and material sciences. I recommend to accept the article with revisions.

**Comment by IngoHeimbach** [comment]
Thank you very much for the reviews and the positive feedback. We respond here to all the points raised.

@inchoate

1.  pyMolDyn uses the marching cubes algorithm mainly for the visualization of cavities. However, additional information about the grouping of cavity points is needed for calculating parameters such as the volume and the gyration tensor. Here we apply in addition the split-and-merge algorithm to segment individual cavities / cavity domains.

2.  I have installed the latest pyMolDyn version (0.9.7) on a fresh macOS Sierra with the latest Apple updates. I could reproduce the exception in your execution log, but the GUI was still functional and I could calculate cavities for the ``AgGeS-BOX.xyz`` sample file. I would need more information about the way the GUI was used to reproduce the behavior mentioned.

3.  Citations are now placed before periods and commas and are consistent throughout.

4.  A cutoff radius of 2.8 Å is suitable for alloys of Ge/Sb/Te and Ag/In/Sb/Te that we used in previous work and is the default cutoff radius. The sample file referenced in the article (``AgGeS-BOX.xyz``) needs a smaller cutoff radius because of the small sulfur atoms. With a cutoff radius of 2.8 Å, there are no cavities.

5.  The *Concluding Remarks* section has been shortened and now includes a benchmark.

6.  Freely available codes do not calculate cavities for the definitions used here. However, pyMolDyn was developed as a replacement for and a major extension of a Fortran code originally developed in [AJ07]. The results of the two codes have been compared where possible throughout the development of pyMolDyn.

@govarguz

1.  The single algorithm steps are illustrated in the video linked below the title. The video is now cited in the paper.

2.  See ``6.`` above.

3.  A benchmark (TABLE 1) has been added to the *Concluding Remarks* section. We prefer a table to a figure, since the range of times is large.

We have taken the opportunity to make a number of minor corrections.

**Comment by inchoate** [comment]
@IngoHeimbach 
  * Thanks for the changes to the text.
  * The software works fine with a smaller radius. I'm attaching the *ready* label as described in the instructions.

**Comments you may feel free to ignore**:
I was the Product Manager for PyMOL for 5 years, supporting customers worldwide. Here are a few small suggestions to potentially increase adoption (if that's your goal):
    * Compare this very carefully against other tools. Share those results. People will want to know why they should use your software.
    * Create and ship with your product a small test suite of molecular systems to establish and prove validity of future code changes. Customers/users who will come to rely on this will run those tests prior to using each release to ensure stability in your code/changes. Maybe even include that into a continuous integration build step.
    * Modularize the code so that this can be run from an API. Then, your users are free to use this when and how they want.

Good luck!

**Comment by govarguz** [comment]
@IngoHeimbach

- I have read your latest version of the proceedings Ms.
- @proceedings / @scipy-proceedings-bot the Authors have addressed the points of the revision I have raised. Thereby I would recommend to accept the article.

Best,
Horacio A. Vargas Guzman

**Comment by mpacer** [comment]
Merging this for the purposes of having the camera-ready proceedings available for the main conference. Further changes (if necessary) should be made as a new PR.

**Pull request merged**
