### PR TITLE
Collect author ORCIDs for presentations

### PR DESCRIPTION
**Pull request by stargaser**
As a last part of implementing #355, add information to the example JSON files for presentations.

### CODE REVIEW

**Comment by stargaser** [comment]
Maybe we'll want to collect author email addresses too?

**Comment by deniederhut** [comment]
This is exactly what I was imagining -- thanks for working on this! As discussed on the call right this very second, we might want to add affiliation as an option in the author field too

**Comment by stargaser** [comment]
I've added the affiliations. For the example of a poster by @deniederhut , I used the affiliation on the poster and not the current one.

**Review by deniederhut — APPROVED** [review]
Thanks for doing this work David!

**Pull request merged**
