### PR TITLE
Slides: Keynote Particles, People, and Pull Requests

### PR DESCRIPTION
**Pull request by achabotl**
Submitting July 12, 2024 keynote slides on behalf of Kyle Cranmer, with his permission.

### CODE REVIEW

**Comment by achabotl** [comment]
Closing in favor of a different PR I'll make in a moment. I reduced the original PDF's size using the command below and I feel bad about it. I shouldn't mess with other people's slides.

```
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=output_printer.pdf INPUT.PDF
```

**Comment by achabotl** [comment]
@cbcunc Question about PDF size for slides. The slides in this PR are ~50 MB. The original slides, which I tried to push as a separate PR were 180 MB. Pushing them failed with the errors below. I guess I should just re-open this PR then?

```
emote: error: Trace: d2ff259fd9eee074d6a8a4d27a784019ae25dee51f658c838736d1217403136c
remote: error: See https://gh.io/lfs for more information.
remote: error: File presentations/slides/cranmer-kyle/Cranmer-Kyle-Keynote-SciPy-2024.pdf is 182.21 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:scipy-conference/scipy_proceedings.git
```

**Comment by achabotl** [comment]
Re-opening to ensure this issue gets looked at eventually.

**Comment by mepa** [comment]
Hi @achabotl! I think reducing the PDF size was a good call since Zenodo, where the file will be uploaded to, allows a default max of 50GB: https://about.zenodo.org/policies/. I'll flag this for discussion with the rest of the proceedings committee, also.
> "Volume and size limitations: Total files size limit per record is 50GB. Higher quotas can be requested and granted on a case-by-case basis."

**Comment by mepa** [comment]
I'll also note that the file uploaded to Zenodo can be .zip or any other format, too.

**Comment by mepa** [comment]
> Hi @achabotl! I think reducing the PDF size was a good call since Zenodo, where the file will be uploaded to, allows a default max of 50GB: https://about.zenodo.org/policies/. I'll flag this for discussion with the rest of the proceedings committee, also.
> 
> > "Volume and size limitations: Total files size limit per record is 50GB. Higher quotas can be requested and granted on a case-by-case basis."

@achabotl, I just noticed that the Zenodo file size limit is 50GB (not 50MB, which is what I had in mind when I made the above comment 🤦).

If you could please share the original 182MB file with the Proceedings Committee separately then we will upload the original to Zenodo and keep the reduced-size file here in GitHub.

**Comment by achabotl** [comment]
@mepa You can download the original PDF at this link: https://www.dropbox.com/s/jj9tqvsfbp3shli/SciPy-2024.pdf?e=1

**Review by mepa — APPROVED** [review]

**Pull request merged**
