### PR TITLE
Paper: pyDEM: Global Digital Elevation Model Analysis (Ueckermann)

### PR DESCRIPTION
**Pull request by mpu-creare**
Conference paper for pyDEM talk. 

[Edit by jaberg] http://nipy.bic.berkeley.edu:5000/download/29

### CODE REVIEW

**Comment by ashtonmsu** [comment]
This review follows the suggested review criteria (https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md)

1. Written Quality
The paper is written in mostly sound technical English. The authors avoid jargon, and the paper is clearly organized. Some fixes are indicated below:
Typos:
Second paragraph in the abstract is in the body font and size - fix.
"efficiently computess the UCA" - "computes"
"drains preferably along those pixels" - "preferentially"

2. Technical Content

Intro - please develop a better working definition of aspect and TWI so that non-geomorph and hydro readers will understand why they are useful.

The paper does an excellent job of verifying the implemented algorithms using synthetic and (large) actual DEMs. More detail (e.g., summary stats) on similarity to the reference implementation (taudem) might be helpful, although I understand that results will differ.

3. Novelty & Impact
A longstanding issue in spatial parallelization is flow accumulation, as flow may have to be passed back and forth between spatial 'chunks' of terrain many times. A core contribution of this paper is developing a robust solution. It appears capable of efficiently handling this issue. Validation with various synthetic examples illustrates this and other algorithm properties very well.

The paper mentions that pyDEM was also used on a 3 arc second global DEM (SRTM?). However no results are reported. This would be of interest, since there are gaps/holes in SRTM as well as significant oceanic elements.


4. Verifiability
Code is linked and available on Github.

5. Other
Ok.

6. Length
Fine.

7. Figures and Code Snippets
Figures are fine. Code snippets are readable.

**Comment by mpu-creare** [comment]
1.  Thanks for catching those typos! 
2. 
    * Added a few sentences to explain working knowledge of aspect/twi. Thanks, good suggestion there. 
    * I also added a more direct comparison to the reference implementation tauDEM. There was already a direct comparison for the spiral case, although it was not explicitly discussed. The new comparison also addresses the issues of non-uniform grid coordinates which I did not discuss in the original submission (I thought the page limit was 7). 
    * I also added the result of the global SRTM calculation to the inset of Fig 10. The other zoom levels do not give much more information.

**Comment by aashish24** [comment]
@mpu-creare I have stated my review and post my notes here soon.

**Comment by ashtonmsu** [comment]
Looks very good. I appreciated learning more about the (small) differences in results between your approach and tauDEM.

**Comment by mpu-creare** [comment]
Thanks @ashtonmsu, glad you enjoyed it. :)

**Comment by aashish24** [comment]
## Written Quality
* Written quality is very good. I was impressed with authors style. 
* I also enjoyed reading this paper.
* Not unusual but I find it interesting the way authors used the locking mechanism
* Minor improvement request: May this could be reworded (could be improved a bit):
We will then demonstrate pyDEM on a few test cases, and some real data
* It would have been nice to see some performance graph specifically for parallel processing

**Comment by aashish24** [comment]
### Technical Content

1. Novelty The paper tackles the issue of global hydrological terrain analysis specially when the data is too large to fit into the memory. This use case is very relevant in the era of "data intensive analytics" or "big data". Authors use of file-based locking mechanism for coordination purposes is interesting and successful. Demonstration with real dataset is valuable. It would have been nice to some numbers from weak or strong scaling in parallel context. 

2. Verifiability
Code exists on Github. The link provided was correct.

3. Other
Ok.

4. Length
Length seems fine. 

5. Figures and Code Snippets
Figure had good resolution. Code snippet was readable.

**Comment by mpu-creare** [comment]
Thanks for the review @aashish24 . I reworded the sentence, and I agree that it's better. 

I also agree that a performance graph on the parallel scaling would be nice to have... but I don't think I have the time for that at the moment. I will certainly try to get that done in the future and add it to the pydem github page. 

I also updated some of the figures to make them more clear. In particular, I inverted the TWI colorbar on a few graphs to match the colorbar for the CONUS results (slight oversight on my part). Now wetter regions are 'bluer' which makes more sense to my brain at least.

**Comment by aashish24** [comment]
thanks @mpu-creare for taking care of a minor request quickly. I agree performance graph may take some time and as you said you can always add it to the web-site. I think that will clearly demonstrate the effectiveness of the architecture and possibly algorithm as well. This paper is very well written and has lot of details. I certainly enjoyed reading the paper and appreciated the work that has been done.

**Comment by mpu-creare** [comment]
@aashish24 Agreed. I will add a performance graph later. Thanks again for the review, it's always nice when someone actually reads one of my papers. :)

@katyhuff @jaberg I think the paper is ready to be merged, I believe the reviewers would agree.

**Comment by aashish24** [comment]
thanks @mpu-creare for the excellent work. I am sure I will use in my work. 

@katyhuff I agree, this paper is ready to be merged.

**Pull request merged**
