### PR TITLE
Paper: atoMEC: an open-source average-atom Python code

### PR DESCRIPTION
**Pull request by timcallow**
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*: @deniederhut

*Reviewers*: @ktzhao, @jyhmiinlin

### CODE REVIEW

**Comment by scoobies** [comment]
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

**Comment by deniederhut** [comment]
@scoobies mark paper

**Comment by deniederhut** [comment]
@scoobies build status

**Comment by scoobies** [comment]
{"timcallow-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpyqiiouf3'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: Timothy_Callow\n*** Warning: /tmp/tmpyqiiouf3/publisher/../output/Timothy_Callow/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/timcallow-2022.pdf", "build_status"=>"success", "build_timestamp"=>"23/05 16:10"}, "status"=>"success"}}

**Comment by deniederhut** [comment]
@scoobies mark needs review

**Comment by deniederhut** [comment]
@scoobies assign @deniederhut as editor

**Comment by scoobies** [comment]
Assigned! @deniederhut is now the editor

**Comment by timcallow** [comment]
@deniederhut are there any restrictions regarding uploading these papers to the arxiv?

**Comment by deniederhut** [comment]
Nope, no restrictions.

**Comment by deniederhut** [comment]
@scoobies add @ktzhao to reviewers

**Comment by scoobies** [comment]
@ktzhao added to the reviewers list!

**Comment by deniederhut** [comment]
@scoobies add @jyhmiinlin to reviewers

**Comment by scoobies** [comment]
@jyhmiinlin added to the reviewers list!

**Comment by deniederhut** [comment]
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

**Comment by jyhmiinlin** [comment]
Dear Dillon,

Thanks for the update.

Just a question: How do I submit the review-result.html and the annotated
pdf? should I git add files, commit a change, and push it to the PR? Am I
right?

Thanks!

Jyh-Miin Lin, MD, PhD
IEEE senior member
Alumnus, Robinson College, University of Cambridge

Dillon Niederhut ***@***.***> 於 2022年6月7日 週二 上午10:46寫道：

**Comment by jyhmiinlin** [comment]
Just a technical question: 
How do I submit the review-result.html and the annotated pdf? should I git add files, commit a change, and push it to the PR? 
Thanks,

**Comment by ktzhao** [comment]
Thank you for inviting me to review this paper.
It is a great job to develop the python-based average-atom code atoMEC.
However, the English in this paper is not of publication quality, contain numerous grammatical errors. Please carefully proof-read spell check to correct those errors.

**Comment by jyhmiinlin** [comment]
Reviewer:Jyh-Miin Lin

Department/Center/Division: Alumnus, Robinson College

Institution/University/Company: University of Cambridge

Field of interest / expertise: Python for MRI, PyNUFFT

Country: UK / Taiwan


Article reviewed: atoMEC

Thank you for contributing the package to Scipy proceedings. The paper is well-written. As a medical imaging researcher, I cannot find obvious errors in Equations. Please find domain experts to check the equations.

There are some questions for the paper:

1. Equation (1): I suppose that quantum numbers in superscripts and subscripts do not indicate the Einstein summation convention. Is it possible to represent m,n,l in a way, unlike the Einstein summation convention? For example, (m,n,l) with commas.

2. Equation (3): Can r^{>}(x) be represented as max(r,x)? r^{>}(x) seems very complex for people from other fields (like me).

3. Fig. 2 is excellent but I am not sure I understand this sentence: "Some liberties are taken with the code in the figure in order to improve readability." I guess the figure may not connect left to right exactly. Am I correct?

4. Page 5 "common" units -> SI units?


GENERAL EVALUATION
------------------

Please rate the paper using the following criteria (please use the abbreviation
to the right of the description)::

  below     doesn't meet standards for academic publication
  meets     meets or exceeds the standards for academic publication
  n/a       not applicable

- Quality of the approach: **meets**

- Quality of the writing: **meets**

- Quality of the figures/tables: **meets**


SPECIFIC EVALUATION
-------------------

For the following questions, please respond with 'yes' or 'no'.  If you
answer 'no',  please provide a brief, one- to two-sentence explanation.

- Is the code made publicly available and does the article sufficiently
  describe how to access it? **yes** We aim not to publish papers that essentially
  advertise proprietary software.  Therefore, if the code is not publicly
  available, please provide a one- to two- sentence response to each of the
  following questions:

  - Does the article focus on a topic other than the features
    of the software itself? 
  - Can the majority of statements made be externally validated
    (i.e., without the use of the software)? 
  - Is the information presented of interest to readers other than
    those at whom the software is aimed? 
  - Is there any other aspect of the article that would
    justify including it despite the fact that the code
    isn't available? 
  - Does the article discuss the reasons the software is closed?

- Does the article present the problem in an appropriate context? yes
  Specifically, does it:

  - explain why the problem is important, **yes**
  - describe in which situations it arises, **yes**
  - outline relevant previous work, **yes**
  - provide background information for non-experts **yes**

- Is the content of the paper accessible to a computational scientist
  with no specific knowledge in the given field? **yes**

- Does the paper describe a well-formulated scientific or technical
  achievement? **yes**

- Are the technical and scientific decisions well-motivated and
  clearly explained? **yes**

- Are the code examples (if any) sound, clear, and well-written? **yes**

- Is the paper factually correct? **n/a** Please find a domain expert to double check the equations.

- Is the language and grammar of sufficient quality? **yes**

- Are the conclusions justified? **yes**

- Is prior work properly and fully cited? **yes**

- Should any part of the article be shortened or expanded? **no** Please explain.

- In your view, is the paper fit for publication in the conference proceedings? **yes**
  Please suggest specific improvements and indicate whether you think the
  article needs a significant rewrite (rather than a minor revision).

**Comment by timcallow** [comment]
> Thank you for inviting me to review this paper. It is a great job to develop the python-based average-atom code atoMEC. However, the English in this paper is not of publication quality, contain numerous grammatical errors. Please carefully proof-read spell check to correct those errors.

@ktzhao Thanks for reviewing our paper.

In response to your comment, we have gone through the paper manually and with a spelling / grammar checking tool and corrected the errors that were found. If you think there are still some mistakes, please tell us specifically what these are and we will be happy to correct them.

**Comment by timcallow** [comment]
@scoobies help

**Comment by scoobies** [comment]
Hello @timcallow, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

**Comment by timcallow** [comment]
@scoobies build paper

**Comment by scoobies** [comment]
building paper...

**Comment by scoobies** [comment]
{"data"=>{"info"=>"Build for paper timcallow-2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

**Comment by timcallow** [comment]
@deniederhut My most recent commits (made after initial reviews) don't seem to be reflected in the latest [build](http://procbuild.scipy.org/) of the paper. Everything works ok locally so I'm not sure what the problem is.

**Comment by deniederhut** [comment]
@timcallow I see the Physics->physics change from line 62 in the rendered pdf. Does it show up if you hard refresh the page at https://procbuild.scipy.org/download/timcallow-2022?

**Comment by deniederhut** [comment]
@scoobies mark pending comment

**Comment by timcallow** [comment]
> @timcallow I see the Physics->physics change from line 62 in the rendered pdf. Does it show up if you hard refresh the page at https://procbuild.scipy.org/download/timcallow-2022?

@deniederhut Thanks, yes it seems to have updated now. Sorry, not sure why I wasn't seeing the updates before, maybe it just needed a bit more time.

**Comment by timcallow** [comment]
> Thank you for inviting me to review this paper. It is a great job to develop the python-based average-atom code atoMEC. However, the English in this paper is not of publication quality, contain numerous grammatical errors. Please carefully proof-read spell check to correct those errors.

@ktzhao Thanks for reviewing our paper.

In response to your comment, we've gone through the paper manually and with a spelling / grammar check tool, and corrected all the errors that we found. If you find there are still some mistakes, please tell us specifically what these are and we will happy to correct them.

**Comment by timcallow** [comment]
@jyhmiinlin Thanks for reviewing our paper.

In response to your comments:

> 1. Equation (1): I suppose that quantum numbers in superscripts and subscripts do not indicate the Einstein summation 
convention. Is it possible to represent m,n,l in a way, unlike the Einstein summation convention? For example, (m,n,l) with commas.

You're correct that these don't indicate the Einstein summation convention. We have used the notation that is common in our field, and adding commas (for example) might look strange. However, we have added a footnote to clarify that Einstein summation notation is not used here or elsewhere in the paper.

> 2. Equation (3): Can r^{>}(x) be represented as max(r,x)? r^{>}(x) seems very complex for people from other fields (like me).

Yes, we have made the suggested change.

> 3. Fig. 2 is excellent but I am not sure I understand this sentence: "Some liberties are taken with the code in the figure in order to improve readability." I guess the figure may not connect left to right exactly. Am I correct?

Agreed, this was a little unclear. The main thing is that the code snippets on the right hand column do not appear exactly as they do in the code, as some parameters for some functions are not shown or simplified (e.g. shown as an object where in the code they are a specific attribute of that object). There are additionally various intermediate steps in the code which are not shown in this figure, because they are not fundamental to understanding the main message. We have updated the paper with a more detailed explanation.

> 4. Page 5 "common" units -> SI units?

They are not necessarily SI units, but rather units which are commonly used by researchers in our field. We have clarified this in the updated paper.

**Comment by deniederhut** [comment]
> Sorry, not sure why I wasn't seeing the updates before, maybe it just needed a bit more time.

🤷‍♀️ probably goblins in the internet or something. Glad it's working now!

**Comment by deniederhut** [comment]
Hi @ktzhao and @jyhmiinlin! Do you feel that this paper is now ready for inclusion in the proceedings?

**Comment by jyhmiinlin** [comment]
Hi @timcallow, @deniederhut : Thank you for revising the papper. In a second review, I cannot find all typos but I have some concerns about the grammar. To achieve the highest standard for Scipy-proceedings, is it possible to ask a native English speaker to proofread the paper? 

1. Abstract: First sentence: Average-atom models are an important tool in studying matter... Would you consider changing the "an" and "tools" in the sentence? 
2. Introduction: unfeasiably expensive: unfeasibly expensive?

3. I also wonder if GPUs can help to accelerate the average-atom models and the ab-initio (first-principles) methods? Some discussions about the topic could be of interest. 

Thanks a lot. Overall I think this package is important for fusion calculations.

**Comment by deniederhut** [comment]
Thanks for the feedback! @timcallow do you have a friend who would be willing to do a read-through of the paper for grammatical help?

**Comment by timcallow** [comment]
@deniederhut Working on it. Hope to update the paper by EOD tomorrow (28.06)

**Comment by timcallow** [comment]
> Hi @timcallow, @deniederhut : Thank you for revising the papper. In a second review, I cannot find all typos but I have some concerns about the grammar. To achieve the highest standard for Scipy-proceedings, is it possible to ask a native English speaker to proofread the paper?
> 
> 1. Abstract: First sentence: Average-atom models are an important tool in studying matter... Would you consider changing the "an" and "tools" in the sentence?
> 2. Introduction: unfeasiably expensive: unfeasibly expensive?
> 3. I also wonder if GPUs can help to accelerate the average-atom models and the ab-initio (first-principles) methods? Some discussions about the topic could be of interest.
> 
> Thanks a lot. Overall I think this package is important for fusion calculations.

@jyhmiinlin (cc @deniederhut) Thanks for the additional feedback. I am actually a native English speaker, but of course I still make mistakes! I asked a friend (with experience in proof-reading / journalism) to take a second look which resulted in a few changes.

Regarding the specific questions:

1. I see your point, but I disagree with this one. The meaning of the sentence is to group average-atom models together, as a single entity, and say that they are an important tool, hence the use of the singular person. But if you still think this is wrong, I am open to changing it to what you suggest.
2. Thanks for spotting that - changed now.
3. Yes, great point. GPUs are getting more mainstream in ab-initio methods and are known to accelerate calculations. I've added a sentence in the introduction to acknowledge this, when we talk about methods which reduce the computational complexity of ab-initio calculations. Regarding average-atom models, I imagine it's true that GPUs could also help there. But average-atom calculations are already so fast relative to ab-initio methods that the focus is on making them more accurate, rather than more efficient. Therefore I think it's unlikely there will be much appetite to accelerate average-atom models with GPUs in the near future. So I restricted the mention of GPUs in the paper to ab initio models only.

**Comment by deniederhut** [comment]
> I am actually a native English speaker, but of course I still make mistakes!

Haha me too! Thanks for the updates, Tim.

@ktzhao and @jyhmiinlin -- how are you feeling after the last batch of revisions?

**Comment by jyhmiinlin** [comment]
> > I am actually a native English speaker, but of course I still make mistakes!

I am not native, and I am glad that there is an experienced writer who has helped us.
> 
> Haha me too! Thanks for the updates, Tim.
> 
> @ktzhao and @jyhmiinlin -- how are you feeling after the last batch of revisions?
I would have a look and get back to you.

**Comment by ktzhao** [comment]
Sorry for the delayed response. It looks better now. I think it is ready for the proceedings.

**Comment by deniederhut** [comment]
@scoobies check references

**Comment by scoobies** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK
- 10.1007/978-3-319-04912-0 is OK
- 10.1088/0953-4075/49/9/092001 is OK
- 10.1103/PhysRev.136.B864 is OK
- 10.1103/PhysRev.140.A1133 is OK
- 10.1103/RevModPhys.71.1253 is OK
- 10.1063/1.5143225 is OK
- 10.1103/PhysRevB.104.035120 is OK
- 10.1103/PhysRevLett.108.253002 is OK
- 10.1038/s41467-017-00839-3 is OK
- 10.1103/PhysRevB.97.115207 is OK
- 10.1103/PhysRevLett.111.106402 is OK
- 10.1103/PhysRevResearch.4.023055 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1103/PhysRevB.77.184201 is OK
- 10.1103/PhysRevA.43.3035 is OK
- 10.1007/978-94-011-3262-6_2 is OK
- 10.1103/PhysRevLett.107.015002 is OK
- 10.1103/PhysRevX.4.031004 is OK
- 10.1103/PhysRevE.104.025209 is OK
- 10.1103/PhysRevE.99.053201 is OK
- 10.1103/PhysRevE.89.023108 is OK
- 10.48550/ARXIV.2203.05863 is OK
- 10.1021/cr200107z is OK
- 10.1119/1.4748813 is OK
- 10.1103/PhysRevE.99.053201 is OK
- 10.1103/PhysRevLett.107.163001 is OK
- 10.5281/zenodo.5205719 is OK
- 10.1103/PhysRevB.102.224107 is OK

MISSING DOIs

- 10.1103/physrev.137.a1441 may be a valid DOI for title: Thermal properties of the inhomogenous electron gas

INVALID DOIs

- https://doi.org/10.1016/j.physrep.2018.04.001 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.softx.2017.11.002 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.hedp.2013.12.001 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.hedp.2016.04.001 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jcp.2013.05.005 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cpc.2011.03.010 is INVALID because of 'https://doi.org/' prefix
```

**Comment by deniederhut** [comment]
Most of these references have both a URL and a DOI -- could we standardize on having just the DOI for papers/articles/books, and reserving URLs for software that has no associated publication?

Screen Shot 2022-06-29 at 5 47 36 AM

**Comment by timcallow** [comment]
> Most of these references have both a URL and a DOI -- could we standardize on having just the DOI for papers/articles/books, and reserving URLs for software that has no associated publication?

I've removed URLs where there is a DOI

**Review by deniederhut — APPROVED** [review]
Thanks for making those changes Tim! And thanks to the reviewers for all your comments. I think this is good to go

**Comment by deniederhut** [comment]
@scoobies mark ready

**Pull request merged**
