### PR TITLE
[Issue 169] Copyright Holder Different Than Author

### PR DESCRIPTION
**Pull request by dalippa**
Added a copyright_holder tag that can be used to replace the authors' copyright with an author-defined one.

Sample usage would be:

:author: Joe Author
:email: joe@author.org

:copyright_holder: My Company, Inc.

### CODE REVIEW

**Comment by dalippa** [comment]
@katyhuff This resolves #169 .

**Comment by katyhuff** [comment]
This looks great to me @dalippa ! I'm going to merge it into both master and 2015. Thanks!! Once that's done, I'll restart the server (so it'll be down for a bit and then it'll be back up again and then at that point your paper will be able to use the copyright_holder bit).

**Comment by katyhuff** [comment]
Alright! Build server back up, everything building normally. You should be able to test it out in production for your own paper, @dalippa ! Thanks a ton!

**Comment by dalippa** [comment]
@katyhuff I double checked and the paper built as expected. Thanks!

**Comment by katyhuff** [comment]
Thank you! Open source for the win.

**Pull request merged**
