### PR TITLE
Paper: Storing Reproducible Results from Computational Experiments using Scientific Python Packages (Oxvig)

### PR DESCRIPTION
**Pull request by Chroxvi**
Submission of the paper "Storing Reproducible Results from Computational Experiments using Scientific Python Packages".

CC: @ThomasA, @t-larsen, @ppeder08

### CODE REVIEW

**Comment by suchow** [comment]
Here's some advice from Proselint (http://github.com/amperser/Proselint), a Python-based linter for prose:

```
35:175: weasel_words.very Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be. Found 7 times elsewhere.
```

**Comment by sbenthall** [comment]
This paper reads very well and presents useful Python software that supports reproducible research. Aside from minor spelling errors here and there, this paper is ready for acceptance.

**Comment by sbenthall** [comment]
(That was a review)

**Comment by Chroxvi** [comment]
We have now passed the official review deadline (30/6 2016), so I have updated the paper based on the comments from the reviews. Since only minor revisions were requested by the reviewers, I consider this to be the final revision of the paper.

@sbenthall Thanks for taking your time to review the paper. I have corrected several typos and spelling errors to address your comment.

@suchow Thanks for the Proselint suggestions. I have taken them into account in the revised version of the paper.

**Comment by jseabold** [comment]
Given we are past the deadline, I also don't have any requests for revisions beyond what the others have asked for and the changes that have been made. This is interesting work. I'd be interested to talk about how these packages for reproducibility fit into the container ecosystem, but that's beyond the scope of the paper.

**Comment by Chroxvi** [comment]
@jseabold It seems to me that quite a lot of people are trying to solve more or less the same problem using the container ecosystem as we are trying to solve using packages for reproducibility. That is, the problem of making computational results reproducible. Yet, it seems that there has not been done that much to combine the two approaches. I would certainly be interested in discussing how one might get the best from both. We should meet and discuss this at SciPy2016.

**Comment by sarostru** [comment]
Due to the complication of the proceedings deadline lining up with everyone's travel schedule to attend the conference we've decided to allow authors to spend an additional 2 days, that is until July 12th to complete any major changes to the submission.  This may impact your enjoyment of the conference, so we hope not too many of you need to take the time.  For reviewers, we ask that you read over this final document before the conference is over and post your decision here in the comments on or before July 17th.

Thanks and have a great Scipy!
Your proceedings co-chairs Scott Rostrup (@sarostru) and Sebastian Benthall (@sbenthall)

**Comment by sbenthall** [comment]
Thanks for the minor changes. Paper looks great.

**Comment by sarostru** [comment]
Based on the comments, adding the ready label, @Chroxvi if you could do a final careful proofread, since we don't have dedicated copy-editors, and @sbenthall and I will help with updating the proceedings build from draft to final.

**Comment by Chroxvi** [comment]
Sorry for the late reply. I have been taking some time off following the SciPy conference. 

I have done a final careful proofread of the paper and I believe it is ready for publication.

**Pull request merged**
