### PR TITLE
Paper: PySPLIT and TrendVis (Cross)

### PR DESCRIPTION
**Pull request by mscross**
TrendVis paper is close to ready for review, PySPLIT paper is still being fleshed out.

### CODE REVIEW

**Comment by katyhuff** [comment]
Hi @mscross : Can you please make one pull request per paper? They need to be reviewed (and built in our buildbot and merged if/when they're accepted) separately. Sorry to be a stickler for this rule, it's there because it allows us to keep reviews on the per-paper level. Does that make sense?

**Comment by mscross** [comment]
@katyhuff that makes sense.  Since they both live in the same branch, should I just make a second PR and title each with a different paper name?  Or is there another way I should do this?

**Comment by katyhuff** [comment]
@mscross , not exactly. You can see [here](http://nipy.bic.berkeley.edu:5000/) that our build server only picks up the first of the rst-containing folders that it finds in the pull request (in your case, it only builds the pysplit paper). You are going to want to do something that erases a little of your history, unfortunately, but because you made single commits that included changes to both papers, there's really no way around destroying a little history.



1. make two separate branches, each based on the scipy-conference/2015 branch 
```
git remote add upstream https://github.com/scipy-conference/scipy_proceedings.git
git fetch upstream
git checkout upstream/2015
git checkout -b pysplit
git checkout upstream/2015
git checkout -b trendvis
```

2) copy the trendvis-containing directory to the trendvis branch, commit it, push it, and pull request against our 2015 branch.
```
git checkout 2015
cp melissa_cross_t ~
git checkout trendvis
mv ~/melissa_cross_t .
git add mellissa_cross_t
git commit -am "commits trendvis paper in its own branch"
git push origin trendvis
<< go to github.com and make the trendvis -> 2015 pull request... let me know if this is confusing >>
```

3) copy the pysplit-containing directory to the pysplit branch, commit it, push it, and pull request against our 2015 branch.
```
git checkout 2015
cp melissa_cross_p ~
git checkout pysplit
mv ~/melissa_cross_p .
git add mellissa_cross_p
git commit -am "commits pysplit paper in its own branch"
git push origin pysplit
<< go to github.com and make the pysplit -> 2015 pull request... let me know if this is confusing >>
```


I just pulled that git workflow out of my head. I'm pretty sure it will work for you. If it doesn't and gives you a confusing error, please let me know asap. We are trying to assign reviewers to papers today and as it stands, you only have the pysplit paper building, so I'd like to make sure this gets cleared up so that you get reviewers for both.

**Comment by katyhuff** [comment]
Excellent! I'll close this one in favor of the other two pull requests!

**Pull request closed without merging**
