### PR TITLE
Paper: PMDA – Parallel Molecular Dynamics Analysis

### PR DESCRIPTION
**Pull request by orbeckst**
Dear Editors,

Please consider our contribution to SciPy 2019, *PMDA – Parallel Molecular Dynamics Analysis* by Shujie Fan @VOD555 , Max Linke @kain88-de , Ioannis Paraskevakos @iparask , Richard J. Gowers @richardjgowers, Michael Gecht @mimischi, Oliver Beckstein @orbeckst

Thank you,
Oliver Beckstein

----
If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

### CODE REVIEW

**Comment by akhalighi** [comment]
**REVIEWER COMMENTS:**

The article by Fan et al. introduces `PMDA`, an open-source Python library that allows for efficient analysis of particle trajectories resulting from molecular dynamics (MD) simulations. At the high level, `PMDA` provides a common interface to the split-apply-combine paradigm applied to analyze MD trajectory data. This is achieved by combining `Dask` and `MDAnalysis` to parallelize the simulation analysis tasks. Throughout the manuscript, Fan and colleagues clearly explain the motivation for their work as well as the API to use and extend `PMDA`. They have also benchmarked the performance of `PMDA` for different combinations of `Dask` schedulers and different means to read the input data which showed that analysis parallelization using `PMDA` can bring down the simulation time from hours to minutes in some special cases. In their submission, the authors diligently describe the architecture of `PMDA`, several key implementation details, and some use cases of the library. The domain-specific terminology of the work is explained in the manuscript and the provided `Python` code snippets allow non-expert `Python` programmers to also follow the workflow and benefit from the article. I believe the work by Fan et al. is a great contribution to the SciPy 2019 meeting and I would like to recommend the manuscript, in its current form, for inclusion in the conference proceedings.

**Comment by cyrush** [comment]
In this paper the authors provide an introduction to the PMDA Python library and describe the results of strong-scaling performance study of two analysis algorithms implemented with PMDA that were run at small scale on an HPC cluster.

PMDA provides an interface and framework for creating parallel MD trajectory analysis algorithms using Dask. PMDA provides a base class that abstracts out the stages of a `split-apply-combine` strategy. This `split-apply-combine` strategy supports a class of parallel algorithms where the input data is partitioned into compute blocks which are then processed individually in parallel and then optionally reduced. PMDA also provides a function wrapper that makes parallelizing a single function very simple in cases where a set of parallel constraints apply. 


The intro is clear - provides motivation, a good basic description of MD trajectory analysis, related tools, and why the authors choose Dask.  The sections that outline PMDA's interface and how to implement algorithms using PDMA clearly convey how to use the library and the benefits of the design. For the scaling study, the authors describe their experimental setup and provide detailed graphs and clear descriptions of the results.

PMDA is open source. The paper concludes with a brief outline of project resources, PMDA's software development processes, and interaction points for potential users. 

Here is a my brief reckoning of SciPy Review Criteria: (https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md)

+ Written Quality:  The paper is clear, authors bridge enough domain specific info to motivate their approach to non-MD experts. Great details in experimental setup and discussion. 

+ Technical Content & Novelty and Impact: Authors demonstrate their framework simplifies creating parallel algorithms for MD trajectory analysis tasks and clearly demonstrate strong-scaling reducing analysis time.

+ Verifiability: Authors provide detailed descriptions, links to data used in experiments, job submission scripts, etc. 


The paper is well written. I think it's strong enough to be accepted as is -- but I do have a few suggestions:

Minor typo to fix: 

"for example, the date may be histogrammed" --> "for example, the data may be histogrammed"


Section order:

The flow between "Methods: Performance Evaluation" sub-section and the "Results and Discussion" section feels broken by the "Using PMDA" Section.  The details in "Methods: Performance Evaluation" are very important to "Results and Discussion", but feel distant after switching context to read the "Using PMDA" section. Maybe move "Methods: Performance Evaluation" into the final section as a sub-section?


Scaling Study: 

In addition to graphs of wall clock times, a chart with percentage breakdowns of task times could also help convey parallel scaling issues and initialization amortization issues. These issues are described well in the text, however I found myself wanting to try to convert the wall time plots into a stacked graph with percentages to see if I was parsing the words correctly.

I understand creating new graphs is a non-trivial ask -- I do think they would help, but again I don't think they are necessary for acceptance.


Thanks for an interesting, well written submission!

-Cyrus

**Comment by orbeckst** [comment]
@akhalighi and @cyrush thank you for your thoughtful comments. We will try to improve the paper along the lines of your recommendations.

**Comment by deniederhut** [comment]
@orbeckst feel free to @ your reviewers when you feel this is ready for a second look 😄

**Comment by orbeckst** [comment]
@cyrush we addressed your comments, including the stacked plots (https://github.com/Becksteinlab/scipy_proceedings/issues/33). They are a really good addition to the paper. Thank you for the suggestion. Can we acknowledge you in the paper for the idea? (I will add a commit so that you can see what we would want to add.) Thanks again.

**Comment by orbeckst** [comment]
All last-minute edits done.

**Comment by cyrush** [comment]
@orbeckst @VOD555 thank you for the updates and for taking the time to create the extra plots. 
The stack % plots really help present the scalability of your test cases. Thanks for the acknowledgment  as well!

@deniederhut I strongly support including this paper the proceedings. In my view, authors went above and beyond our suggestions to strengthen an already well written paper.

**Comment by deniederhut** [comment]
Awesome. Thanks everyone!

**Pull request merged**
